### PR TITLE
fix(plugin/cors): treat empty Origin header same as missing header

### LINKED ISSUE #14352: Plugin(cors):Assertion failure on empty origin header
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.9

### Current Behavior

When I create a route with a CORS plugin specifying **at least two allowed origins**, and then attempt to access the route using curl with `header.Origin`=`''`(empty string)， receives empty reply from server.

### Expected Behavior

Not empty reply.

### Steps To Reproduce

1. Create a route with a CORS plugin.

Route Config:
```
{
  "preserve_host": false,
  "id": "737e3275-8a23-489d-a692-9307e01c3b83",
  "headers": null,
  "name": "echo-route-a",
  "service": {
    "id": "727d0f37-f96f-439a-b154-9953f039748c"
  },
  "strip_path": true,
  "request_buffering": true,
  "response_buffering": true,
  "https_redirect_status_code": 426,
  "protocols": [
    "http",
    "https"
  ],
  "snis": null,
  "path_handling": "v0",
  "destinations": null,
  "tags": [],
  "paths": [
    "/"
  ],
  "regex_priority": 0,
  "methods": null,
  "sources": null,
  "hosts": [
    "echo-test.com"
  ]
}
```

CORS Plugin:
```
{
  "id": "287d5fdc-1125-4af3-aa92-ec8dbdadbe4b",
  "protocols": [
    "http",
    "https"
  ],
  "instance_name": null,
  "consumer": null,
  "enabled": true,
  "tags": null,
  "config": {
    "exposed_headers": null,
    "headers": null,
    "origins": [
      "echo-test.com",
      "echo-test2.com"
    ],
    "preflight_continue": false,
    "max_age": null,
    "methods": [
      "GET",
      "HEAD",
      "OPTIONS"
    ],
    "private_network": false,
    "credentials": false
  },
  "service": null,
  "name": "cors",
  "route": {
    "id": "737e3275-8a23-489d-a692-9307e01c3b83"
  }
}
```

2. Create a request
`curl -ivv http://localhost:8000/ -H "Host: echo-test.com" -H "Origin;"`  (The `header.Origin` field is set to an empty string)

curl client info:
```
* Host localhost:8000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8000...
* Connected to localhost (::1) port 8000
> GET / HTTP/1.1
> Host: echo-test.com
> User-Agent: curl/8.7.1
> Accept: */*
> Origin:
>
* Request completely sent off
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

Kong server error log:
```
failed to run header_filter_by_lua*: /usr/local/share/lua/5.1/kong/plugins/cors/handler.lua:34: invalid url
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/plugins/cors/handler.lua:34: in function 'normalize_origin'
	/usr/local/share/lua/5.1/kong/plugins/cors/handler.lua:132: in function 'configure_origin'
	/usr/local/share/lua/5.1/kong/plugins/cors/handler.lua:245: in function </usr/local/share/lua/5.1/kong/plugins/cors/handler.lua:240>
	/usr/local/share/lua/5.1/kong/init.lua:465: in function 'execute_collected_plugins_iterator'
	/usr/local/share/lua/5.1/kong/init.lua:1633: in function 'header_filter'
	header_filter_by_lua(nginx-kong.conf:116):2: in main chunk while reading response header from upstream
```

### Anything else?

The assertion failure at https://github.com/Kong/kong/blob/6b9d32b1a065a7c4404f9c015cc084fab447f98e/kong/plugins/cors/handler.lua#L34 occurs when the domain parameter is an empty string. This appears to happen when the request origin (req_origin) is passed as an empty string through the CORS plugin logic.

**Proposed Fix**
We should add a check for empty origin values at:

https://github.com/Kong/kong/blob/6b9d32b1a065a7c4404f9c015cc084fab447f98e/kong/plugins/cors/handler.lua#L194
https://github.com/Kong/kong/blob/6b9d32b1a065a7c4404f9c015cc084fab447f98e/kong/plugins/cors/handler.lua#L250
By adding a condition `req_origin ~= ""` before processing the origin value, we can prevent empty strings from reaching the assertion check while maintaining valid CORS behavior.

If acceptable, I'd be happy to submit a PR to implement this fix.

### PR DESCRIPTION
**Pull request by dingjiayi**
### Summary
This change ensures that an empty Origin header (`Origin: ""`) is treated 
the same way as a missing Origin header, fixing inconsistent behavior 
between these two cases.

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #14352

### CODE REVIEW

File: kong/plugins/cors/handler.lua [hunk 1]
```diff
@@ -89,7 +89,7 @@ local function configure_origin(conf, header_filter, req_origin)
     end
   end
 
-  if req_origin then
+  if req_origin and req_origin ~= "" then
```
Comment (StarlightIbuki) [inline kong/plugins/cors/handler.lua:92]: Perhaps this way it's simpler?
```suggestion
	if req_origin == "" then
		req_origin = nil
	end

  if req_origin then
```

**Review by StarlightIbuki — APPROVED** [review]
Overall LGTM. Not a blocker but please take a look

File: kong/plugins/cors/handler.lua (hunk 1 above)
Comment (dingjiayi) [reply kong/plugins/cors/handler.lua:92]: Hi @Starlightbuki,

Thanks a lot for reviewing this PR and for your suggestion!

I agree, your proposed change does make the conditional logic simpler and the code cleaner. That's a good direction.

One minor point I noticed is that this approach would convert an empty string `req_origin` (`""`) into `nil`. While this doesn't have a functional impact on the current plugin's behavior, it does lead to a subtle loss of information by removing the distinction between an explicitly empty origin and a non-existent one (`nil`).

Inspired by your comment aiming for simplification, what do you think about encapsulating this check into a small helper function instead? This way, we can keep the main logic clean while preserving the original values.

Something like this:

```
local function is_valid_origin(origin)
  return origin and origin ~= ""
end
```
We could then use `if is_valid_origin(req_origin) then ...` in the configure_origin function.

Let me know your thoughts! Thanks again for the feedback.

Comment (StarlightIbuki) [reply kong/plugins/cors/handler.lua:92]: That's also a good option. Anyway, this PR is good enough. Choose anything that works for you should be fine

**Comment by dingjiayi** [comment]
Hi @StarlightIbuki 👋, a friendly ping to let me know if there's anything I can clarify or adjust to move this forward.

File: changelog/unreleased/kong/fix-cors-allow-empty-string-origin.yml [hunk 2]
```diff
@@ -0,0 +1,3 @@
+message: Fixed a bug where requests with empty origin headers would cause empty reply from server
```
Comment (chronolaw) [inline changelog/unreleased/kong/fix-cors-allow-empty-string-origin.yml:1]:
```suggestion
message: **cors**: Fixed a bug where requests with empty `origin` headers would cause empty reply from server.
```

File: kong/plugins/cors/handler.lua [hunk 3]
```diff
@@ -30,6 +30,10 @@ local config_cache = setmetatable({}, mt_cache)
 local normalized_req_domains = lrucache.new(10e3)
 
 
+local function is_origin_provided(origin)
+  return origin and origin ~= ""
+end
+
```
Comment (chronolaw) [inline kong/plugins/cors/handler.lua:36]: style: should be 2 blank lines.

File: spec/03-plugins/13-cors/01-access_spec.lua [hunk 4]
```diff
@@ -232,6 +232,8 @@ hybrid_helper.run_for_each_deploy({}, function(helpers, strategy, deploy, rpc, r
       },
     }
 
+    local absent_origin_headers = { nil, "" }
```
Comment (chronolaw) [inline spec/03-plugins/13-cors/01-access_spec.lua:235]:
```suggestion
    local absent_origin_headers = { nil, "", }
```

File: spec/03-plugins/13-cors/01-access_spec.lua [hunk 5]
```diff
@@ -1161,31 +1163,36 @@ hybrid_helper.run_for_each_deploy({}, function(helpers, strategy, deploy, rpc, r
...
-          headers = {
-            ["Host"]   = "cors15.test",
-          }
-        })
-        assert.res_status(200, res)
-        assert.is_nil(res.headers["Access-Control-Allow-Origin"])
-        assert.is_nil(res.headers["Access-Control-Allow-Credentials"])
-        assert.is_nil(res.headers["Access-Control-Expose-Headers"])
-      end)
+      for i = 1, 2 do
```
Comment (chronolaw) [inline spec/03-plugins/13-cors/01-access_spec.lua:1166]: could be 
```
for _, v in ipairs(absent_origin_headers) do
```

File: spec/03-plugins/13-cors/01-access_spec.lua [hunk 6]
```diff
@@ -1161,31 +1163,36 @@ hybrid_helper.run_for_each_deploy({}, function(helpers, strategy, deploy, rpc, r
...
+        local origin = absent_origin_headers[i]
+        it("when allow_origin_absent is disabled with missing Origin header[" .. i .. "], no ACAO is returned", function()
```
Comment (chronolaw) [inline spec/03-plugins/13-cors/01-access_spec.lua:1168]: We could use `tosting(v)`.

**Comment by StarlightIbuki** [comment]
@dingjiayi Hi. Please address the new comments. Our policy requires 2 approvals from maintainers to merge a PR.

File: spec/03-plugins/13-cors/01-access_spec.lua (hunk 5 above)
Comment (dingjiayi) [reply spec/03-plugins/13-cors/01-access_spec.lua:1166]: Thanks for the suggestion.

However, in this specific case, `ipairs` won't work as intended because the `absent_origin_headers` table contains `nil` values. Lua's `ipairs` iterator stops when it encounters the first integer key `i` for which `t[i]` is `nil`.

Similarly, using `for i = 1, #absent_origin_headers` is also unreliable for tables with `nil` values interspersed. (e.g. `#{"", nil}` is 1 and `#{nil, ""}` is 2).

I struggled a bit to find a cleaner solution here myself due to these Lua behaviors with `nil`s in sequences.

Comment (chronolaw) [reply spec/03-plugins/13-cors/01-access_spec.lua:1166]: Sorry, I did not notice that, you are correct, could we change like this:
```
for i=1, #absent_origin_headers do
```

Comment (dingjiayi) [reply spec/03-plugins/13-cors/01-access_spec.lua:1166]: Thank you @chronolaw , this approach would work as intended.

However, we need to ensure that the order of elements in `absent_origin_headers remains` fixed and cannot be modified. `#{nil, ""}` would return 2, while `#{"", nil}` would return 1.
Perhaps we should add a clear comment where `absent_origin_headers` is defined to indicate that the element positions must not be changed? Something like:

```
-- IMPORTANT: Do not modify the order of elements in this array
-- as the presence of nil values affects the # operator result
-- and could break the validation logic if reordered
local absent_origin_headers = { nil, "",}
```

Comment (chronolaw) [reply spec/03-plugins/13-cors/01-access_spec.lua:1166]: Perhaps we could define a constant `LEN = 2` to avoid magic number.

File: spec/03-plugins/13-cors/01-access_spec.lua (hunk 6 above)
Comment (dingjiayi) [reply spec/03-plugins/13-cors/01-access_spec.lua:1168]: Yes, using the value directly would be more intuitive, I agree.

The reason I chose to use the index rather than the value here is because when the value is an empty string, the output wouldn't be as clear visually in the test results.

Would it be better to use  `it(string.format("when allow_origin_absent is disabled with missing Origin header value:%q , no ACAO is returned", origin))` instead?（Using `string.format("...%q...", v)`） This way we can see the exact value (including empty strings) in a more readable format in the test output.

What do you think about this approach?

File: changelog/unreleased/kong/fix-cors-allow-empty-string-origin.yml (hunk 2 above)
Comment (dingjiayi) [reply changelog/unreleased/kong/fix-cors-allow-empty-string-origin.yml]: changed.

File: spec/03-plugins/13-cors/01-access_spec.lua (hunk 4 above)
Comment (dingjiayi) [reply spec/03-plugins/13-cors/01-access_spec.lua]: changed.

File: spec/03-plugins/13-cors/01-access_spec.lua (hunk 5 above)
Comment (dingjiayi) [reply spec/03-plugins/13-cors/01-access_spec.lua]: changed.

**Review by chronolaw — APPROVED** [review]

**Review by StarlightIbuki — APPROVED** [review]

**Review by chobits — APPROVED** [review]

**Comment by chobits** [comment]
hi @ms2008 and @windmgc could you take a look at again? I'm reviewing community PR and issues and find this one has fixed one issue.https://github.com/Kong/kong/issues/14352

**Review by ms2008 — APPROVED** [review]
LGTM
