### PR TITLE
fix(key-auth): add missing www-authenticate headers

### LINKED ISSUE #7772: WWW-Authenticate header not present when Kong and plugins return HTTP status 401
### Summary
- Kong version (`$ kong version`) - 2.4.1
According to the HTTP specification for 401 error, https://httpwg.org/specs/rfc7235.html#status.401, WWW-Authenticate header field containing at least one challenge applicable to the target resource must be returned in the response.

At least the following plugins were observed to not returning the header when returning 401.
1) basic-auth
2) key-auth
3) ldap-auth
4) jwt

For Oauth2 related plugins **oauth2** and **jwt**, below are additional requirements from the related RFCs. They further define what needs to be included in the WWW-Authenticate header.

1) https://datatracker.ietf.org/doc/html/rfc6750#section-3
2) https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

### Steps To Reproduce
Exercise any unit tests of those plugins that would return 401 error and add an assertion in those test to detect the header, the assertion would fail.

For example in jwt pluging 03_acces_spec.lua, add the **LAST** assertion and execute the test, it will fail.

    describe("refusals", function()
      it("returns 401 Unauthorized if no JWT is found in the request", function()
        local res = assert(proxy_client:send {
          method  = "GET",
          path    = "/request",
          headers = {
            ["Host"] = "jwt1.com",
          }
        })
        assert.res_status(401, res)
        assert.not_nil(body.headers["WWW-Authenticate"])
      end)

### PR DESCRIPTION
**Pull request by nowNick**
### Summary

When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. Key auth was missing this header on some responses. This PR also adds a possibility to configure an optional parameter - realm (defaults to `null`).

### Related PRs:
- https://github.com/Kong/kong/pull/11791
- https://github.com/Kong/kong/pull/11792
- https://github.com/Kong/kong/pull/11795
- https://github.com/Kong/kong/pull/11820
- https://github.com/Kong/kong/pull/11833

### RFCs & Materials

- https://httpwg.org/specs/rfc7235.html#status.401
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [x] N/A ~~There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~~

### Full changelog

- add `WWW-Authenticate` header to all key-auth 401 response

### Issue reference

- Fix #7772
- KAG-321

### CODE REVIEW

**Comment by bungle** [comment]
@nowNick,

How does this behave in `AND`/`OR` scenario? E.g. `basic-auth` AND/OR `key-auth`?

**Comment by nowNick** [comment]
Hey @bungle !

When I was thinking about it I came to the conclusion that it's not necessary to handle those scenarios or it's impossible to do them, but my understanding could be wrong.

Basically when it comes to `OR` I think we do not need to handle the `WWW-Authenticate` since the response should be 200 unless there's request termination plugin turned on that forbids anonymous access.... well... now that I think of it maybe we should add proper `WWW-Authenticate` headers to that plugin as well. Will it be possible to look up what auth plugins the request has fallen through so that we could create a proper `WWW-Authenticate` header at the request termination plugin turn? 
I'm basing my understanding on this: https://docs.konghq.com/gateway/latest/kong-plugins/authentication/reference/#multiple-authentication

Now when it comes to `AND` scenario I wonder whether it's possible to return all of the challenges. Correct me if I'm wrong but if there's the so called `AND` condition - when a single auth plugin fails and it returns 401 will another auth plugin code execute or will the request be terminated since the `AND` condition already failed (basically an early exit)? 
If so I concluded that it's impossible to incorporate other challenges to certain plugin 401 response if there's `AND` condition between them. Is my understanding correct?

**Review by kikito — APPROVED** [review]
Approved with a couple minor comments

File: spec/03-plugins/09-key-auth/02-access_spec.lua [hunk 1]
```diff
@@ -259,7 +282,7 @@ for _, strategy in helpers.each_strategy() do
           }
         })
         res:read_body()
-        assert.equal('Key realm="' .. meta._NAME .. '"', res.headers["WWW-Authenticate"])
+        assert.equal('Key', res.headers["WWW-Authenticate"])
```
[the remark this answers is not in the document]
Comment (nowNick) [reply spec/03-plugins/09-key-auth/02-access_spec.lua:285]: That's correct. The plugin instance resolved on `key-auth1.com` doesn't have `realm` set and since it's optional for everything except `basic-auth` then we don't want to add it. This diff shows that we don't include `realm="something"` unless it's been explicitly set

File: kong/plugins/key-auth/handler.lua [hunk 2]
```diff
@@ -99,11 +97,19 @@ local function get_body()
...
+local function server_error(message)
+  return { status = 500, message = message }
+end
+
+local function unauthorized(message, www_auth_content)
+  return { status = 401, message = message, headers = { ["WWW-Authenticate"] = www_auth_content } }
+end
 
 local function do_authentication(conf)
+  local www_auth_content = conf.realm and fmt('Key realm="%s"', conf.realm) or 'Key'
```
Comment (bungle) [inline kong/plugins/key-auth/handler.lua:109]: This can be moved closer to usage.

**Review by bungle — DISMISSED** [review]
Just a small change req.

**Comment by locao** [comment]
@nowNick there conflicts preventing us from merging this PR, can you check, please?

File: kong/plugins/key-auth/handler.lua [hunk 3]
```diff
@@ -203,44 +207,58 @@ local function do_authentication(conf)
...
-    return nil, ERR_UNEXPECTED
+    return nil, server_error(ERR_UNEXPECTED)
   end
 
   set_consumer(consumer, credential)
 
   return true
 end
 
+local function set_anonymous_consumer(anonymous)
```
Comment (nowNick) [inline kong/plugins/key-auth/handler.lua:218]: Just some small refactoring - I've extracted from `KeyAuthHandler:access` function following funcs:
- `set_anonymous_consumer`
- `logical_OR_authentication`
- `logical_AND_authentication`

File: kong/plugins/key-auth/schema.lua [hunk 4]
```diff
@@ -20,6 +20,7 @@ return {
           { key_in_query = { description = "If enabled (default), the plugin reads the query parameter in the request and tries to find the key in it.", type = "boolean", required = true, default = true }, },
           { key_in_body = { description = "If enabled, the plugin reads the request body. Supported MIME types: `application/www-form-urlencoded`, `application/json`, and `multipart/form-data`.", type = "boolean", required = true, default = false }, },
           { run_on_preflight = { description = "A boolean value that indicates whether the plugin should run (and try to authenticate) on `OPTIONS` preflight requests. If set to `false`, then `OPTIONS` requests are always allowed.", type = "boolean", required = true, default = true }, },
+          { realm = { description = "When authentication or authorization fails, or there is an unexpected error, the plugin sends an `WWW-Authenticate` header with the `realm` attribute value.", type = "string", required = false }, },
```
Comment (flrgh) [inline kong/plugins/key-auth/schema.lua:23]: > or there is an unexpected error

Is this true? It doesn't seem to be the case with any of the paths that return `server_error()`/500

**Review by flrgh — APPROVED** [review]

File: kong/plugins/key-auth/schema.lua (hunk 4 above)
Comment (nowNick) [reply kong/plugins/key-auth/schema.lua:23]: Oh! Yeah that's incorrect! Thanks for spotting it 👍

**Comment by bungle** [comment]
> Hey @bungle !
> 
> When I was thinking about it I came to the conclusion that it's not necessary to handle those scenarios or it's impossible to do them, but my understanding could be wrong.
> 
> Basically when it comes to `OR` I think we do not need to handle the `WWW-Authenticate` since the response should be 200 unless there's request termination plugin turned on that forbids anonymous access.... well... now that I think of it maybe we should add proper `WWW-Authenticate` headers to that plugin as well. Will it be possible to look up what auth plugins the request has fallen through so that we could create a proper `WWW-Authenticate` header at the request termination plugin turn? I'm basing my understanding on this: https://docs.konghq.com/gateway/latest/kong-plugins/authentication/reference/#multiple-authentication

It is possible at least in theory, but I agree it feels like a stretch. Not part of this PR. We would need to modify all auth plugins to add/append something in context. So lets skip it for now.

> Now when it comes to `AND` scenario I wonder whether it's possible to return all of the challenges. Correct me if I'm wrong but if there's the so called `AND` condition - when a single auth plugin fails and it returns 401 will another auth plugin code execute or will the request be terminated since the `AND` condition already failed (basically an early exit)?

The other plugins (that come after) access phase will not be executed if one auth plugin terminates. But they are still collected, so their `header_filter` will still be called. And in header filter it is possible to do something like this. But again, complicates the thing and all our auth plugins need to implement header_filter phase too. Which is probably not a good idea.

File: kong/plugins/key-auth/handler.lua [hunk 5]
```diff
@@ -99,13 +97,21 @@ local function get_body()
   return body
 end
 
+local function server_error(message)
+  return { status = 500, message = message }
+end
+
+local function unauthorized(message, www_auth_content)
+  return { status = 401, message = message, headers = { ["WWW-Authenticate"] = www_auth_content } }
```
Comment (bungle) [inline kong/plugins/key-auth/handler.lua:105]: The original one had `tables` preallocated, this will allocate some memory on each failure. I am not sure was the original intent to avoid creating tables. But this is so small thing that I am fine with this.

File: kong/plugins/key-auth/schema.lua (hunk 4 above)
Comment (bungle) [reply kong/plugins/key-auth/schema.lua:23]: @nowNick, I am not sure what type of authorizaton this plugin does, thus I would remove the `or auhorization`. What do you think.

**Review by bungle — APPROVED** [review]
Approved with a comment.

File: kong/plugins/key-auth/schema.lua (hunk 4 above)
Comment (nowNick) [reply kong/plugins/key-auth/schema.lua]: Fixed the description ✅
