### PR TITLE
fix(proxy) do not clear Upgrade header if response Connection header contains Upgrade

### LINKED ISSUE #5714: Error during WebSocket handshake: 'Upgrade' header is missing
- Kong `2.0.2`
- Server Config
```json
{
    "host": "api.dev.ourfor.top",
    "created_at": 1584945910,
    "connect_timeout": 60000,
    "id": "46f07b22-d0e8-4f5e-a05f-eb3f57e4da54",
    "protocol": "http",
    "name": "api",
    "read_timeout": 60000,
    "port": 80,
    "path": null,
    "updated_at": 1584945910,
    "retries": 5,
    "write_timeout": 60000,
    "tags": null,
    "client_certificate": null
}
```
- Route Config
```json
{
    "id": "de596b50-c3b9-48aa-98e2-5d3d7e245230",
    "path_handling": "v0",
    "paths": null,
    "destinations": null,
    "headers": null,
    "protocols": [
        "http",
        "https"
    ],
    "methods": null,
    "snis": null,
    "service": {
        "id": "46f07b22-d0e8-4f5e-a05f-eb3f57e4da54"
    },
    "name": null,
    "strip_path": true,
    "preserve_host": false,
    "regex_priority": 0,
    "updated_at": 1584945983,
    "sources": null,
    "hosts": [
        "demo.ourfor.top"
    ],
    "https_redirect_status_code": 426,
    "tags": null,
    "created_at": 1584945983
}
```
Xnip2020-03-23_15-55-15

Xnip2020-03-23_15-56-23

http works ok, but can't connect websocket, what should I do?

### LINKED ISSUE #6691: how to set http upgrade to websocket
i want to use kong to proxy kube-apiserver request,
some request use http upgade to websocket
likes with nginx config:
```
        proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
```
it works well on nginx;

that my kong config:
```
curl -s  http://localhost:8001/services|jq
{
  "next": null,
  "data": [
    {
      "host": "192.168.200.199",
      "id": "007b38a9-e7c0-4123-80f9-6a29e8c451e0",
      "protocol": "https",
      "read_timeout": 60000,
      "tls_verify_depth": null,
      "port": 6443,
      "updated_at": 1609308727,
      "ca_certificates": null,
      "created_at": 1609308727,
      "connect_timeout": 60000,
      "write_timeout": 60000,
      "name": "k8s_https",
      "retries": 5,
      "path": null,
      "tls_verify": null,
      "tags": null,
      "client_certificate": null
    }
  ]
}

{
  "next": null,
  "data": [
    {
      "id": "38366f6b-6fd8-4fd3-b796-9a61ca4d3fcc",
      "tags": null,
      "paths": [
        "/api"
      ],
      "destinations": null,
      "headers": null,
      "protocols": [
        "https"
      ],
      "strip_path": true,
      "created_at": 1609309284,
      "request_buffering": true,
      "hosts": null,
      "name": "k8sapi",
      "updated_at": 1609309284,
      "snis": null,
      "preserve_host": false,
      "regex_priority": 0,
      "methods": null,
      "sources": null,
      "response_buffering": true,
      "https_redirect_status_code": 426,
      "path_handling": "v0",
      "service": {
        "id": "007b38a9-e7c0-4123-80f9-6a29e8c451e0"
      }
    }
  ]
}
curl  -s   http://localhost:8001/services/k8s_https/plugins|jq
{
  "next": null,
  "data": [
    {
      "created_at": 1609316964,
      "id": "2d4d50e6-44e7-4fa0-8179-36e6aa8e827a",
      "tags": null,
      "enabled": true,
      "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
      ],
      "name": "request-transformer",
      "consumer": null,
      "service": {
        "id": "007b38a9-e7c0-4123-80f9-6a29e8c451e0"
      },
      "route": null,
      "config": {
        "remove": {
          "querystring": [],
          "headers": [],
          "body": []
        },
        "replace": {
          "querystring": [],
          "headers": [
            "Connection:Upgrade"
          ],
          "uri": null,
          "body": []
        },
        "http_method": null,
        "add": {
          "querystring": [],
          "headers": [
            "Upgrade:SPDY/3.1"
          ],
          "body": []
        },
        "append": {
          "querystring": [],
          "headers": [],
          "body": []
        },
        "rename": {
          "querystring": [],
          "headers": [],
          "body": []
        }
      }
    }
  ]
}
```
it works well on https;
but when i use kubectl exec ,it response ```Error from server (BadRequest): Upgrade request required```

how should i do

### LINKED ISSUE #6921: Error during WebSocket handshake: 'Upgrade' header is missing
https://github.com/Kong/kong/blob/b305fc58892d40200e08bf93f9d8f51d8c2244c4/kong/runloop/handler.lua#L1249

The code maybe is not running for me.
I change the  `var.upstream_connection = "upgrade"`  is  nomarl.

### PR DESCRIPTION
**Pull request by bungle**
### Summary

This issue is documented by @goober at:
https://github.com/goober/kong-websocket-bug

### Issues Resolved

Fix #6691
Fix #5714
Fix #6921

### CODE REVIEW

**Comment by bungle** [comment]
Reviewers: I tried to add a test, but with our mock server, I cannot set `Connection` header. Thus it means that I need to implement test with some low-level custom socket code, which I didn't think is worth it. I manually tested it with `ncat`, and seems to work as expected.

File: kong/runloop/handler.lua [hunk 1]
```diff
@@ -1400,11 +1401,13 @@ return {
 
       -- clear hop-by-hop response headers:
       for _, header_name in csv(var.upstream_http_connection) do
-        header[header_name] = nil
+        if header_name ~= "close" and header_name ~= "upgrade" and header_name ~= "keep-alive" then
```
Comment (dndx) [inline kong/runloop/handler.lua:1404]: Does this needs to be:

```
if lower(header_name) ~= "close" and lower(header_name) ~= "upgrade" and lower(header_name) ~= "keep-alive" then
```

**Review by dndx — APPROVED** [review]
