### PR TITLE
fix(api) fix output of records in /plugins/schema

### LINKED ISSUE #4137: Plugin schema inconsistentcy for request-transformer
### Summary

Plugin schema for request transformer contains fields in a nested object as opposed to an array.

### Steps To Reproduce
```
http :8001/plugins/schema/request-transformer
-- stripped out  
      {
            "remove": {
                "fields": {
                    "1": {
                        "body": {
                            "default": {},
                            "elements": {
                                "type": "string"
                            },
                            "type": "array"
                        }
                    },
                    "2": {
                        "headers": {
                            "default": {},
                            "elements": {
                                "type": "string"
                            },
                            "type": "array"
                        }
                    },
                    "3": {
                        "querystring": {
                            "default": {},
                            "elements": {
                                "type": "string"
                            },
                            "type": "array"
                        }
                    },
                    "body": {
                        "default": {},
                        "elements": {
                            "type": "string"
                        },
                        "type": "array"
                    },
                    "headers": {
                        "default": {},
                        "elements": {
                            "type": "string"
                        },
                        "type": "array"
                    },
                    "querystring": {
                        "default": {},
                        "elements": {
                            "type": "string"
                        },
                        "type": "array"
                    }
                },
                "required": true,
                "type": "record"
            }
        },
-- stripped out
```

The `fields` property of schema of an object should be an array and not an object.
Also, as can be seen, the fields are again nested into `1`, `2`, `3`, and are also present in the fields object itself, which seems ambiguous.
 
### Additional Details & Logs

- Kong version (`$ kong version`) 1.0.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) none
- Operating system Ubuntu

### PR DESCRIPTION
**Pull request by hishamhm**
* Ensure that plugin schemas return sub-fields of nested records in the same
format as the toplevel `fields` entry (i.e., as an array of single-fields
objects, so that the field order can be retrieved).
* Ensure `fields` in `/plugins/schema` always returns a JSON array,
even when it is empty (as in the prometheus plugin).

This produces an incompatible output from that of 1.0.0, but I'm opening this against `master` because the one in 1.0.0 is arguably broken, so this produces the intended result.

Fixes #4137.

### CODE REVIEW

File: kong/api/routes/plugins.lua [hunk 1]
```diff
@@ -70,14 +70,50 @@ end
...
+  local fdata_to_jsonable
+
+  local function fields_to_jsonable(fields)
+    local out = {}
+    for _, field in ipairs(fields) do
+      local fname = next(field)
+      local fdata = field[fname]
+      insert(out, { [fname] = fdata_to_jsonable(fdata, "no") })
+    end
+    setmetatable(out, cjson.empty_array_mt)
```
Comment (thibaultcha) [inline kong/api/routes/plugins.lua]: Here, we now that `fields` is always an Array. We should use [cjson.array_mt](https://github.com/openresty/lua-cjson#array_mt) instead, which is is preferred over `empty_array_mt`. The latter is less efficient and, while not documented, is scheduled for deprecation some time in the future since `array_mt` is a better pattern.

File: kong/api/routes/plugins.lua [hunk 2]
```diff
@@ -70,14 +70,50 @@ end
...
+    return out
+  end
+
```
Comment (thibaultcha) [inline kong/api/routes/plugins.lua]: style: missing line break in between functions declarations

File: kong/api/routes/plugins.lua [hunk 3]
```diff
@@ -94,20 +130,14 @@ do
         out[k] = v
       end
     end
+    if is_array == "yes" or is_array == "maybe" then
+      setmetatable(out, cjson.empty_array_mt)
```
Comment (thibaultcha) [inline kong/api/routes/plugins.lua]: Consider using `array_mt` if possible. The issues with `empty_array_mt` were partially described in my other comment, but overall, it makes for unpredictable results (or hard to predict) since this will leave tables to be encoded as an Object or an Array solely depending on whether they are empty or not... It could be that the `maybe` branch isn't sure how to encode the table, but we better be certain if possible. The same way, the table could deserve to be encoded as an empty Object in some cases, while we are making it an empty Array with this metatable. And vice-versa if the table _has_ fields.

**Comment by hishamhm** [comment]
@thibaultcha Review addressed! Thanks for the tip about `array_mt`!

File: spec/02-integration/04-admin_api/04-plugins_routes_spec.lua [hunk 4]
```diff
@@ -241,6 +241,19 @@ for _, strategy in helpers.each_strategy() do
             assert.is_table(json.fields)
           end
         end)
+        it("returns nested records as arrays", function()
+          for plugin, _ in pairs(helpers.test_conf.loaded_plugins) do
+            local res = assert(client:send {
+              method = "GET",
+              path = "/plugins/schema/request-transformer",
```
Comment (thibaultcha) [inline spec/02-integration/04-admin_api/04-plugins_routes_spec.lua]: The plugin name is hard-coded here. The surrounding loop is useless (and the below assertions about `default:[]` need to be conditionally triggered).

Comment (hishamhm) [reply spec/02-integration/04-admin_api/04-plugins_routes_spec.lua]: welp, I thought I copied only the inside of the block of the previous test, not the for loop
