### PR TITLE
fix(hmac-auth) add deprecation transition for pr #3339

### LINKED ISSUE #3672: PR #3339 in Kong 0.13.1 breaks existing hmac auth clients
PR #3339 breaks existing hmac auth clients

Before Kong 0.13.1, Kong calculated signatures using `request-line` that did not include the query string. This Pull Request released in 0.13.1 significantly changes the signature calculation to include the query string which breaks existing clients. What is the recommended approach to upgrade to Kong 0.13.1 without breaking existing clients? There doesn’t appear to be a way to configure Kong allow both signing algorithms for an appropriate transition period.

I’m in the process of upgrading our clusters to 0.13.1 but this is a major breaking change which breaks all existing clients so we’re basically stuck on Kong 0.13.0 or below because the older Kong versions don’t support the new algorithm and Kong 0.13.1+ doesn’t support the old algorithm. “Cutting-over" the new signing algorithm is basically impossible to coordinate with all existing clients simultaneously without incurring significant amounts of downtime.

Please help

### PR DESCRIPTION
**Pull request by mlehner616**
### Summary
Add deprecation transition for PR #3339 by adding support for older signatures generated from `request-line` without the query_string. This is intended to be a patch on 0.13.1 but may apply to 0.14+ although I haven't tested this. 

### Full changelog
* add deprecation hmac-auth transition for pr #3339 

### Issues resolved

Fix #3672

### CODE REVIEW

**Comment by thibaultcha** [comment]
@mlehner616 Thanks for taking the initiative here!

@shashiranjan84 Will you help review the proposed patch for this behaviour? Thanks!

File: kong/plugins/hmac-auth/access.lua [hunk 1]
```diff
@@ -157,11 +157,48 @@ local function create_hash(request, hmac_params, headers)
...
+      signing_string = signing_string .. "\n"
+    end
+  end
+  return hmac[hmac_params.algorithm](hmac_params.secret, signing_string)
+end
+
 local function validate_signature(request, hmac_params, headers)
-  local signature_1 = create_hash(request, hmac_params, headers)
-  local signature_2 = ngx_decode_base64(hmac_params.signature)
+  local signature_1            = create_hash(request, hmac_params, headers)
```
Comment (shashiranjan84) [inline kong/plugins/hmac-auth/access.lua]: we don't need extra space before assignment operator.

File: kong/plugins/hmac-auth/access.lua [hunk 2]
```diff
@@ -157,11 +157,48 @@ local function create_hash(request, hmac_params, headers)
...
+  local signature_2            = ngx_decode_base64(hmac_params.signature)
```
Comment (shashiranjan84) [inline kong/plugins/hmac-auth/access.lua]: ditto

Comment (shashiranjan84) [reply kong/plugins/hmac-auth/access.lua]: Also we don't need to create both the signature at once, one should be fall back and only be created if needed.

Comment (mlehner616) [reply kong/plugins/hmac-auth/access.lua]: @shashiranjan84 Whitespace removed, My commit from yesterday should have included the deprecated signature creation into the conditional. This looks like it would do what you're describing.

**Comment by mlehner616** [comment]
@shashiranjan84 I made the changes you requested, I haven't had a chance to write tests for this yet.

File: kong/plugins/hmac-auth/access.lua (hunk 2 above)
Comment (shashiranjan84) [reply kong/plugins/hmac-auth/access.lua]: You are right. Thanks again for your effort, we just need add test, which would be very similar to https://github.com/Kong/kong/blob/master/spec/03-plugins/20-hmac-auth/03-access_spec.lua#L1150, you would just need to create request signature without query-param

Comment (mlehner616) [reply kong/plugins/hmac-auth/access.lua]: Test Added

**Comment by shashiranjan84** [comment]
@mlehner616 thanks, we will review it.

File: spec/03-plugins/20-hmac-auth/03-access_spec.lua [hunk 3]
```diff
@@ -1080,6 +1080,47 @@ for _, strategy in helpers.each_strategy() do
         assert.res_status(200, res)
       end)
 
+      it("should pass with GET with request-line having query param but signed without query param", function()
```
[the remark this answers is not in the document]
Comment (mlehner616) [reply spec/03-plugins/20-hmac-auth/03-access_spec.lua]: done

**Comment by mlehner616** [comment]
@thibaultcha @shashiranjan84  Thanks for the feedback. I've committed changes that address your latest suggestions. Let me know if there are any other tweaks needed. Is there any chance this PR will get backported to a 0.13.2+ release? We're actually blocked on the 0.14 versions right now since we're not ready to drop API support.

**Comment by thibaultcha** [comment]
@mlehner616 We do not have plans for a 0.13.2 version so far.

> not ready to drop API support.

Not sure what you mean by that. In 0.14, the API entity is still supported (`/apis` on the Admin API). or are you talking about other specific changes in the Admin API itself?

**Comment by mlehner616** [comment]
Sorry, I thought I remember seeing 0.14 dropped API entities so it looks like I misread that section. Thanks for the clarification, I'll wait for the release to get cut and give it a shot.

**Comment by thibaultcha** [comment]
@mlehner616 Great, thank you!
