### PR TITLE
fix(tracing): sample rate not working

### LINKED ISSUE #10402: OpenTelemetry plugin does not send out any span while 'tracing_sampling_rate' is lower than 1.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.1.1

### Current Behavior

In my local development environment, I have a running container with image `jaegertracing/all-in-one:1.41` in order to verify OpenTelemetry plugins interacts with Jaeger.

With below environment configuration, everything works well:
```
KONG_OPENTELEMETRY_TRACING=all
KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE=1.0
```

After I change `KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE` to `0.9`, Kong does not send out any span to my Jaeger.  

### Expected Behavior

When I set `KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE` between 0 to 1, it should send out span regarding to the sampling rate.

### Steps To Reproduce

1. Set up a `jaegertracing/all-in-one:1.41` locally
```yaml
jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      SPAN_STORAGE_TYPE: "memory"
```
2. Setup Kong with 3.1.1 with following settings.
```
KONG_OPENTELEMETRY_TRACING=all
KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE=0.9
```
3. Enable `OpenTelemetry` Plugin
```yaml
plugins:
  - name: opentelemetry
    enabled: true
    config:
      endpoint: http://docker.for.mac.host.internal:4318/v1/traces
```

4. Verify by visiting any route, and browser `http://localhost:16686/` to see the OpenTelemetry spans, you will see nothing if `KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE` is 0.9, and after setting it to 1.0, it works and show spans.

### Anything else?
After a roughly tracing, the value of `sampled` is always false while set tracing sampling rate to 0.9
I guess this equation is incorrect and always fail since `tracer.sampler(trace_id)` is a `True` or `False` result, so it always not equals to `FLAG_SAMPLED_AND_RECORDING`
```
tracer.sampler(trace_id) == FLAG_SAMPLED_AND_RECORDING
```
Ref: https://github.com/Kong/kong/blob/3.1.1/kong/pdk/tracing.lua#L160

_No response_

### PR DESCRIPTION
**Pull request by StarlightIbuki**
### Full change log

- Fixed the original sampling algorithm implementation and added a test to examine the precision
- Removing `FLAG_SAMPLED_AND_RECORDING` flags as it seems we do not distinguish sample and recording yet, and it causes the result always be "not sampling".

### Checklist

- [x] The Pull Request has tests
- [x] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #10402
Fix KAG-910

### CODE REVIEW

**Comment by StarlightIbuki** [comment]
I strongly doubt it the algorithm of sampling is correct: Only the last bytes matter in most cases.
I need more knowledge to fix this:
1. Should we keep consistency with other tracers?
2. Should we keep consistency with the same trace ID?
3. Should we keep consistency with the same trace?

File: kong/pdk/tracing.lua [hunk 1]
```diff
@@ -37,15 +33,18 @@ local ngx_ERR = ngx.ERR
...
 local POOL_SPAN = "KONG_SPAN"
 local POOL_SPAN_STORAGE = "KONG_SPAN_STORAGE"
 local POOL_ATTRIBUTES = "KONG_SPAN_ATTRIBUTES"
 local POOL_EVENTS = "KONG_SPAN_EVENTS"
 
+-- must be power of 2
+local SAMPLING_BYTE = 8
+local SAMPLING_PRECISION = 8 * SAMPLING_BYTE
+local BOUND_MAX = math.pow(2, SAMPLING_PRECISION)
+local SAMPLEING_UINT_PTR_TYPE = "uint" .. SAMPLING_PRECISION .. "_t*"
```
Comment (bungle) [inline kong/pdk/tracing.lua:45]: Is this a typo?

```suggestion
local SAMPLING_UINT_PTR_TYPE = "uint" .. SAMPLING_PRECISION .. "_t*"
```

File: kong/pdk/tracing.lua [hunk 2]
```diff
@@ -67,34 +66,38 @@ end
...
+  -- TODO: is this a sound method to sample?
   return function(trace_id)
-    local n = ffi_cast("uint64_t*", ffi_str(trace_id, 8))[0]
-    n = rshift(n, 1)
-    return tonumber(n, 10) < upper_bound
+    if #trace_id < SAMPLING_BYTE then
+      error(TOO_SHORT_MESSAGE, 2)
+    end
+
+    local truncated = ffi_cast(SAMPLEING_UINT_PTR_TYPE, ffi_str(trace_id, SAMPLING_BYTE))[0]
```
Comment (bungle) [inline kong/pdk/tracing.lua:99]: If yes, then:
```suggestion
    local truncated = ffi_cast(SAMPLING_UINT_PTR_TYPE, ffi_str(trace_id, SAMPLING_BYTE))[0]
```

**Review by bungle — DISMISSED** [review]
Just checking

**Review by bungle — APPROVED** [review]

**Comment by sabertobihwy** [comment]
I have reviewed this code and it is consistent with the description provided by [probability-sampler-algorithm](https://github.com/c24t/opentelemetry-specification/blob/3b3d321865cf46364bdfb292c179b6444dc96bf9/specification/sdk-tracing.md#probability-sampler-algorithm). The logic is correct and I believe it will work well.

File: spec/01-unit/26-tracing/01-tracer_pdk_spec.lua
[the remark this answers is not in the document]
Comment (StarlightIbuki) [reply spec/01-unit/26-tracing/01-tracer_pdk_spec.lua:1]: Added.

**Review by sabertobihwy — APPROVED** [review]

File: spec/01-unit/26-tracing/01-tracer_pdk_spec.lua [hunk 3]
```diff
@@ -1,6 +1,18 @@
 require "spec.helpers" -- initializes 'kong' global for tracer
 local match = require("luassert.match")
 
+local utils = require "kong.tools.utils"
+local SAMPLING_BYTE = 8
+local rand_bytes = utils.get_rand_bytes
+local TEST_COUNT = 10000
+-- we can only ensure a sampling precision of 0.01
+local SAMPLING_PRECISION = 0.01
```
Comment (samugi) [inline spec/01-unit/26-tracing/01-tracer_pdk_spec.lua:9]: Running the test a few times I got some failures like:
`sampling rate is not correct: 0.4903 expected: 0.5007118` - we should probably adjust this precision

File: kong/pdk/tracing.lua [hunk 4]
```diff
@@ -37,15 +33,18 @@ local ngx_ERR = ngx.ERR
...
-local FLAG_SAMPLED_AND_RECORDING = bit.bor(FLAG_SAMPLED, FLAG_RECORDING)
-
 local POOL_SPAN = "KONG_SPAN"
 local POOL_SPAN_STORAGE = "KONG_SPAN_STORAGE"
 local POOL_ATTRIBUTES = "KONG_SPAN_ATTRIBUTES"
 local POOL_EVENTS = "KONG_SPAN_EVENTS"
 
+-- must be power of 2
+local SAMPLING_BYTE = 8
+local SAMPLING_PRECISION = 8 * SAMPLING_BYTE
```
Comment (samugi) [inline kong/pdk/tracing.lua:43]: since `SAMPLING_BYTE` is the number of byte**s** we consider from the trace id to apply the sampling algorithm on, should we rename to the plural `SAMPLING_BYTES`?

**Review by samugi — CHANGES_REQUESTED** [review]
Looks great to me. An adjustment is required in a test parameter otherwise I think it'll be flaky. Changelog conflicts should be resolved too.

File: spec/01-unit/26-tracing/01-tracer_pdk_spec.lua (hunk 3 above)
Comment (StarlightIbuki) [reply spec/01-unit/26-tracing/01-tracer_pdk_spec.lua]: Thanks for testing this. Changed to 0.02.

File: kong/pdk/tracing.lua (hunk 4 above)
Comment (StarlightIbuki) [reply kong/pdk/tracing.lua:43]: Guess "bits" is more precise.

Comment (samugi) [reply kong/pdk/tracing.lua]: oh yeah SAMPLING_BITS instead of SAMPLING PRECISION, but I was referring to what is now `SAMPLING_BYTE = 8` which refers to the number of bytes on this line: https://github.com/Kong/kong/pull/10485/files#diff-ee1d8aa5ddb77d9d9724f6bd21f6da4b6f4ed563a4cdaf0d53d5b7a40ca93652R99

**Review by samugi — APPROVED** [review]

**Comment by hbagdi** [comment]
Please cherry-pick this to EE.

**Comment by hbagdi** [comment]
ping @StarlightIbuki

**Comment by StarlightIbuki** [comment]
> ping @StarlightIbuki

PR created.
