### PR TITLE
fix(proxy) do not clear upgrade header with websockets, fix #4718

### LINKED ISSUE #4718: Websocket Upgrade header missing after upgrade to 1.2.0
### Summary

When publishing a an application that uses web sockets (via deepstream.io 3.2.4) after upgrading kong 1.1.2 to 1.20 the Upgrade response header is not passed to the client meaning a websocket connection fails to be established.

### Steps To Reproduce

1. Deploy websocket application (that uses websocket upgrade protocol)  through kong 1.1.2
2. Test that it works and if necessary capture http request logs using browser developer tools
3. Follow the standard kong upgrade process to 1.2.0 with identical service and route configuration
4. Test the same after the upgrade and note websockets will not be connected.

### Additional Details & Logs

- Kong version 1.2.0

Network logs

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Ensures that `Upgrade` header is not cleared with `websockets`.

### Issues resolved

Fix #4718

### CODE REVIEW

File: spec/02-integration/05-proxy/09-websockets_spec.lua [hunk 1]
```diff
@@ -38,6 +38,57 @@ for _, strategy in helpers.each_strategy() do
...
+      local key = encode_base64(bytes)
+      local req = "GET /up-ws HTTP/1.1\r\nUpgrade: websocket\r\nHost: "
+        .. host .. ":" .. port
+        .. "\r\nSec-WebSocket-Key: " .. key
+        .. "\r\nSec-WebSocket-Version: 13"
+        .. "\r\nConnection: Upgrade\r\n\r\n"
+
+      assert(sock:send(req))
+
+      local header_reader = sock:receiveuntil("\r\n\r\n")
```
Comment (thibaultcha) [inline spec/02-integration/05-proxy/09-websockets_spec.lua]: Can we close the socket once we are done here?

Comment (bungle) [reply spec/02-integration/05-proxy/09-websockets_spec.lua]: Sure. Thanks.
