### PR TITLE
fix(proxy) fix broken SNI based routing in L4 proxy mode, closes #5501

### LINKED ISSUE #5501: bug: sni routing does not seem to be working
### Summary

I'm trying to get Kong to route based on SNI but that doesn't seem to be working. I might be doing something wrong here as well.

### Steps To Reproduce

Start Kong

Populate Kong with the following config:

```
services:
- name: svc1
  protocol: tcp
  host: mockbin.org
  port: 80
  tags:
  - team-svc1
  routes:
  - name: r1
    protocols:
    - tls
    snis:
    - localhost
```

Do:
```
curl -k https://localhost:9001/
```

At this point Kong closes the connection because it can't find any route for the request. This is refelect in the error log as well.

Doing a tcpdump, curl does set the SNI field in the SSL handshake correctly so it seems Kong is not reading it.

Upon some initial conversatoin with @gszr (many thanks GS!), it seems like the nginx context isn't getting preserved from the certificate (where sni is resolved and stored in the context) to preread phase (when the router is executed and said value is used). He also might have a potential fix for the solution.

### Additional Details & Logs

- Kong version (`$ kong version`) 2.0.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

```
2020/01/24 19:46:21 [error] 26#0: *193551 stream [lua] handler.lua:967: before(): no Route found with those values while prereading client data, client: 172.17.0.1, server: 0.0.0.0:9001
172.17.0.1 [24/Jan/2020:19:46:21 +0000] TCP 500 0 0 0.011
```

- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)

```json
{
   "plugins":{
      "enabled_in_cluster":[

      ],
      "available_on_server":{
         "correlation-id":true,
         "pre-function":true,
         "cors":true,
         "ldap-auth":true,
         "loggly":true,
         "hmac-auth":true,
         "zipkin":true,
         "request-size-limiting":true,
         "azure-functions":true,
         "request-transformer":true,
         "oauth2":true,
         "response-transformer":true,
         "ip-restriction":true,
         "statsd":true,
         "jwt":true,
         "proxy-cache":true,
         "basic-auth":true,
         "key-auth":true,
         "http-log":true,
         "datadog":true,
         "tcp-log":true,
         "post-function":true,
         "prometheus":true,
         "acl":true,
         "syslog":true,
         "file-log":true,
         "session":true,
         "udp-log":true,
         "response-ratelimiting":true,
         "aws-lambda":true,
         "bot-detection":true,
         "rate-limiting":true,
         "request-termination":true
      }
   },
   "tagline":"Welcome to kong",
   "configuration":{
      "plugins":[
         "bundled"
      ],
      "admin_listen":[
         "0.0.0.0:8001",
         "0.0.0.0:8444 ssl"
      ],
      "proxy_access_log":"\/dev\/stdout",
      "prefix":"\/usr\/local\/kong",
      "nginx_conf":"\/usr\/local\/kong\/nginx.conf",
      "cassandra_username":"kong",
      "nginx_events_directives":[
         {
            "value":"auto",
            "name":"worker_connections"
         },
         {
            "value":"on",
            "name":"multi_accept"
         }
      ],
      "admin_ssl_cert_key":"\/usr\/local\/kong\/ssl\/admin-kong-default.key",
      "dns_resolver":{

      },
      "nginx_upstream_keepalive_requests":"100",
      "nginx_http_upstream_directives":[
         {
            "value":"100",
            "name":"keepalive_requests"
         },
         {
            "value":"60s",
            "name":"keepalive_timeout"
         },
         {
            "value":"60",
            "name":"keepalive"
         }
      ],
      "nginx_main_daemon":"off",
      "stream_proxy_ssl_enabled":true,
      "nginx_acc_logs":"\/usr\/local\/kong\/logs\/access.log",
      "pg_semaphore_timeout":60000,
      "proxy_listen":[
         "0.0.0.0:8000 reuseport backlog=16384",
         "0.0.0.0:8443 http2 ssl reuseport backlog=16384"
      ],
      "client_ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt",
      "go_pluginserver_exe":"\/usr\/local\/bin\/go-pluginserver",
      "dns_no_sync":false,
      "db_update_propagation":0,
      "stream_listen":[
         "0.0.0.0:9000",
         "0.0.0.0:9001 ssl"
      ],
      "nginx_err_logs":"\/usr\/local\/kong\/logs\/error.log",
      "cassandra_port":9042,
      "headers":[
         "server_tokens",
         "latency_tokens"
      ],
      "nginx_http_client_max_body_size":"0",
      "status_listen":[
         "off"
      ],
      "dns_stale_ttl":4,
      "cluster_control_plane":"127.0.0.1:8005",
      "nginx_http_ssl_prefer_server_ciphers":"off",
      "pg_database":"kong",
      "nginx_http_client_body_buffer_size":"8k",
      "admin_acc_logs":"\/usr\/local\/kong\/logs\/admin_access.log",
      "cassandra_refresh_frequency":60,
      "nginx_pid":"\/usr\/local\/kong\/pids\/nginx.pid",
      "nginx_main_worker_rlimit_nofile":"auto",
      "admin_access_log":"\/dev\/stdout",
      "proxy_listeners":[
         {
            "listener":"0.0.0.0:8000 reuseport backlog=16384",
            "proxy_protocol":false,
            "reuseport":true,
            "deferred":false,
            "ssl":false,
            "ip":"0.0.0.0",
            "backlog=16384":true,
            "http2":false,
            "port":8000,
            "bind":false
         },
         {
            "listener":"0.0.0.0:8443 ssl http2 reuseport backlog=16384",
            "proxy_protocol":false,
            "reuseport":true,
            "deferred":false,
            "ssl":true,
            "ip":"0.0.0.0",
            "backlog=16384":true,
            "http2":true,
            "port":8443,
            "bind":false
         }
      ],
      "db_cache_warmup_entities":[
         "services",
         "plugins"
      ],
      "enabled_headers":{
         "latency_tokens":true,
         "X-Kong-Response-Latency":true,
         "Server":true,
         "X-Kong-Admin-Latency":true,
         "X-Kong-Upstream-Status":false,
         "Via":true,
         "X-Kong-Proxy-Latency":true,
         "server_tokens":true,
         "X-Kong-Upstream-Latency":true
      },
      "nginx_http_ssl_protocols":"TLSv1.2 TLSv1.3",
      "db_cache_ttl":0,
      "nginx_events_multi_accept":"on",
      "admin_ssl_cert_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt",
      "pg_ssl":false,
      "status_access_log":"off",
      "cluster_listeners":[
         {
            "listener":"0.0.0.0:8005",
            "proxy_protocol":false,
            "reuseport":false,
            "backlog=%d+":false,
            "deferred":false,
            "ssl":false,
            "ip":"0.0.0.0",
            "port":8005,
            "http2":false,
            "bind":false
         }
      ],
      "kong_env":"\/usr\/local\/kong\/.kong_env",
      "cassandra_schema_consensus_timeout":10000,
      "log_level":"notice",
      "admin_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.key",
      "real_ip_recursive":"off",
      "cassandra_repl_factor":1,
      "ssl_cipher_suite":"intermediate",
      "router_consistency":"strict",
      "pg_port":5432,
      "cassandra_keyspace":"kong",
      "ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt",
      "nginx_http_ssl_session_timeout":"1d",
      "error_default_type":"text\/plain",
      "role":"traditional",
      "client_ssl":false,
      "trusted_ips":{

      },
      "nginx_events_worker_connections":"auto",
      "nginx_supstream_directives":{

      },
      "ssl_cert_key":"\/usr\/local\/kong\/ssl\/kong-default.key",
      "pg_user":"kong",
      "mem_cache_size":"128m",
      "ssl_ciphers":"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
      "nginx_admin_directives":{

      },
      "nginx_upstream_keepalive_timeout":"60s",
      "nginx_http_directives":[
         {
            "value":"0",
            "name":"client_max_body_size"
         },
         {
            "value":"off",
            "name":"ssl_prefer_server_ciphers"
         },
         {
            "value":"8k",
            "name":"client_body_buffer_size"
         },
         {
            "value":"TLSv1.2 TLSv1.3",
            "name":"ssl_protocols"
         },
         {
            "value":"on",
            "name":"ssl_session_tickets"
         },
         {
            "value":"1d",
            "name":"ssl_session_timeout"
         },
         {
            "value":"prometheus_metrics 5m",
            "name":"lua_shared_dict"
         }
      ],
      "pg_host":"kong-database",
      "nginx_kong_stream_conf":"\/usr\/local\/kong\/nginx-kong-stream.conf",
      "ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr",
      "go_plugins_dir":"off",
      "cluster_listen":[
         "0.0.0.0:8005"
      ],
      "dns_order":[
         "LAST",
         "SRV",
         "A",
         "CNAME"
      ],
      "dns_error_ttl":1,
      "nginx_optimizations":true,
      "nginx_http_upstream_keepalive_timeout":"60s",
      "pg_timeout":5000,
      "nginx_http_upstream_keepalive_requests":"100",
      "database":"postgres",
      "nginx_upstream_keepalive":"60",
      "nginx_worker_processes":"auto",
      "nginx_http_status_directives":{

      },
      "lua_package_path":".\/?.lua;.\/?\/init.lua;",
      "router_update_frequency":1,
      "upstream_keepalive":60,
      "pg_max_concurrent_queries":0,
      "proxy_ssl_enabled":true,
      "nginx_http_upstream_keepalive":"60",
      "lua_socket_pool_size":30,
      "db_resurrect_ttl":30,
      "nginx_proxy_real_ip_header":"X-Real-IP",
      "cassandra_consistency":"ONE",
      "client_max_body_size":"0",
      "admin_error_log":"\/dev\/stderr",
      "nginx_main_directives":[
         {
            "value":"off",
            "name":"daemon"
         },
         {
            "value":"auto",
            "name":"worker_rlimit_nofile"
         },
         {
            "value":"auto",
            "name":"worker_processes"
         }
      ],
      "dns_not_found_ttl":30,
      "nginx_http_ssl_session_tickets":"on",
      "loaded_plugins":{
         "correlation-id":true,
         "pre-function":true,
         "cors":true,
         "rate-limiting":true,
         "loggly":true,
         "hmac-auth":true,
         "zipkin":true,
         "bot-detection":true,
         "azure-functions":true,
         "request-transformer":true,
         "oauth2":true,
         "response-transformer":true,
         "syslog":true,
         "statsd":true,
         "jwt":true,
         "proxy-cache":true,
         "basic-auth":true,
         "key-auth":true,
         "http-log":true,
         "datadog":true,
         "tcp-log":true,
         "post-function":true,
         "ldap-auth":true,
         "acl":true,
         "ip-restriction":true,
         "file-log":true,
         "prometheus":true,
         "udp-log":true,
         "response-ratelimiting":true,
         "aws-lambda":true,
         "request-size-limiting":true,
         "session":true,
         "request-termination":true
      },
      "cassandra_ssl":false,
      "cassandra_repl_strategy":"SimpleStrategy",
      "status_error_log":"logs\/status_error.log",
      "db_update_frequency":5,
      "nginx_status_directives":{

      },
      "nginx_main_worker_processes":"auto",
      "nginx_kong_conf":"\/usr\/local\/kong\/nginx-kong.conf",
      "real_ip_header":"X-Real-IP",
      "dns_hostsfile":"\/etc\/hosts",
      "admin_listeners":[
         {
            "listener":"0.0.0.0:8001",
            "proxy_protocol":false,
            "reuseport":false,
            "backlog=%d+":false,
            "deferred":false,
            "ssl":false,
            "ip":"0.0.0.0",
            "port":8001,
            "http2":false,
            "bind":false
         },
         {
            "listener":"0.0.0.0:8444 ssl",
            "proxy_protocol":false,
            "reuseport":false,
            "backlog=%d+":false,
            "deferred":false,
            "ssl":true,
            "ip":"0.0.0.0",
            "port":8444,
            "http2":false,
            "bind":false
         }
      ],
      "nginx_stream_directives":[
         {
            "value":"stream_prometheus_metrics 5m",
            "name":"lua_shared_dict"
         }
      ],
      "ssl_cert":"\/usr\/local\/kong\/ssl\/kong-default.crt",
      "nginx_proxy_real_ip_recursive":"off",
      "admin_ssl_enabled":true,
      "cassandra_ssl_verify":false,
      "admin_ssl_cert":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt",
      "proxy_error_log":"\/dev\/stderr",
      "nginx_sproxy_directives":{

      },
      "cassandra_timeout":5000,
      "client_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key",
      "nginx_daemon":"off",
      "anonymous_reports":true,
      "pg_ssl_verify":false,
      "status_listeners":{

      },
      "ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key",
      "cassandra_contact_points":[
         "kong-database"
      ],
      "client_body_buffer_size":"8k",
      "stream_listeners":[
         {
            "bind":false,
            "port":9000,
            "listener":"0.0.0.0:9000",
            "ip":"0.0.0.0",
            "proxy_protocol":false,
            "ssl":false,
            "reuseport":false,
            "backlog=%d+":false
         },
         {
            "bind":false,
            "port":9001,
            "listener":"0.0.0.0:9001 ssl",
            "ip":"0.0.0.0",
            "proxy_protocol":false,
            "ssl":true,
            "reuseport":false,
            "backlog=%d+":false
         }
      ],
      "cassandra_lb_policy":"RequestRoundRobin",
      "lua_package_cpath":"",
      "cassandra_data_centers":[
         "dc1:2",
         "dc2:3"
      ],
      "nginx_proxy_directives":[
         {
            "value":"X-Real-IP",
            "name":"real_ip_header"
         },
         {
            "value":"off",
            "name":"real_ip_recursive"
         }
      ],
      "lua_ssl_verify_depth":1,
      "nginx_upstream_directives":[
         {
            "value":"100",
            "name":"keepalive_requests"
         },
         {
            "value":"60s",
            "name":"keepalive_timeout"
         },
         {
            "value":"60",
            "name":"keepalive"
         }
      ]
   },
   "version":"2.0.0",
   "node_id":"91a7983e-eaa4-4ed8-b0bd-fefed4df3b28",
   "lua_version":"LuaJIT 2.1.0-beta3",
   "prng_seeds":{
      "pid: 28":592146248190,
      "pid: 31":184113251642,
      "pid: 27":107691131571,
      "pid: 1":607617298203,
      "pid: 30":791510924431,
      "pid: 26":228215232621,
      "pid: 29":131199226714,
      "pid: 33":132190189297,
      "pid: 32":168371332083
   },
   "timers":{
      "pending":8,
      "running":0
   },
   "hostname":"f91260e15ec2"
}
```
- Operating system: Docker alpine image

### PR DESCRIPTION
**Pull request by dndx**
The `stream_lua` per-connection doesn't exist yet during
`ssl_certificate_by_lua` phase. As a result saving the SNI into the
`ngx.ctx` object wouldn't preserve into later phases, causing SNI
routing failure.

This PR uses the `ngx.ssl.server_name` method to obtain the SNI
`server_name` instead which is guaranteed to work in the later phases.

Thanks @hbagdi for the report!

### CODE REVIEW

File: kong/router.lua [hunk 1]
```diff
@@ -1739,12 +1739,15 @@ function _M.new(routes)
...
+    local server_name = require("ngx.ssl").server_name
+
+    function self.exec()
       local src_ip = var.remote_addr
       local src_port = tonumber(var.remote_port, 10)
       local dst_ip = var.server_addr
       local dst_port = tonumber(var.server_port, 10)
-      local sni = ctx.sni_server_name
+      -- error value for non-TLS connections ignored intentionally
+      local sni, _ = server_name()
```
Comment (gszr) [inline kong/router.lua]: @dndx for my own knowledge, is this at all different from var.ssl_server_name?

Comment (dndx) [reply kong/router.lua]: This is faster, because the preread module doesn't have to run.

Comment (gszr) [reply kong/router.lua]: It of course not a blocker, but in this case could we update the HTTP subsystem branch to use the faster alternative?

**Comment by gszr** [comment]
This should go into `master` instead. Could you rebase @dndx?

**Comment by dndx** [comment]
Thanks @gszr, rebased and merged!
