### PR TITLE
fix(schema) make process auto fields to remove empty strings on select

### LINKED ISSUE #5653: Treat key-auth's config.anonymous "" as null
### Summary

In the past key-auth's `config.anonymous` was set to `""` (empty string) in the database. Starting Kong 2.0 that causes `failed to load anonymous consumer` error.

### Steps To Reproduce

We upgraded from Kong 1.4 to 2.0.2. (And previously 0.9 to 1.1, then 1.1 to 1.4). Very early we added key-auth plugin like this
```
curl -s -X POST \
  --url http://localhost:8001/services/ourservice/plugins/ \
  --data 'name=key-auth'
```
without any other config values set.

In Kong 1.4 and 2.0 in the database that get stored as
```
select * from plugins where name='key-auth' and consumer_id is null;

id          | edca177b-77b6-457c-9019-9105badbeea1
name        | key-auth
api_id      |
consumer_id |
config      | {"anonymous": "", "key_names": ["apikey"],
"hide_credentials": false, "run_on_preflight": true}
```

Based on the documentation https://docs.konghq.com/hub/kong-inc/key-auth/ I wouldn've expected the database to show `"anonymous: null"` or the key not existent. https://github.com/Kong/kong/commit/91a5738dcf5 looks like the change from boolean to string type.

No problem in Kong 1.4. A URL request without any authentication key (key name `apikey` by default) set, e.g. `curl http://localhost:8000/ourservice/` returns `HTTP/1.1 401 Unauthorized` and body `{"message":"No API key found in request"}`.

Starting Kong 2.0 the same request returns `HTTP/1.1 500 Internal Server Error` with body `{"message":"An unexpected error occurred"}`. The kong logfile contains `*2400 [kong] handler.lua:193 [key-auth] failed to load anonymous consumer:failed to get from node cache: [postgres] length must be at least 1, client: 127.0.0.1, server: kong, request: "GET /ourservice HTTP/1.1", host: "localhost:8000"`

It is no longer clear what set `anonymous": ""` in the database in the past, but it seems it was the default setting. Upgrading to Kong 2.0 broke the default behaviour.

Comment https://github.com/Kong/kong/issues/3222#issuecomment-365750935 from Kong 0.12.1 shows an example how the value was set to empty string in the past.

https://github.com/Kong/kong/issues/2539 shows how Kong 0.10. set the default to empty string and how previous logic looked at both empty string and null/nil.
```
.//kong/plugins/key-auth/handler.lua:    if conf.anonymous ~= "" and conf.anonymous ~= nil then
```
### Expected behaviour

Either

* Add a note about a breaking change to the https://github.com/Kong/kong/blob/master/UPGRADE.md documentation
* Have a migration convert the value during an upgrade (`""` to `null`)
* Treat empty string the same as null

I'd prefer the latter, but the Kong maintaners are more expert at backward compatibility, the DAO (which keeps changing) and side-effects with other auth plugins. I argue a Kong administrator setting the value to empty string made clear it's neither meant to be a UUID or username.

### Workaround

We changed the value in the database with a SQL statement. It was unclear how to unset a value. Setting it to `null` via the Admin API returned `{"message":"invalid primary key: '{id=\"expected a valid UUID\"}'","name":"invalid primary key","fields":{"id":"expected a valid UUID"},"code":1`

### Additional Details & Logs

- Kong version (`2.0.2`)
- Ubuntu 16

### PR DESCRIPTION
**Pull request by bungle**
### Summary

On PR #5879 @murillopaula proposed a fix to a common but arbitrary plugin field called `config.anonymous`. The PR tried to tackle two things at the same time. It tried to infer `JSON` input (which we don't do), and it tried to fix issue where upgraded databases still contained empty strings `""` stored to `config.anonymous` (instead of `null`). This only fixes the issue for this field. It also added `legacy` flag to that field, which in my opinion the field is not, or that it is not any special to any other field that could contain empty string `""`. So I didn't think it was a good idea to start flagging fields to `legacy` one by one.

Thus I discussed this with @murillopaula and out of those discussions came one winner that we both agreed upon. The solution is to run automatic transformation on `select` to database fields that are not legacy, and convert the value to `nil` (remove field) or `null` (when nulls were requested). This is implemented directly in `process_auto_fields` which we call automatically on daos. The solution looks like this:

```lua
if context == "select"
   and not field.legacy
   and field.type == "string"
   and (field.len_min or 1) > 0
   and data[key] == ""
then
  data[key] = nulls and null or nil
end
```

This fixes the issue for all the fields that are updated to new schema which if not `len_min=0` will not accept `""` as input, and thus are auto-translated to `nil`/`null` on read if they exists as `""` in db.

### Issues resolved

Fix #5653 (the database `""`)
Close #5879 (previous attempt)

### CODE REVIEW

File: spec/01-unit/01-db/01-schema/01-schema_spec.lua [hunk 1]
```diff
@@ -2692,6 +2692,54 @@ describe("schema", function()
...
+        b = {
+          c = "",
+        },
+        d = { "", "", "" },
+        e = "",
+      }, "select", true)
+      assert.is_nil(err)
+      assert.equal(cjson.null, data.a)
+      assert.equal(cjson.null, data.b.c)
+      assert.same({"", "", ""}, data.d) -- TODO: should we remove also empty values from arrays?
```
Comment (murillopaula) [inline spec/01-unit/01-db/01-schema/01-schema_spec.lua:2739]: Good question. To reiterate, in order to fix https://github.com/Kong/kong/issues/5653 we just need to remove empty strings. But what about official or third party plugins that have an array of empty strings in the database? Or any other type that accepts elements of strings, for example, a map or a set? See all the types at https://github.com/Kong/kong/blob/master/kong/db/schema/init.lua#L52-L60

File: kong/db/schema/init.lua [hunk 2]
```diff
@@ -1614,8 +1614,18 @@ function Schema:process_auto_fields(data, context, nulls)
     end
 
     for key in pairs(data) do
-      -- set non defined fields to nil, except meta fields (ttl) if enabled
-      if not self.fields[key] then
+      local field = self.fields[key]
+      if field then
+        if not field.legacy
```
Comment (murillopaula) [inline kong/db/schema/init.lua:1619]: Legacy fields are UUID fields, right? Why are legacy fields `null` by default and not `nil`? See https://github.com/Kong/kong/blob/master/kong/db/schema/init.lua#L1561-L1563

File: spec/01-unit/01-db/01-schema/01-schema_spec.lua (hunk 1 above)
Comment (murillopaula) [reply spec/01-unit/01-db/01-schema/01-schema_spec.lua:2739]: I think we should do the same treatment for anything that accepts strings as element, no? We don't allow empty strings elements inside arrays. So If we also have it set to "" in empty in the DB, shouldn't we also translate it to `nil`?

Comment (bungle) [reply spec/01-unit/01-db/01-schema/01-schema_spec.lua:2739]: For maps that have `string` values (or records as values that have `strings`) I think, absolutely, that would be a good idea. Arrays/sets I am not sure what the current state is. When removing empty string from arrays/set we need to to use `table.remove` to prevent holes.

I added a couple of tests there, so if we modify the behavior those tests should fail. I think it might be a good idea to do the same treatment. @hishamhm do you have anything against it? Is it part of this PR or should it be another PR?
