### PR TITLE
fix(plugins/grpc-gateway):handle json decode error safely(#10028)

### LINKED ISSUE #10028: Incorrect status code 500 for invalid JSON data processed by grpc-gateway plugin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8.1

### Current Behavior

When I send an invalid JSON request, or a valid JSON with incorrect data type for a certain field, the response is received as a stream with 500 internal server error. 

### Expected Behavior

When I send an invalid JSON request, or a valid JSON with incorrect data type for a certain field, the response should be 400 with proper JSON response.

### Steps To Reproduce

```markdown
1. Add kong grpc-gateway plugin in declarative yml, and add proto path to config.
2. Start Kong server
3. Send HTTP request with Invalid JSON, or incorrect datatype in JSON.
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by beardnick**
### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [x] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #10028

### CODE REVIEW

File: kong/plugins/grpc-gateway/deco.lua [hunk 1]
```diff
@@ -227,7 +227,10 @@ function deco:upstream(body)
   local body_variable = self.endpoint.body_variable
   if body_variable then
     if body and #body > 0 then
-      local body_decoded = decode_json(body)
+      local body_decoded, err = decode_json(body)
+      if err then
+        return nil, err
```
Comment (oowl) [inline kong/plugins/grpc-gateway/deco.lua:232]:
```suggestion
        return nil, "decode json err: " .. err
```

Comment (beardnick) [reply kong/plugins/grpc-gateway/deco.lua]: Thank you for your review. I will take this suggest.

File: kong/plugins/grpc-gateway/handler.lua [hunk 2]
```diff
@@ -120,7 +120,7 @@ function grpc_gateway:body_filter(conf)
   if not ret or #ret == 0 then
     if ngx_arg[2] then
       -- it's eof and we still cannot decode, fall through
-      ret = deco:get_raw_downstream_body()
```
Comment (beardnick) [inline kong/plugins/grpc-gateway/handler.lua:123]: It's the decoder instance dec should be used there because it's dec who carry the downstream_body.
Using deco will make get_raw_downstream_body return nil, hence the response body will be nil.

**Comment by beardnick** [comment]
updated. PTAL @oowl

**Review by oowl — APPROVED** [review]

File: changelog/unreleased/kong/fix-grpc-gateway-json-decode-bug.yml [hunk 3]
```diff
@@ -0,0 +1,3 @@
+message: "**grpc-gateway**:Fixed an json decode issue so that kong will response 400 with error info in it's body instead of 500."
```
Comment (hanshuebner) [inline changelog/unreleased/kong/fix-grpc-gateway-json-decode-bug.yml:1]:
```suggestion
message: "**grpc-gateway**: When there is a JSON decoding error, respond with status 400 and error information in the body instead of status 500."
```

**Review by hanshuebner — CHANGES_REQUESTED** [review]

File: changelog/unreleased/kong/fix-grpc-gateway-json-decode-bug.yml (hunk 3 above)
Comment (beardnick) [reply changelog/unreleased/kong/fix-grpc-gateway-json-decode-bug.yml]: Sorry for my poor English.😂

**Review by hanshuebner — APPROVED** [review]

**Comment by hanshuebner** [comment]
Merged, thank you for your contribution!

**Comment by beardnick** [comment]
> Merged, thank you for your contribution!

Thank you for your help and patience again.

**Comment by kikito** [comment]
@beardnick Notice that this fix will land in 3.8, as it was merged after 3.7 Feature Freeze and we don't have bandwidth to backport it in time.
