### PR TITLE
fix(plugins/acme): fix certificate renew failure issue

### LINKED ISSUE #12442: Bug when triggering renewal of cert in acme plugin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5.0

### Current Behavior

I try to trigger a renewal of certificates and there seems to be some issue in the acme client.

This is the request I do towards the admin-api:
```console
curl http://XX.XXX.XXX.XXX:8001/acme -XPATCH
```

The response from my request is this:
```json
{"message":"Renewal process started successfully"}
```

This is the error message from Kong:
```plain
Jan 28 18:09:58 fra1-kong-001 docker[138569]: kong-api              | 2024/01/28 18:09:58 [error] 1280#0: *200803 [lua] job.lua:284: execute(): [timer-ng] failed to run timer unix_timestamp=1706465398520.000000;counter=13563:meta=debug off: /usr/local/share/lua/5.1/kong/plugins/acme/client.lua:512: attempt to index local 'config' (a boolean value), context: ngx.timer
Jan 28 18:09:58 fra1-kong-001 docker[138569]: kong-api              | XX.XXX.XXX.XXX - - [28/Jan/2024:18:09:58 +0000] "PATCH /acme HTTP/1.1" 202 50 "-" "curl/8.4.0"
```

### Expected Behavior

I except the existing certificates to be renewed and not get stuck with the "old" ones.

### Steps To Reproduce

1. Trigger a renew of certificate:
   ```console
   curl http://XX.XXX.XXX.XXX:8001/acme -XPATCH
   ```

### Anything else?

I use DecK for configuring Kong, but I've done that since months and without any problem.

If I recall correct I did not have the renewal issue when I run an older version of Kong (not 3.5.0), but I don't remember the version back then.

### PR DESCRIPTION
**Pull request by Water-Melon**
### Summary

Fix ACME renewal bug.

Using `client.renew_certificate` directly as the callback function in `ngx_timer_at` causes the parameter value to not be the plugin's config.

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

KAG-4008
Fix #12442

### CODE REVIEW

File: kong/plugins/acme/api.lua [hunk 1]
```diff
@@ -125,7 +125,7 @@ return {
     end,
 
     PATCH = function()
-      ngx_timer_at(0, client.renew_certificate)
+      ngx_timer_at(0, handler.renew)
```
Comment (bungle) [inline kong/plugins/acme/api.lua:128]: Do we need to start timer here? What if we started it here:
https://github.com/Kong/kong/blob/master/kong/plugins/acme/handler.lua#L95

Comment (bungle) [reply kong/plugins/acme/api.lua:128]: Ok, figured it out, the sole purpose of PATCH is to renew (on control plane, which feels strange).

**Review by bungle — APPROVED** [review]

File: changelog/unreleased/kong/fix-acme-renewal-bug.yml [hunk 2]
```diff
@@ -0,0 +1,3 @@
+message: Fix ACME renewal bug. Using `client.renew_certificate` directly as the callback function in `ngx_timer_at` causes the parameter value to not be the plugin's config.
```
Comment (chronolaw) [inline changelog/unreleased/kong/fix-acme-renewal-bug.yml:1]: Should be:
```
"**ACME**: fix an issue where ..."
```

Comment (Water-Melon) [reply changelog/unreleased/kong/fix-acme-renewal-bug.yml]: fixed

**Review by fffonion — APPROVED** [review]

File: changelog/unreleased/kong/fix-acme-renewal-bug.yml [hunk 3]
```diff
@@ -0,0 +1,3 @@
+message: "**ACME**: fix an issue where using client.renew_certificate directly as the callback function in ngx_timer_at causes the parameter value to not be the plugin's config."
```
Comment (chronolaw) [inline changelog/unreleased/kong/fix-acme-renewal-bug.yml:1]: The message is too technical, could we change it more understandable?

Comment (ADD-SP) [reply changelog/unreleased/kong/fix-acme-renewal-bug.yml:1]: Agreed, we can write technical into the commit message, but the changelog is not a good place for that.

Comment (ADD-SP) [reply changelog/unreleased/kong/fix-acme-renewal-bug.yml:1]: Agreed, we can write technical words into the commit message, but the changelog is not a good place for that.

**Review by ADD-SP — CHANGES_REQUESTED** [review]
Please refine the changelog as customers might unable to understand it.

File: changelog/unreleased/kong/fix-acme-renewal-bug.yml (hunk 3 above)
Comment (Water-Melon) [reply changelog/unreleased/kong/fix-acme-renewal-bug.yml]: How about this one?

> "**ACME**: fix an issue where the certificate was not successfully renewed during ACME renewal."

It's already updated in changelog.

File: changelog/unreleased/kong/fix-acme-renewal-bug.yml [hunk 4]
```diff
@@ -0,0 +1,3 @@
+message: "**ACME**: fix an issue where the certificate was not successfully renewed during ACME renewal."
```
Comment (ADD-SP) [inline changelog/unreleased/kong/fix-acme-renewal-bug.yml:1]:
``` suggestion
message: "**ACME**: Fixed an issue where the certificate was not successfully renewed during ACME renewal."
```

**Review by ADD-SP — CHANGES_REQUESTED** [review]

File: changelog/unreleased/kong/fix-acme-renewal-bug.yml (hunk 4 above)
Comment (Water-Melon) [reply changelog/unreleased/kong/fix-acme-renewal-bug.yml]: Done

**Review by ADD-SP — COMMENTED** [review]
One more question: there are two backport labels, did we decided to backport this fix?

**Comment by chronolaw** [comment]
Do we have test case to verify this issue is fixed?

**Comment by Water-Melon** [comment]
> Do we have test case to verify this issue is fixed?

It has already been verified using my personal domain name + EC2 instance.

**Review by ADD-SP — CHANGES_REQUESTED** [review]
In general, we should add tests for bugfix before merging.

**Comment by Water-Melon** [comment]
The test for this ticket requires binding a public IP address to a domain name, and then configuring it according to the instructions in https://docs.konghq.com/hub/kong-inc/acme/how-to/ . Afterward, send a PATCH request (also in this document), and we will see this error log in Kong's logs:
```
... attempt to index local 'config' (a boolean value), context: ngx.timer
```

After fixing it, if we execute it again, there will be no error log output, and the API will still return `{"message":"Renewal process started successfully"}`.

**Review by chronolaw — APPROVED** [review]
It seems that it is hard to write a test case for this PR, so I approve it.

**Comment by ADD-SP** [comment]
Missing tests, coverted to a draft.

**Review by ADD-SP — APPROVED** [review]
