### PR TITLE
fix(ldap): add missing www-authenticate headers

### LINKED ISSUE #7772: WWW-Authenticate header not present when Kong and plugins return HTTP status 401
### Summary
- Kong version (`$ kong version`) - 2.4.1
According to the HTTP specification for 401 error, https://httpwg.org/specs/rfc7235.html#status.401, WWW-Authenticate header field containing at least one challenge applicable to the target resource must be returned in the response.

At least the following plugins were observed to not returning the header when returning 401.
1) basic-auth
2) key-auth
3) ldap-auth
4) jwt

For Oauth2 related plugins **oauth2** and **jwt**, below are additional requirements from the related RFCs. They further define what needs to be included in the WWW-Authenticate header.

1) https://datatracker.ietf.org/doc/html/rfc6750#section-3
2) https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

### Steps To Reproduce
Exercise any unit tests of those plugins that would return 401 error and add an assertion in those test to detect the header, the assertion would fail.

For example in jwt pluging 03_acces_spec.lua, add the **LAST** assertion and execute the test, it will fail.

    describe("refusals", function()
      it("returns 401 Unauthorized if no JWT is found in the request", function()
        local res = assert(proxy_client:send {
          method  = "GET",
          path    = "/request",
          headers = {
            ["Host"] = "jwt1.com",
          }
        })
        assert.res_status(401, res)
        assert.not_nil(body.headers["WWW-Authenticate"])
      end)

### PR DESCRIPTION
**Pull request by nowNick**
### Summary

When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. Ldap auth was missing this header on some responses.

### Related PRs:
- https://github.com/Kong/kong/pull/11791
- https://github.com/Kong/kong/pull/11792
- https://github.com/Kong/kong/pull/11794
- https://github.com/Kong/kong/pull/11795
- https://github.com/Kong/kong/pull/11833

### RFCs & Materials

- https://httpwg.org/specs/rfc7235.html#status.401
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [x] N/A ~~There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~~

### Full changelog

- add `WWW-Authenticate` header to all ldap 401 response

### Issue reference

- Fix #7772
- KAG-321

### CODE REVIEW

File: kong/plugins/ldap-auth/access.lua [hunk 1]
```diff
@@ -232,25 +232,29 @@ local function set_consumer(consumer, credential)
...
-      -- TODO: provide migration to capitalize older configurations
-      scheme = upper(scheme)
-    end
-
-    return false, {
-      status = 401,
-      message = "Unauthorized",
-      headers = { ["WWW-Authenticate"] = scheme .. ' realm="kong"' }
-    }
+    return false, unauthorized("Unauthorized", www_auth_content)
```
Comment (hanshuebner) [inline kong/plugins/ldap-auth/access.lua:257]: Like in the other PR: Is there a need to change the default for the realm from "kong"?

**Review by hanshuebner — CHANGES_REQUESTED** [review]

File: kong/plugins/ldap-auth/access.lua (hunk 1 above)
Comment (nowNick) [reply kong/plugins/ldap-auth/access.lua:257]: (same answer as in the other pr 😉 )

**Review by hanshuebner — APPROVED** [review]

**Review by jschmid1 — APPROVED** [review]
