### PR TITLE
fix(tracing): span start/end time precision

### LINKED ISSUE #11294: Broken trace trees with tracing_instrumentations=request
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

With `tracing_instrumentations=request`, Kong will only report the request span via the OpenTelemetry plugin. The problem hereby is that it will also inject an invalid parent span ID (maybe the one of the balancer span?) into the balancer request, leading to broken trace graphs like this:

Screenshot 2023-07-26 at 10 43 57

With `tracing_instrumentations=all`, the span tree is not broken:

Screenshot 2023-07-26 at 11 02 58

### Expected Behavior

With `tracing_instrumentations=request` (and any other limited set), Kong should inject the span ID of the request span as parent span ID into the balancer request so that the trace tree is not broken.

### Steps To Reproduce

1. Set up OpenTelemetry plugin with Jaeger export (other collectors should show same problem)
2. Send request to an instrumented service
3. Check trace in Jaeger

### Anything else?

If I'm not mistaken, this was working correctly on earlier versions of Kong 3.x and broke with the update to 3.3

### PR DESCRIPTION
**Pull request by samugi**
### Summary

Ensure the span lifetime is consistent with the spans hierarchy by using the same time precision for the root span's "end time" as the balancer span.

Before this fix, using millisecond precision instead of nano could result in the root span to end before its children.

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/CHANGELOG/README.md) (Please ping @vm-001 if you need help)
- [x] (no) ~There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~

### Full changelog

* increased precision of the request (kong) span to nanoseconds

### Issue reference

KAG-2336
Fix #11294 (secondary issue reported in the comments)

### CODE REVIEW

File: spec/02-integration/14-tracing/03-tracer-pdk_spec.lua [hunk 1]
```diff
@@ -77,5 +85,39 @@ for _, strategy in helpers.each_strategy() do
...
+      lazy_setup(function()
+        setup_instrumentations("all", false, 1)
+      end)
+
+      lazy_teardown(function()
+        helpers.stop_kong()
+      end)
+
+      it("sets child lifespan within parent's lifespan", function ()
+        for _ = 1, 100 do
```
Comment (StarlightIbuki) [inline spec/02-integration/14-tracing/03-tracer-pdk_spec.lua:99]: How long does this test take... How about we do it with a mocked unit test?

File: CHANGELOG/unreleased/kong/11484.yaml [hunk 2]
```diff
@@ -0,0 +1,7 @@
+message: "Tracing: fix an issue that resulted in some parent spans to end before their children due to lack of precision"
```
Comment (StarlightIbuki) [inline CHANGELOG/unreleased/kong/11484.yaml:1]: Could you explain in what condition the low precision leads to a child's span with an earlier ending time?

**Comment by StarlightIbuki** [comment]
Rerunning all the tests as it seems the artificials are broken.

File: spec/02-integration/14-tracing/03-tracer-pdk_spec.lua (hunk 1 above)
Comment (samugi) [reply spec/02-integration/14-tracing/03-tracer-pdk_spec.lua:99]: this test takes 0.7 seconds to execute in my local machine, let's see how long it takes on CI once the build succeeds, but I don't think it will exceed 1 second

File: CHANGELOG/unreleased/kong/11484.yaml (hunk 2 above)
Comment (samugi) [reply CHANGELOG/unreleased/kong/11484.yaml:1]: An example is visible in the screenshots of https://github.com/Kong/kong/issues/11294, in general, since the balancer's span end time is recorded with nanosecond precision (e.g. 1,693,916,282,000,123,456) and the request (root / kong) span's end time **was** recorded with millisecond precision (e.g. 1,693,916,282,000) we could expect to see the request's end up to 999,999ns (0.999999 ms) earlier than the balancer.

File: spec/02-integration/14-tracing/03-tracer-pdk_spec.lua (hunk 1 above)
Comment (StarlightIbuki) [reply spec/02-integration/14-tracing/03-tracer-pdk_spec.lua:99]: Then I think it's fine.

File: CHANGELOG/unreleased/kong/11484.yaml (hunk 2 above)
Comment (StarlightIbuki) [reply CHANGELOG/unreleased/kong/11484.yaml:1]: Got it. So maybe we should name the problem like "mixing of different precisions"?

Comment (samugi) [reply CHANGELOG/unreleased/kong/11484.yaml]: @StarlightIbuki I rephrased the changelog message to make it more clear, thanks

File: CHANGELOG/unreleased/kong/11484.yaml [hunk 3]
```diff
@@ -0,0 +1,7 @@
+message: "Tracing: fix an issue that resulted in some parent spans to end before their children due to different precision of their timestamps"
+type: bugfix
+scope: PDK
+prs:
+  - 11484
+jiras:
+  - "KAG-2336"
```
Comment (StarlightIbuki) [inline CHANGELOG/unreleased/kong/11484.yaml:7]: It's ok to go without this change.

```suggestion
  - "KAG-2336"
issues:
  - 11294
```

File: kong/init.lua [hunk 4]
```diff
@@ -1504,6 +1504,7 @@ function Kong.log()
   local ctx = ngx.ctx
   if not ctx.KONG_LOG_START then
     ctx.KONG_LOG_START = now() * 1000
+    ctx.KONG_LOG_START_NS = time_ns()
```
Comment (StarlightIbuki) [inline kong/init.lua:1507]: What about we get the time in ns precision and then round it to 1us?
Also, is there some consideration that we making the `KONG_LOG_START` field with ns precision?

**Review by StarlightIbuki — APPROVED** [review]
I'm okay with this being merged.

File: kong/init.lua (hunk 4 above)
Comment (samugi) [reply kong/init.lua:1507]: > round it to 1us

Would it provide any advantage to do that? Some of the tracing backends do support nanosecond as the smallest precision, others seem to do the rounding up automatically, so I believe we can just keep that level of precision where we can afford it.

The reason I preferred to keep LOG_START and LOG_START_NS separate, rather than setting the value in nanosecond and then converting to ms is that we would end up comparing times that come from different sources when, for example, we use the value `KONG_LOG_START` to compute latencies.

Keeping this value isolated to tracing seemed a better alternative to reduce the impact of the change.

**Comment by kikito** [comment]
@samugi is there a reason for not backporting this further (e.g 3.3)
