### PR TITLE
fix(basic-auth): add missing www-authenticate headers

### LINKED ISSUE #7772: WWW-Authenticate header not present when Kong and plugins return HTTP status 401
### Summary
- Kong version (`$ kong version`) - 2.4.1
According to the HTTP specification for 401 error, https://httpwg.org/specs/rfc7235.html#status.401, WWW-Authenticate header field containing at least one challenge applicable to the target resource must be returned in the response.

At least the following plugins were observed to not returning the header when returning 401.
1) basic-auth
2) key-auth
3) ldap-auth
4) jwt

For Oauth2 related plugins **oauth2** and **jwt**, below are additional requirements from the related RFCs. They further define what needs to be included in the WWW-Authenticate header.

1) https://datatracker.ietf.org/doc/html/rfc6750#section-3
2) https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

### Steps To Reproduce
Exercise any unit tests of those plugins that would return 401 error and add an assertion in those test to detect the header, the assertion would fail.

For example in jwt pluging 03_acces_spec.lua, add the **LAST** assertion and execute the test, it will fail.

    describe("refusals", function()
      it("returns 401 Unauthorized if no JWT is found in the request", function()
        local res = assert(proxy_client:send {
          method  = "GET",
          path    = "/request",
          headers = {
            ["Host"] = "jwt1.com",
          }
        })
        assert.res_status(401, res)
        assert.not_nil(body.headers["WWW-Authenticate"])
      end)

### PR DESCRIPTION
**Pull request by nowNick**
### Summary

When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. Basic auth was missing this header on some responses. Previously it only returned this header when `Authorization` or `Proxy-Authorization` was missing but the RFC states that it should return it for every 401 response. This PR also adds a possibility to configure a parameter - realm (defaults to `service`).

### Related PRs:
- https://github.com/Kong/kong/pull/11791
- https://github.com/Kong/kong/pull/11792
- https://github.com/Kong/kong/pull/11794
- https://github.com/Kong/kong/pull/11820
- https://github.com/Kong/kong/pull/11833

### RFCs & Materials

- https://httpwg.org/specs/rfc7235.html#status.401
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [x] N/A ~~There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~~

### Full changelog

- add `WWW-Authenticate` header to all basic-auth 401 response

### Issue reference

- Fix #7772
- KAG-321

### CODE REVIEW

File: kong/plugins/basic-auth/access.lua [hunk 1]
```diff
@@ -155,7 +155,13 @@ end
 
 
 local function fail_authentication()
-  return false, { status = 401, message = "Invalid authentication credentials" }
+  return false, {
+      status = 401,
+      message = "Invalid authentication credentials",
+      headers = {
+        ["WWW-Authenticate"] = realm
```
Comment (nowNick) [inline kong/plugins/basic-auth/access.lua:162]: We cannot remove `realm=""` part from the header as for the Basic auth it is required according to: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#basic

**Review by hanshuebner — APPROVED** [review]

File: spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua [hunk 2]
```diff
@@ -375,6 +375,7 @@ describe("declarative config: process_auto_fields", function()
                     protocols = { "grpc", "grpcs", "http", "https" },
                     config = {
                       hide_credentials = false,
+                      realm = "service",
```
Comment (kikito) [inline spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua:378]: Probably not needed, as this is the default in the schema

**Review by kikito — APPROVED** [review]
Approved with a small comment

File: spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua (hunk 2 above)
Comment (nowNick) [reply spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua:378]: Unfortunately without this the test fails and I guess it's ok since as far as I understand it this test in [line#306](https://github.com/Kong/kong/pull/11795/files#diff-d67bdb1532159f004104b149195dba283e15ebdb56b539a18b76472b85275dd5R306) dumps schema with DecK and then validates against this.
From what I see this is what happens after running `deck gateway dump -o kong.yaml`
Screenshot 2023-12-05 at 09 27 46

**Comment by locao** [comment]
@nowNick there are conflicts in this PR, can you check please?

**Review by kikito — APPROVED** [review]
