### PR TITLE
fix(acl) second try fixing acl plugin to return 401

### LINKED ISSUE #4480: ACL plugin: 401 vs 403
### Summary
ACL plugin should return 401 when credentials is not provided. Now always returns 403

### Steps To Reproduce
1. Add ACL plugin with white list to any service
2. Add Any security plugin (ApiKey)
3. Request any service route without credentials  (response 403)
4. Disable ACL plugin and send the request again (response 401)

401 Unauthorized (I don't have credentials) vs 403 Forbidden (I have credentials but, is refusing to fulfil it

### Additional Details & Logs
- Kong version (`1.0.2`)

### PR DESCRIPTION
**Pull request by bungle**
### Summary

The PR #5440 tried to fix the issue with ACL plugin, but it didn't do it completely. As seen here:
https://github.com/Kong/kong/pull/5440#issuecomment-574720075

This is a second try to fix it so that anonymous consumers that do not have ACL groups will get `401` status code instead of `403`.

### Issues Resolved

Fix #4480 (again)

### CODE REVIEW

**Comment by bungle** [comment]
@jeremyjpj0916, could you try this on top of the previous one?

**Comment by jeremyjpj0916** [comment]
@bungle Testing now, will report back in 30-45 mins.

**Comment by jeremyjpj0916** [comment]
@bungle 

Tested again with the same use case as before, this time it did 401 as desired. Thanks!

**Comment by bungle** [comment]
@jeremyjpj0916,

I think I need to fix one thing still, the error message is currently:
```
You cannot consume this service
```

But I think the normal:
```
Unauthorized
```

Is better in this case? Do you have opinion?

**Comment by jeremyjpj0916** [comment]
@bungle I didn't wanna be too picky 😆  , but yes I think I ```Unauthorized``` is more appropriate in this situation.

**Comment by bungle** [comment]
Ok, changed the message on `401` to be `Unauthorized` and updated the test suite.

File: kong/plugins/acl/handler.lua [hunk 1]
```diff
@@ -99,10 +104,20 @@ function ACLHandler:access(conf)
...
       if not consumer_groups then
-        local status = kong.client.get_credential() and 403 or 401
-        return kong.response.exit(status, {
-          message = "You cannot consume this service"
-        })
+        if config.type == BLACK and kong.client.get_credential() then
+          consumer_groups = EMPTY
+
+        else
+          if kong.client.get_credential() then
```
Comment (kikito) [inline kong/plugins/acl/handler.lua]: This code calls `kong.client.get_credential()` twice. LuaJIT will probably optimize this up, but let's localize it just in case.
