### PR TITLE
fix(core): fix an issue where Kong do not handle properly when Python and Javascript plugin server crashes

### LINKED ISSUE #12364: 100% CPU usage and keep posting event 'reset_instances' to go plugin server
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.5 / go-pdk 0.6.0

### Current Behavior

There is a self-development plugin written by Go with go-pdk v0.6.0.
It is running well and stable more than one year.
Recently we've upgraded kong from 3.4.2 to 3.5.0 and then found sometimes 100% CPU usage happens and Kong keep calling `reset_instances` repeatedly but always failed.

My key configuration to enable the Go plugin server:
```env
KONG_PLUGINSERVER_NAMES=my_plugin
KONG_PLUGINSERVER_MY_PLUGIN_QUERY_CMD="/usr/local/bin/my_plugin -dump"
```

When this issue happens, I noticed that:
- 100% CPU usage (see the figure below)
- Cannot find any plugin crash logs, exception, nil pointer, errors during that period.
- Not reproducible on my local environment but it happens more than one times on production environment.
- Log shows:
```log
2024/01/17 10:27:46 [warn][kong] mp_rpc.lua:340 [myPlugin] no plugin instance 31
(repeat)
// ....after few moments...
2024/01/17 10:28:10 [error][kong] mp_rpc.lua:336 [myPlugin] failed to post plugin_server reset_instances event: failed to 
publish event: queue overflow
(repeat)
```
image

After some quick tracing, it seems like this function https://github.com/Kong/kong/blob/3.5.0/kong/runloop/plugin_servers/mp_rpc.lua#L328-L345 is a recursive function and keep posting event `reset_instance` and call itself again if the error is still `no plugin instance` and then [run out of event queue size](https://github.com/Kong/lua-resty-events/blob/main/lualib/resty/events/queue.lua#L33). 

**The most weirdest thing is that there is NO crash log related to the plugin but kong tries to reset it and then failed.**

Also I found some similar issues:
https://github.com/Kong/kong/issues/7148
https://github.com/Kong/kong/issues/8293
https://github.com/Kong/kong/issues/9301

cc @samugi @StarlightIbuki (not sure you guys are familiar with this issue)

### Expected Behavior

Not making CPU 100% and restart the plugin server.

### Steps To Reproduce

Not reproducible

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by StarlightIbuki**
### Summary

The bug was introduced when refactoring/cherry-picking. We missed the `mp_rpc.lua`. The PR also syncs the changes made to EE branches.

**DO NOT CHEERY-PICK THIS TO EE**.

### Checklist

- [N/A] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [N/A] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #12364
Fix KAG-3765

### CODE REVIEW

**Review by ADD-SP — APPROVED** [review]

File: kong/runloop/plugin_servers/pb_rpc.lua [hunk 1]
```diff
@@ -371,7 +371,7 @@ function Rpc:call_start_instance(plugin_name, conf)
     return nil, err
   end
 
-  kong.log.debug("started plugin server: seq ", conf.__seq__, ", worker ", ngx.worker.id() or -1, ", instance id ",
+  kong.log.debug("started plugin server: seq ", conf.__seq__, ", worker ", ngx.worker.id(), ", instance id ",
```
Comment (ms2008) [inline kong/runloop/plugin_servers/pb_rpc.lua:374]: Please keep the `or -1` here, as `ngx.worker.id()` returns `nil` for privileged workers. We've changed all parts of the codebase, so please be consistent.

Ref: https://github.com/Kong/kong/pull/12385

**Review by gszr — APPROVED** [review]
Good catch. I have the same changes over here in my wip branch: https://github.com/Kong/kong/commit/55586c1ce380688f2511aebbd98dda7c1d76bc4d. Let's merge this one and I will rebase mine 👍🏻

File: changelog/unreleased/kong/plugin_server_restart.yml [hunk 2]
```diff
@@ -0,0 +1,3 @@
+message: "**Plugin Server**: fix an issue where Kong do not handle properly when Python and Javascript plugin server crashes"
```
Comment (gszr) [inline changelog/unreleased/kong/plugin_server_restart.yml:1]:
```suggestion
message: "**Plugin Server**: fix an issue where Kong fails to properly restart MessagePack-based pluginservers (used in Python and Javascript plugins, for example)"
```

Comment (gszr) [reply changelog/unreleased/kong/plugin_server_restart.yml:1]: Good to merge after this change ^

**Review by gszr — CHANGES_REQUESTED** [review]

**Review by ms2008 — APPROVED** [review]

**Review by gszr — APPROVED** [review]

**Comment by gszr** [comment]
@StarlightIbuki - please open the remaining PRs on the kong-ee side, fixing the log line divergence.

**Comment by StarlightIbuki** [comment]
> @StarlightIbuki - please open the remaining PRs on the kong-ee side, fixing the log line divergence. Also consider fixing this one [55586c1#diff-898289fc808a047bf9f9401e7e7b38625131477da1363ce4f68719a3dd9d6dec](https://github.com/Kong/kong/commit/55586c1ce380688f2511aebbd98dda7c1d76bc4d#diff-898289fc808a047bf9f9401e7e7b38625131477da1363ce4f68719a3dd9d6dec)

Do we have a PR for this branch? Or is it still WIP?

**Comment by gszr** [comment]
> > @StarlightIbuki - please open the remaining PRs on the kong-ee side, fixing the log line divergence. Also consider fixing this one [55586c1#diff-898289fc808a047bf9f9401e7e7b38625131477da1363ce4f68719a3dd9d6dec](https://github.com/Kong/kong/commit/55586c1ce380688f2511aebbd98dda7c1d76bc4d#diff-898289fc808a047bf9f9401e7e7b38625131477da1363ce4f68719a3dd9d6dec)
> 
> Do we have a PR for this branch? Or is it still WIP?

Still wip. I will rebase it.
