### PR TITLE
fix(PDK): req.start_time for PDK log phase

### LINKED ISSUE #9409: kong.nginx.req_start_time() returns zero in log phase
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

The code in `init.lua` simply sets the plugin api `kong.nginx.req_start_time` to `ngx.req.start_time`, but the log phase was delay-executed after the request has finished, so I think the value of `ngx.req.start_time()` should be persisted in `save_for_later[co]` to make it work.

And also some other bugs could be the same reason, for example, when calling `kong.request.get_host()`, the process `check_phase` produces an error message, due to the `ngx.ctx.KONG_PHASE` is empty.

### Expected Behavior

`kong.nginx.req_start_time()` returns right value in `log` phase

### Steps To Reproduce

```markdown
1. Run kong-gateway:2.8.1
2. Setup a plugin with a `log` phase
3. call `kong.nginx.req_start_time()`
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by StarlightIbuki**
Fix #9409

### CODE REVIEW

**Review by fffonion — APPROVED** [review]

**Review by chronolaw — APPROVED** [review]

**Comment by chronolaw** [comment]
Need a change log entry.

File: kong/runloop/plugin_servers/init.lua [hunk 1]
```diff
@@ -108,7 +108,10 @@ local exposed_api = {
     return kong.response.get_source(saved and saved.ngx_ctx or nil)
   end,
 
-  ["kong.nginx.req_start_time"] = ngx.req.start_time,
+  ["kong.nginx.req_start_time"] = function ()
```
Comment (chronolaw) [inline kong/runloop/plugin_servers/init.lua:111]: remove redundant space before `()`

Comment (bungle) [inline kong/runloop/plugin_servers/init.lua:111]:
```suggestion
  ["kong.nginx.req_start_time"] = function()
```
