### PR TITLE
fix(conf) retain IPv6 brackets in proxy_listen and admin_listen

### LINKED ISSUE #3475: IPV6 address in PROXY_LISTEN env variable generates error
### Summary

When the environment variable PROXY_LISTEN is set to [::]:443 nginx quits with the error:
nginx: [emerg] invalid port in "0000:0000:0000:0000:0000:0000:0000:0000:8443" of the "listen" directive in /usr/local/kong/nginx-kong.conf:46

This is the relevant part of the /usr/local/kong/nginx-kong.conf file generated:

server {
    server_name kong;
    listen 0000:0000:0000:0000:0000:0000:0000:0000:8443 ssl;
    error_page 400 404 408 411 412 413 414 417 494 /kong_error_handler;
    error_page 500 502 503 504 /kong_error_handler;

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.13.1
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System: Oracle Linux 7.5

### PR DESCRIPTION
**Pull request by hishamhm**
Nginx requires brackets in IPv6 addresses, but `normalize_ip` does not include them (due to backwards compatibility with its other uses elsewhere in the codebase).

Fixes #3475.

### CODE REVIEW

File: kong/conf_loader.lua [hunk 1]
```diff
@@ -411,8 +411,13 @@ local function parse_listeners(values)
       ip.host, ip.port = remainder:match("(.+):([%d]+)$")
 
     else
-      -- It's an IPv4 or IPv6, just normalize it
+      -- It's an IPv4 or IPv6, normalize it
       ip = utils.normalize_ip(remainder)
+      -- nginx requires brackets in IPv6 addresses, but normalize_ip does
+      -- not include them (due to backwards compatibility with its other uses)
+      if ip and ip.host:find(":", 1, true) then
```
Comment (thibaultcha) [inline kong/conf_loader.lua]: For the sake reference code and efficiency, probably better to rely on:
```lua
if ip and ip.type == "ipv6" then

end
```

Comment (hishamhm) [reply kong/conf_loader.lua]: Updated!
