### PR TITLE
fix(plugins) ensure go plugins on protobuf restart instance

### LINKED ISSUE #8293: Kong can't call an embedded server plugin once the plugin is killed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.7.0

### Current Behavior

As title, kong seems to fail to call external embedded server plugin if the plugin is killed by for example OOM. After a plugin is killed, kong outputs error logs as below, but the request succeeds.

```
2022/01/14 05:43:17 [error] 1109#0: *1757 [kong] pb_rpc.lua:365 [hello] closed, client: 172.18.0.1, server: kong, request: "HEAD / HTTP/1.1", host: "localhost:8000"
```

### Expected Behavior

Best is Kong can call external embedded server plugin even after the plugin is killed.

### Steps To Reproduce

```markdown
I have tested in docker environment of my local laptop.

Example go plugin (from https://github.com/Kong/go-plugins/blob/master/go-hello.go)


package main

import (
	"fmt"
	"log"

	"github.com/Kong/go-pdk"
	"github.com/Kong/go-pdk/server"
)

type Config struct {
	Message string
}

func main() {
	server.StartServer(New, "1.0.0", 1)
}

func New() interface{} {
	return &Config{}
}

func (conf Config) Access(kong *pdk.PDK) {
	host, err := kong.Request.GetHeader("host")
	if err != nil {
		log.Printf("Error reading 'host' header: %s", err.Error())
	}

	message := conf.Message
	if message == "" {
		message = "hello"
	}
	kong.Response.SetHeader("x-hello-from-go", fmt.Sprintf("Go says %s to %s", message, host))
}
```

Dockerfile of kong

```
FROM golang:1.16.4-buster as plugin-hello

RUN mkdir /go-plugins
WORKDIR /go-plugins
COPY plugin-hello/*.go plugin-hello/go.mod plugin-hello/go.sum /go-plugins/
RUN go build -o /go-plugins/hello

FROM kong:2.7.0-ubuntu

USER root
COPY --from=plugin-hello /go-plugins/hello /usr/local/bin

USER kong
ENTRYPOINT ["/docker-entrypoint.sh"]
STOPSIGNAL SIGQUIT
HEALTHCHECK --interval=10s --timeout=10s --retries=10 CMD kong health
CMD ["kong", "docker-start"]
```

docker-compose.yml

```
version: "3.9"
services:
  httpbin:
    image: kennethreitz/httpbin
  kong:
    build: .
    ports: ["8000:8000", "8001:8001"]
    environment:
    - KONG_DATABASE=off
    - KONG_DECLARATIVE_CONFIG=/opt/kong.yml
    - KONG_PLUGINSERVER_NAMES=hello
    - KONG_PLUGINSERVER_HELLO_QUERY_CMD=/usr/local/bin/hello -dump
    - KONG_PLUGINS=hello
    - KONG_PROXY_LISTEN=0.0.0.0:8000
    - KONG_ADMIN_LISTEN=0.0.0.0:8001
    - KONG_HEADERS=off
    - KONG_LOG_LEVEL=info
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stdout
    - KONG_ADMIN_ERROR_LOG=/dev/stdout
    volumes:
    - ./kong.yml:/opt/kong.yml
```

kong.yml

```
_format_version: "1.1"
services:
- url: http://httpbin
  routes:
  - paths: ["/"]
  plugins:
  - name: hello
    config:
      message: hello
```

## Steps to reproduce

```
$ docker-compose build
$ docker-compose up
$ curl -I localhost:8000
```

In this time, x-hello-from-go exists in response header 

```
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 9593
Connection: keep-alive
x-hello-from-go: Go says hello to localhost:8000
Server: gunicorn/19.9.0
Date: Fri, 14 Jan 2022 05:40:09 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
```

After login to kong and kill plugin process, request succeeds but x-hello-from-go does not exist in response header.

```
$ curl -I  localhost:8000
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 9593
Connection: keep-alive
Server: gunicorn/19.9.0
Date: Fri, 14 Jan 2022 05:43:17 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
```

Kong outputs error log as below.

```
kong_1     | 2022/01/14 05:43:17 [error] 1109#0: *1757 [kong] pb_rpc.lua:365 [hello] closed, client: 172.18.0.1, server: kong, request: "HEAD / HTTP/1.1", host: "localhost:8000"
```

However, hello plugin is running with different process id.

```
$ docker-compose exec kong bash
kong@1ff50af4cc82:/$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
kong         1  0.0  1.2 639600 26060 ?        Ss   05:39   0:00 nginx: master process /u
kong      1109  0.0  4.4 709420 90432 ?        S    05:39   0:00 nginx: worker process
kong      1110  0.0  4.3 708844 88904 ?        S    05:39   0:00 nginx: worker process
kong      1111  0.0  4.3 708844 88904 ?        S    05:39   0:00 nginx: worker process
kong      1112  0.0  4.4 708844 89504 ?        S    05:39   0:00 nginx: worker process
kong      1424  0.0  0.4 1154228 8488 ?        Sl   05:43   0:00 /usr/local/bin/hello
kong      4667  2.0  0.1   4116  3376 pts/0    Ss   06:22   0:00 bash
kong      4676  0.0  0.1   5904  2964 pts/0    R+   06:22   0:00 ps aux
```
```


### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gszr**
Fix issue where the Go plugin instance would not get updated after
a plugin server restart.

Fixes #8293

### CODE REVIEW

File: kong/runloop/plugin_servers/pb_rpc.lua [hunk 1]
```diff
@@ -393,13 +393,10 @@ function Rpc:handle_event(plugin_name, conf, phase)
     instance_id = instance_id,
     event_name = phase,
   }, true)
-  if not res then
+  if not res or res == "" then
```
Comment (fffonion) [inline kong/runloop/plugin_servers/pb_rpc.lua:396]: seems `res` can be either `nil` or a table, wondering why include `res == ""` here

File: kong/runloop/plugin_servers/pb_rpc.lua [hunk 2]
```diff
@@ -393,13 +393,10 @@ function Rpc:handle_event(plugin_name, conf, phase)
...
     kong.log.err(err)
-
-    if string.match(err:lower(), "no plugin instance") then
```
Comment (fffonion) [inline kong/runloop/plugin_servers/pb_rpc.lua:399]: maybe `string.match(err:lower(), "no plugin instance") or string.match(err:lower(), "closed")`?

File: kong/runloop/plugin_servers/pb_rpc.lua (hunk 1 above)
Comment (javierguerragiraldez) [reply kong/runloop/plugin_servers/pb_rpc.lua:396]: lua_protobuf has changed how it manages default values between versions.  there are settings, but this is a safe solution too.

**Comment by yaobo-lab** [comment]
This bug when. Can be merged into the main branch??

File: kong/runloop/plugin_servers/pb_rpc.lua (hunk 2 above)
Comment (gszr) [reply kong/runloop/plugin_servers/pb_rpc.lua:399]: Good call! Thanks!
