### PR TITLE
fix(admin) unsupported media type (415) error reported on issue #1182

### LINKED ISSUE #1182: key-auth plugin error when creating new keys - "unsupported media type" - change of behavior
Hi, recently upgraded to 0.8.0 and the behavior for the key-auth key creation on a consumer appears to have changed.  The documentation (and previous behavior) asks for the following command to generate an apikey for a user:

curl -X POST http://localhost:8001/consumers/{consumer}/key-auth

This worked on the previous version I was running (0.7.0?) but now that command returns the following:

```
<html>
<head><title>415 Unsupported Media Type</title></head>
<body bgcolor="white">
<center><h1>415 Unsupported Media Type</h1></center>
<hr><center>openresty/1.9.7.3</center>
</body>
</html>
```

I found if I add an empty POST body it happily generates the key in the same way it used to.

curl -X POST http://localhost:8001/consumers/{consumer}/key-auth -d ""

Not sure if this is intentional and the plugin documentation is now lagging behind, or if this has cropped up since the update to 0.8.0.  If it matters I'm running this on postgres.

Thanks!

Matt

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Fixes issue when using empty body with supported content-types on POST / PUT / PATCH.

### Issues resolved

Fix #1182

### CODE REVIEW

**Comment by bungle** [comment]
One note:

1. when using `application/json` content type
2. empty body

This results:

```javascript
{
    "message": "Cannot parse JSON body"
}
```

Not sure though, should we allow this to go through as we do with `multipart/form-data` and `application/x-www-form-urlencoded` (they don't error on parsing errors).

**Comment by bungle** [comment]
This also contains (apart from added tests) fixes to 02-apis_routes_spec.lua which was bit strangely organized and was also flaky on my machine. The client seems is not happy to be reused on errors (it sometimes closes itself).

File: spec/02-integration/04-admin_api/02-apis_routes_spec.lua [hunk 1]
```diff
@@ -259,6 +315,55 @@ describe("Admin API #" .. kong_config.database, function()
         end
       end)
       describe("errors", function()
+        it("returns 415 on invalid content-type", function()
+          local res = assert(client:request {
+            method = "POST",
```
Comment (thibaultcha) [inline spec/02-integration/04-admin_api/02-apis_routes_spec.lua]: Are those tests duplicates of the above ones? Maybe the intent was to re-run them with `PUT`?

File: spec/02-integration/04-admin_api/02-apis_routes_spec.lua [hunk 2]
```diff
@@ -206,7 +260,7 @@ describe("Admin API #" .. kong_config.database, function()
         --
         -- Eventually, our Admin endpoint will follow a more appropriate
         -- behavior for PUT.
-        local res = assert(client:send {
+        local res = assert(helpers.admin_client():send {
```
Comment (thibaultcha) [inline spec/02-integration/04-admin_api/02-apis_routes_spec.lua]: Curious: why not using `client` here?

File: spec/02-integration/04-admin_api/02-apis_routes_spec.lua [hunk 3]
```diff
@@ -87,6 +88,54 @@ describe("Admin API #" .. kong_config.database, function()
...
+          })
+          assert.res_status(415, res)
+        end)
+        it("returns 400 on missing body with application/json", function()
+          local res = assert(client:request {
+            method = "POST",
+            path = "/apis",
+            headers = {["Content-Type"] = "application/json"}
+          })
+          assert.res_status(400, res)
```
Comment (thibaultcha) [inline spec/02-integration/04-admin_api/02-apis_routes_spec.lua]: When we are returning a `400` error here, I think a second assertion for the body should be added for explicitness, ensuring that it is a schema error from our DAO (and not a Lapis error or some other sort of error).

**Comment by thibaultcha** [comment]
> Not sure though, should we allow this to go through as we do with multipart/form-data and application/x-www-form-urlencoded (they don't error on parsing errors).

Good point. I would tend to say this behavior (reporting an invalid JSON payload) is fine. After all, a client would encounter the same error if they attempted to send an invalid JSON payload (`{"hello":"world"`), and it seems logical that the same error happen in both cases I think.

File: kong/api/init.lua [hunk 4]
```diff
@@ -89,10 +90,31 @@ end
...
+  local content_type = self.req.headers["content-type"]
+  if not content_type then
+    local content_length = self.req.headers["content-length"]
+    if content_length == "0" then
+      return
+    end
+
+    if not content_length then
+      local _, err = ngx.req.socket()
+      if err == "no body" then
```
[the remark this answers is not in the document]
Comment (bungle) [reply kong/api/init.lua]: I think the first one checks client header and the other checks if there is no body even when the client didn't add content-length header. I may be wrong and have to recheck this. I assume client can set that header to say 1000, but still doesn't send body.

[the remark this answers is not in the document]
Comment (bungle) [reply kong/api/init.lua]: I rechecked this and test is needed.

File: spec/02-integration/04-admin_api/02-apis_routes_spec.lua (hunk 2 above)
Comment (bungle) [reply spec/02-integration/04-admin_api/02-apis_routes_spec.lua]: Because the test generates 404 and it makes the client really flaky as you see it runs this `it_content_types` loop, so first time it works, but subsequently you start getting:

> spec/02-integration/04-admin_api/02-apis_routes_spec.lua:263: closed

The client is really problematic, because you cannot really call `:send` multiple times without getting into issues. That's why. To make tests pass reliably.

File: spec/02-integration/04-admin_api/02-apis_routes_spec.lua (hunk 1 above)
Comment (bungle) [reply spec/02-integration/04-admin_api/02-apis_routes_spec.lua]: Yes, a copy-paste-bug. Pushed a new version.

File: spec/02-integration/04-admin_api/02-apis_routes_spec.lua (hunk 2 above)
Comment (thibaultcha) [reply spec/02-integration/04-admin_api/02-apis_routes_spec.lua]: Ohh I see - hmmm

File: kong/api/init.lua (hunk 4 above)
[the remark this answers is not in the document]
Comment (thibaultcha) [reply kong/api/init.lua]: Hmmm, would you care to elaborate why? It seems to me that in our current code path (that is, not calling `ngx.req.init_body()`, not calling `ngx_http_lua_create_fake_request`, and not making a subrequest), the only place where `content_length_n` is set is: https://github.com/openresty/lua-nginx-module/blob/b122ed7ad2a6bf6f90d8d5c5939c0dd98a4ddbf7/src/ngx_http_lua_headers_in.c#L570 - in which case, the value is taken from the `Content-Length` header already. So when `ngx.req.socket()` returns `"no body"`, it means it has did the same check as the one above, L.100 (actually, `content_length_n <= 0`).

Am I missing something?

File: spec/02-integration/04-admin_api/02-apis_routes_spec.lua [hunk 5]
```diff
@@ -87,6 +88,54 @@ describe("Admin API #" .. kong_config.database, function()
       end)
 
       describe("errors", function()
+        it("returns 415 on invalid content-type", function()
```
[the remark this answers is not in the document]
Comment (thibaultcha) [reply spec/02-integration/04-admin_api/02-apis_routes_spec.lua]: Ping here as well - I would say this is concerning considering this endpoint (or its underlying implementation) may disappear soon?

File: kong/api/init.lua (hunk 4 above)
[the remark this answers is not in the document]
Comment (thibaultcha) [reply kong/api/init.lua]: This and the `/apis` endpoint concern are the last "blockers" for me. But feel free to dismiss if I just said non-sense above ^

Apart from those 2 points, this is GTM :+1:
