### PR TITLE
fix(globalpathces) ngx socket connect to unix domain socket

### LINKED ISSUE #3626: connect to unix socked failed
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

tcpsocket return **bad argument #2 to 'connect' (number expected, got nil)** whan calling `connect` method with UNIX socket address, unlike what stated in [ngx.socket.tcp documentation](https://github.com/openresty/lua-nginx-module/tree/v0.10.13#tcpsockconnect), 

### Steps To Reproduce

1. create custom plugin based on tcp-log and modify the call to `connect` method by ommiting the `port` parameter when the `host` start with `unix:`
1. start another program that listen in the unix socket
1. create api and then add the custom plugin to the api
1. invoke the api

### Additional Details & Logs

- Kong version 0.14.0
- Kong debug-level startup logs 

```
kong_1         | preparation done. Executing command: ./bin/kong start -vv -c ./bin/kong.conf
kong_1         | 2018/07/17 08:36:46 [verbose] Kong: 0.14.0
kong_1         | 2018/07/17 08:36:46 [debug] ngx_lua: 10013
kong_1         | 2018/07/17 08:36:46 [debug] nginx: 1013006
kong_1         | 2018/07/17 08:36:46 [warn] the 'custom_plugins' configuration property is deprecated, use 'plugins' instead
kong_1         | 2018/07/17 08:36:46 [debug] Lua: LuaJIT 2.1.0-beta3
kong_1         | 2018/07/17 08:36:46 [verbose] reading config file at ./bin/kong.conf
kong_1         | 2018/07/17 08:36:46 [debug] reading environment variables
kong_1         | 2018/07/17 08:36:46 [debug] KONG_ADMIN_LISTEN ENV found with "0.0.0.0:8001"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_TRUSTED_IPS ENV found with "0.0.0.0/0,::/0"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_PREFIX ENV found with "/prefix"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_CUSTOM_PLUGINS ENV found with "mobdebug,mainapi_log"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_PG_HOST ENV found with "postgres"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_DATABASE ENV found with "postgres"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_ADMIN_ERROR_LOG ENV found with "/proc/1/fd/2"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_ADMIN_ACCESS_LOG ENV found with "/proc/1/fd/2"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_LOG_LEVEL ENV found with "debug"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_PROXY_ERROR_LOG ENV found with "/proc/1/fd/2"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_NGINX_DAEMON ENV found with "off"
kong_1         | 2018/07/17 08:36:46 [debug] KONG_PROXY_ACCESS_LOG ENV found with "/proc/1/fd/1"
kong_1         | 2018/07/17 08:36:46 [debug] admin_access_log = "/proc/1/fd/2"
kong_1         | 2018/07/17 08:36:46 [debug] admin_error_log = "/proc/1/fd/2"
kong_1         | 2018/07/17 08:36:46 [debug] admin_listen = {"0.0.0.0:8001"}
kong_1         | 2018/07/17 08:36:46 [debug] anonymous_reports = true
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_consistency = "ONE"
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_contact_points = {"127.0.0.1"}
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_keyspace = "kong"
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_lb_policy = "RoundRobin"
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_port = 9042
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_repl_factor = 1
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_repl_strategy = "SimpleStrategy"
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_schema_consensus_timeout = 10000
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_ssl = false
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_ssl_verify = false
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_timeout = 5000
kong_1         | 2018/07/17 08:36:46 [debug] cassandra_username = "kong"
kong_1         | 2018/07/17 08:36:46 [debug] client_body_buffer_size = "8k"
kong_1         | 2018/07/17 08:36:46 [debug] client_max_body_size = "0"
kong_1         | 2018/07/17 08:36:46 [debug] client_ssl = false
kong_1         | 2018/07/17 08:36:46 [debug] custom_plugins = {"mobdebug","mainapi_log"}
kong_1         | 2018/07/17 08:36:46 [debug] database = "postgres"
kong_1         | 2018/07/17 08:36:46 [debug] db_cache_ttl = 0
kong_1         | 2018/07/17 08:36:46 [debug] db_resurrect_ttl = 30
kong_1         | 2018/07/17 08:36:46 [debug] db_update_frequency = 5
kong_1         | 2018/07/17 08:36:46 [debug] db_update_propagation = 0
kong_1         | 2018/07/17 08:36:46 [debug] dns_error_ttl = 1
kong_1         | 2018/07/17 08:36:46 [debug] dns_hostsfile = "/etc/hosts"
kong_1         | 2018/07/17 08:36:46 [debug] dns_no_sync = false
kong_1         | 2018/07/17 08:36:46 [debug] dns_not_found_ttl = 30
kong_1         | 2018/07/17 08:36:46 [debug] dns_order = {"LAST","SRV","A","CNAME"}
kong_1         | 2018/07/17 08:36:46 [debug] dns_resolver = {}
kong_1         | 2018/07/17 08:36:46 [debug] dns_stale_ttl = 4
kong_1         | 2018/07/17 08:36:46 [debug] error_default_type = "text/plain"
kong_1         | 2018/07/17 08:36:46 [debug] headers = {"server_tokens","latency_tokens"}
kong_1         | 2018/07/17 08:36:46 [debug] log_level = "debug"
kong_1         | 2018/07/17 08:36:46 [debug] lua_package_cpath = ""
kong_1         | 2018/07/17 08:36:46 [debug] lua_package_path = "./?.lua;./?/init.lua;"
kong_1         | 2018/07/17 08:36:46 [debug] lua_socket_pool_size = 30
kong_1         | 2018/07/17 08:36:46 [debug] lua_ssl_verify_depth = 1
kong_1         | 2018/07/17 08:36:46 [debug] mem_cache_size = "128m"
kong_1         | 2018/07/17 08:36:46 [debug] nginx_admin_directives = {}
kong_1         | 2018/07/17 08:36:46 [debug] nginx_daemon = "off"
kong_1         | 2018/07/17 08:36:46 [debug] nginx_http_directives = {}
kong_1         | 2018/07/17 08:36:46 [debug] nginx_optimizations = true
kong_1         | 2018/07/17 08:36:46 [debug] nginx_proxy_directives = {}
kong_1         | 2018/07/17 08:36:46 [debug] nginx_user = "nobody nobody"
kong_1         | 2018/07/17 08:36:46 [debug] nginx_worker_processes = "auto"
kong_1         | 2018/07/17 08:36:46 [debug] pg_database = "kong"
kong_1         | 2018/07/17 08:36:46 [debug] pg_host = "postgres"
kong_1         | 2018/07/17 08:36:46 [debug] pg_port = 5432
kong_1         | 2018/07/17 08:36:46 [debug] pg_ssl = false
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] globalpatches.lua:9: installing the globalpatches
kong_1         | 2018/07/17 08:36:47 [warn] 33#0: [lua] log.lua:63: log(): the 'custom_plugins' configuration property is deprecated, use 'plugins' instead
kong_1         | nginx: [warn] [lua] log.lua:63: log(): the 'custom_plugins' configuration property is deprecated, use 'plugins' instead
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:431: init(): [dns-client] (re)configuring dns client
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:435: init(): [dns-client] staleTtl = 4
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:438: init(): [dns-client] noSynchronisation = false
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:457: init(): [dns-client] query order = LAST, SRV, A, CNAME
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:489: init(): [dns-client] adding A-record from 'hosts' file: bedbf0bf7230 =172.16.1.4
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-mcastprefix = [ff00::0]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-localnet = [fe00::0]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:489: init(): [dns-client] adding A-record from 'hosts' file: localhost = 127.0.0.1
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost =[::1]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-localhost = [::1]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-loopback = [::1]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-allnodes = [ff02::1]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-allrouters = [ff02::2]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:548: init(): [dns-client] nameserver 127.0.0.11
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:553: init(): [dns-client] attempts = 5
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:562: init(): [dns-client] timeout = 2000 ms
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:566: init(): [dns-client] ndots = 0
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:568: init(): [dns-client] search = telkom.co.id
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:574: init(): [dns-client] badTtl = 30 s
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:576: init(): [dns-client] emptyTtl = 1 s
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:98: load_plugins(): Discovering used plugins
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: correlation-id
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: pre-function
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: cors
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: rate-limiting
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: loggly
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: hmac-auth
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: zipkin
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: request-size-limiting
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: azure-functions
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: request-transformer
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: oauth2
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: response-transformer
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: ip-restriction
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: statsd
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: jwt
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: basic-auth
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: key-auth
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: http-log
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: mainapi_log
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: datadog
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: tcp-log
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: post-function
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: acl
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: mobdebug
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: prometheus
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: syslog
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: response-ratelimiting
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: udp-log
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: file-log
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: aws-lambda
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: bot-detection
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: ldap-auth
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] init.lua:132: load_plugins(): Loading plugin: request-termination
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:431: init(): [dns-client] (re)configuring dns client
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:435: init(): [dns-client] staleTtl = 4
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:438: init(): [dns-client] noSynchronisation = false
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:457: init(): [dns-client] query order = LAST, SRV, A, CNAME
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:489: init(): [dns-client] adding A-record from 'hosts' file: bedbf0bf7230 =172.16.1.4
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-mcastprefix = [ff00::0]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-localnet = [fe00::0]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:489: init(): [dns-client] adding A-record from 'hosts' file: localhost = 127.0.0.1
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost =[::1]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-localhost = [::1]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-loopback = [::1]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-allnodes = [ff02::1]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:504: init(): [dns-client] adding AAAA-record from 'hosts' file: ip6-allrouters = [ff02::2]
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:548: init(): [dns-client] nameserver 127.0.0.11
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:553: init(): [dns-client] attempts = 5
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:562: init(): [dns-client] timeout = 2000 ms
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:566: init(): [dns-client] ndots = 0
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:568: init(): [dns-client] search = telkom.co.id
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:574: init(): [dns-client] badTtl = 30 s
kong_1         | 2018/07/17 08:36:47 [debug] 33#0: [lua] client.lua:576: init(): [dns-client] emptyTtl = 1 s
kong_1         | 2018/07/17 08:36:47 [notice] 33#0: using the "epoll" event method
kong_1         | 2018/07/17 08:36:47 [notice] 33#0: openresty/1.13.6.2
kong_1         | 2018/07/17 08:36:47 [notice] 33#0: built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
kong_1         | 2018/07/17 08:36:47 [notice] 33#0: OS: Linux 4.9.60-linuxkit-aufs
kong_1         | 2018/07/17 08:36:47 [notice] 33#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
kong_1         | 2018/07/17 08:36:47 [notice] 33#0: start worker processes
kong_1         | 2018/07/17 08:36:47 [notice] 33#0: start worker process 41
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] globalpatches.lua:224: randomseed(): seeding PRNG from OpenSSL RAND_bytes()
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] globalpatches.lua:250: randomseed(): random seed: 203298166148 for worker nb 0
kong_1         | 2018/07/17 08:36:47 [notice] 33#0: start worker process 42
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] globalpatches.lua:224: randomseed(): seeding PRNG from OpenSSL RAND_bytes()
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] globalpatches.lua:250: randomseed(): random seed: 125129314158 for worker nb 1
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] events.lua:192: do_event_json(): worker-events: handling event; source=resty-worker-events, event=started, pid=41, data=nil
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] events.lua:192: do_event_json(): worker-events: handling event; source=resty-worker-events, event=started, pid=42, data=nil
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "pre-function": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "pre-function": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "opentracing": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "mobdebug": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "bot-detection": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "cors": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "jwt": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "oauth2": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "key-auth": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "ldap-auth": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "basic-auth": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:24: access(): executing plugin "mainapi_log": access
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "hmac-auth": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "ip-restriction": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "request-size-limiting": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "acl": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "rate-limiting": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "response-ratelimiting": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "request-transformer": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "response-transformer": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "aws-lambda": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "azure-functions": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "prometheus": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "http-log": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "statsd": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "datadog": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "file-log": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "udp-log": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "tcp-log": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "loggly": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "syslog": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "request-termination": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "correlation-id": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 42#0: *2 [lua] base_plugin.lua:12: init_worker(): executing plugin "post-function": init_worker
kong_1         | 2018/07/17 08:36:49 [debug] 42#0: *3 [lua] balancer.lua:464: fetching all upstreams
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "opentracing": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "mobdebug": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "bot-detection": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "cors": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "jwt": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "oauth2": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "key-auth": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "ldap-auth": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "basic-auth": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:24: access(): executing plugin "mainapi_log": access
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "hmac-auth": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "ip-restriction": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "request-size-limiting": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "acl": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "rate-limiting": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "response-ratelimiting": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "request-transformer": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "response-transformer": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "aws-lambda": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "azure-functions": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "prometheus": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "http-log": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "statsd": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "datadog": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "file-log": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "udp-log": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "tcp-log": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "loggly": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "syslog": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "request-termination": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "correlation-id": init_worker
kong_1         | 2018/07/17 08:36:47 [debug] 41#0: *1 [lua] base_plugin.lua:12: init_worker(): executing plugin "post-function": init_worker
kong_1         | 2018/07/17 08:36:49 [debug] 41#0: *8 [lua] events.lua:192: do_event_json(): worker-events: handling event; source=resty-worker-events, event=started, pid=42, data=nil
kong_1         | 2018/07/17 08:36:52 [debug] 42#0: *15 [lua] cluster_events.lua:222: [cluster_events] polling events from: 1531816607.559 to: 1531816612.561
kong_1         | 2018/07/17 08:36:54 [crit] 41#0: *7 [lua] balancer.lua:710: init(): failed loading initial list of upstreams: failed to get from node cache: could not acquire callback lock: timeout, context: ngx.timer
kong_1         | 2018/07/17 08:37:09 [debug] 42#0: *3 [lua] balancer.lua:725: init(): initialized 0 balancer(s), 0 error(s)
kong_1         | 2018/07/17 08:37:12 [debug] 41#0: *73 [lua] cluster_events.lua:222: [cluster_events] polling events from: 1531816607.559 to: 1531816632.567
```

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

```
2018/07/17 08:37:26 [error] 41#0: *122 [lua] handler.lua:31: unix:/var/run/logagent/tcp.sock, context: ngx.timer, client: 172.16.1.1, server: 0.0.0.0:8000

2018/07/17 08:37:46 [error] 41#0: *122 lua entry thread aborted: runtime error: ./kong/plugins/mainapi_log/handler.lua:32: badargument #2 to 'connect' (number expected, got nil)

stack traceback:

coroutine 0:

       [C]: in function 'connect'

       ./kong/plugins/mainapi_log/handler.lua:32: in function <./kong/plugins/mainapi_log/handler.lua:15>, context: ngx.timer,client: 172.16.1.1, server: 0.0.0.0:8000
```

- Kong configuration 

```
{"plugins":{"enabled_in_cluster":["mainapi_log"],"available_on_server":{"correlation-id":true,"pre-function":true,"cors":true,"rate-limiting":true,"loggly":true,"hmac-auth":true,"zipkin":true,"request-size-limiting":true,"azure-functions":true,"request-transformer":true,"oauth2":true,"response-transformer":true,"ip-restriction":true,"statsd":true,"jwt":true,"basic-auth":true,"key-auth":true,"http-log":true,"mainapi_log":true,"datadog":true,"tcp-log":true,"post-function":true,"acl":true,"mobdebug":true,"prometheus":true,"syslog":true,"response-ratelimiting":true,"udp-log":true,"file-log":true,"aws-lambda":true,"bot-detection":true,"ldap-auth":true,"request-termination":true}},"tagline":"Welcome to kong","configuration":{"plugins":["bundled"],"admin_ssl_enabled":false,"lua_ssl_verify_depth":1,"trusted_ips":["0.0.0.0\/0","::\/0"],"prefix":"\/prefix","loaded_plugins":{"correlation-id":true,"pre-function":true,"cors":true,"ldap-auth":true,"loggly":true,"hmac-auth":true,"zipkin":true,"bot-detection":true,"azure-functions":true,"request-transformer":true,"oauth2":true,"response-transformer":true,"syslog":true,"statsd":true,"jwt":true,"basic-auth":true,"key-auth":true,"http-log":true,"mainapi_log":true,"datadog":true,"tcp-log":true,"post-function":true,"rate-limiting":true,"acl":true,"ip-restriction":true,"response-ratelimiting":true,"mobdebug":true,"udp-log":true,"file-log":true,"aws-lambda":true,"prometheus":true,"request-size-limiting":true,"request-termination":true},"cassandra_username":"kong","admin_ssl_cert_csr_default":"\/prefix\/ssl\/admin-kong-default.csr","ssl_cert_key":"\/prefix\/ssl\/kong-default.key","dns_resolver":{},"pg_user":"kong","mem_cache_size":"128m","cassandra_data_centers":["dc1:2","dc2:3"],"nginx_admin_directives":{},"custom_plugins":["mobdebug","mainapi_log"],"pg_host":"postgres","nginx_acc_logs":"\/prefix\/logs\/access.log","proxy_listen":["0.0.0.0:8000","0.0.0.0:8443 ssl"],"client_ssl_cert_default":"\/prefix\/ssl\/kong-default.crt","ssl_cert_key_default":"\/prefix\/ssl\/kong-default.key","dns_no_sync":false,"db_update_propagation":0,"nginx_err_logs":"\/prefix\/logs\/error.log","cassandra_port":9042,"dns_order":["LAST","SRV","A","CNAME"],"dns_error_ttl":1,"headers":["server_tokens","latency_tokens"],"dns_stale_ttl":4,"nginx_optimizations":true,"database":"postgres","pg_database":"kong","nginx_worker_processes":"auto","lua_package_cpath":"","admin_acc_logs":"\/prefix\/logs\/admin_access.log","lua_package_path":".\/?.lua;.\/?\/init.lua;","nginx_pid":"\/prefix\/pids\/nginx.pid","upstream_keepalive":60,"admin_access_log":"\/proc\/1\/fd\/2","client_ssl_cert_csr_default":"\/prefix\/ssl\/kong-default.csr","proxy_listeners":[{"ssl":false,"ip":"0.0.0.0","proxy_protocol":false,"port":8000,"http2":false,"listener":"0.0.0.0:8000"},{"ssl":true,"ip":"0.0.0.0","proxy_protocol":false,"port":8443,"http2":false,"listener":"0.0.0.0:8443 ssl"}],"proxy_ssl_enabled":true,"cassandra_contact_points":["127.0.0.1"],"enabled_headers":{"latency_tokens":true,"X-Kong-Proxy-Latency":true,"Via":true,"server_tokens":true,"Server":true,"X-Kong-Upstream-Latency":true,"X-Kong-Upstream-Status":false},"ssl_ciphers":"ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256","cassandra_ssl":false,"db_resurrect_ttl":30,"ssl_cert_csr_default":"\/prefix\/ssl\/kong-default.csr","cassandra_consistency":"ONE","client_max_body_size":"0","admin_error_log":"\/proc\/1\/fd\/2","pg_ssl_verify":false,"dns_not_found_ttl":30,"pg_ssl":false,"cassandra_schema_consensus_timeout":10000,"client_ssl":false,"cassandra_repl_strategy":"SimpleStrategy","db_update_frequency":5,"nginx_kong_conf":"\/prefix\/nginx-kong.conf","cassandra_repl_factor":1,"nginx_http_directives":[{"value":"prometheus_metrics 5m","name":"lua_shared_dict"}],"kong_env":"\/prefix\/.kong_env","real_ip_header":"X-Real-IP","dns_hostsfile":"\/etc\/hosts","log_level":"debug","error_default_type":"text\/plain","ssl_cert":"\/prefix\/ssl\/kong-default.crt","cassandra_lb_policy":"RoundRobin","admin_ssl_cert_key_default":"\/prefix\/ssl\/admin-kong-default.key","cassandra_ssl_verify":false,"proxy_access_log":"\/proc\/1\/fd\/1","ssl_cipher_suite":"modern","real_ip_recursive":"off","proxy_error_log":"\/proc\/1\/fd\/2","client_ssl_cert_key_default":"\/prefix\/ssl\/kong-default.key","nginx_daemon":"off","anonymous_reports":true,"nginx_proxy_directives":{},"cassandra_timeout":5000,"pg_port":5432,"admin_listeners":[{"ssl":false,"ip":"0.0.0.0","proxy_protocol":false,"port":8001,"http2":false,"listener":"0.0.0.0:8001"}],"client_body_buffer_size":"8k","lua_socket_pool_size":30,"admin_ssl_cert_default":"\/prefix\/ssl\/admin-kong-default.crt","db_cache_ttl":0,"cassandra_keyspace":"kong","ssl_cert_default":"\/prefix\/ssl\/kong-default.crt","nginx_conf":"\/prefix\/nginx.conf","admin_listen":["0.0.0.0:8001"]},"version":"0.14.0","node_id":"64d5f381-57a1-4616-ab53-636618cc5df5","lua_version":"LuaJIT 2.1.0-beta3","prng_seeds":{"pid: 42":125129314158,"pid: 41":203298166148},"timers":{"pending":5,"running":0},"hostname":"bedbf0bf7230"}
```

- Operating system
Linux Ubuntu 16.04 (docker)

- Screenshot
screen shot 2018-07-17 at 15 53 05

### PR DESCRIPTION
**Pull request by rucciva**
### Summary

When connecting to unix domain socket, port parameter should not
be passed to tcpsock:connect or udpsock:connect

### Full changelog

* globalpatches of ngx.socket to connect to unix domain socket

### Issues resolved

Fix #3626

### CODE REVIEW

**Comment by rucciva** [comment]
Weird, the test succeded on the forked repository

screen shot 2018-07-19 at 12 48 31

**Comment by Tieske** [comment]
@rucciva  one testsuite (PDK) failed. It ran fine after restarting.

**Comment by Tieske** [comment]
actually this would be better:

```lua
    -- need to do the extra check here: https://github.com/openresty/lua-nginx-module/issues/860
    local function strip_nils(port, opts)
      if opts then
        return port, opts
      elseif port then
        return port
      end
    end

    -- to be called as:
    old_tcp_connect(sock, target_ip, strip_nils(port, opts))
```

**Comment by rucciva** [comment]
this failed when opts is not nil but the port is nil

```lua
   -- need to do the extra check here: https://github.com/openresty/lua-nginx-module/issues/860
    local function strip_nils(port, opts)
      if opts then
        return port, opts
      elseif port then
        return port
      end
    end

    -- to be called as:
    old_tcp_connect(sock, target_ip, strip_nils(port, opts))
```

i think it should be

```lua
local function strip_nils(port, opts)
      if opts and port then
        return port, opts
      elseif opts then
        return opts
      elseif port then
        return port
      end
    end
```

and the caller will be like this

``` lua
    local function tcp_resolve_connect(sock, host, port, sock_opts)
      local target_ip, target_port
      if sub(host, 1, 5) == "unix:" then
        target_ip = host
      else
        target_ip, target_port = toip(host, port)
      end
      if not target_ip then
        return nil, "[toip() name lookup failed]: " .. tostring(target_port)
      end

      return old_tcp_connect(sock, target_ip, strip_nils(target_port, sock_opts))
    end

    local function udp_resolve_setpeername(sock, host, port)
      local target_ip, target_port
      if sub(host, 1, 5) == "unix:" then
        target_ip = host
      else
        target_ip, target_port = toip(host, port)
      end
      if not target_ip then
        return nil, "[toip() name lookup failed]: " .. tostring(target_port) -- err
      end

      return old_udp_setpeername(sock, target_ip, strip_nils(target_port))
    end
```

is this fine @Tieske ?

**Comment by rucciva** [comment]
or refactor further?

```lua
  -- need to do the extra check here: https://github.com/openresty/lua-nginx-module/issues/860
    local function strip_nils(port, opts)
      if opts and port then
        return port, opts
      elseif opts then
        return opts
      elseif port then
        return port
      end
    end

    local function resolve_connect(f, sock, host, port, sock_opts)
      local target_ip, target_port
      if sub(host, 1, 5) == "unix:" then
        target_ip = host
      else
        target_ip, target_port = toip(host, port)
      end
      if not target_ip then
        return nil, "[toip() name lookup failed]: " .. tostring(target_port)
      end
      return f(sock, target_ip, strip_nils(target_port, sock_opts))
    end

    local function tcp_resolve_connect(sock, host, port, sock_opts)
      return resolve_connect(old_tcp_connect, sock, host, strip_nils(port, sock_opts))
    end

    local function udp_resolve_setpeername(sock, host, port)
      return resolve_connect(old_udp_setpeername, sock, host, strip_nils(port))
    end
```

**Comment by Tieske** [comment]
@rucciva that's looking great (the last version). Thx. please adjust the PR. I'l comment on the update in line

File: kong/globalpatches.lua [hunk 1]
```diff
@@ -288,35 +288,36 @@ return function(options)
...
-    local function tcp_resolve_connect(sock, host, port, sock_opts)
-      local target_ip, target_port = toip(host, port)
-      if not target_ip then
-        return nil, "[toip() name lookup failed]: " .. tostring(target_port) -- err
+  -- need to do the extra check here: https://github.com/openresty/lua-nginx-module/issues/860
+    local function strip_nils(port, opts)
+      if port and opts then
+        return port, opts
+      elseif opts then
+        return opts
```
Comment (Tieske) [inline kong/globalpatches.lua]: here you are "shifting" a parameter? is that what's intended? So in case of a unix socket, the proper call would be `tcp_connect(sock, name, opts)` instead of `tcp_connect(sock, name, nil, opts)`?

File: kong/globalpatches.lua [hunk 2]
```diff
@@ -288,35 +288,36 @@ return function(options)
...
-
+        target_ip = host
       else
         target_ip, target_port = toip(host, port)
-
-        if not target_ip then
-          return nil, "[toip() name lookup failed]: " .. tostring(target_port) -- err
-        end
       end
+      if not target_ip then
```
Comment (Tieske) [inline kong/globalpatches.lua]: this check can be moved in the `else` block above, since it doesn't apply to unix sockets

File: kong/globalpatches.lua [hunk 3]
```diff
@@ -288,35 +288,36 @@ return function(options)
...
     end
 
-    local function udp_resolve_setpeername(sock, host, port)
+    local function resolve_connect(f, sock, host, port, sock_opts)
       local target_ip, target_port
-
       if sub(host, 1, 5) == "unix:" then
-        target_ip = host -- unix domain socket, so just maintain the named values
-
+        target_ip = host
```
Comment (Tieske) [inline kong/globalpatches.lua]: please do not remove the vertical whitspace, see also [style guide](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#conditional-expressions)

File: kong/globalpatches.lua (hunk 1 above)
Comment (Tieske) [reply kong/globalpatches.lua]: and you are correct, sorry for the noise. https://github.com/openresty/lua-nginx-module#tcpsockconnect

Comment (rucciva) [reply kong/globalpatches.lua]: *Since the function should be compatible with the ngx.socket.tcp calls, in the case of a unix socket, the caller would do connect(sock, name, opts), so in the code, the opts table would ba carried in the port variable actually.*

isn't that what will happens? if the `port` is nil then `strip_nils` will return only the `opts`,
so `return f(sock, target_ip, strip_nils(target_port, sock_opts))` equals `return f(sock, target_ip, sock_opts)` when `target_port` is nil

File: kong/globalpatches.lua (hunk 3 above)
Comment (rucciva) [reply kong/globalpatches.lua]: like this one right?

```lua
    local function resolve_connect(f, sock, host, port, sock_opts)
      local target_ip, target_port
      if sub(host, 1, 5) == "unix:" then
        target_ip = host
        
      else
        target_ip, target_port = toip(host, port)
        if not target_ip then
          return nil, "[toip() name lookup failed]: " .. tostring(target_port)
        end

      end

      return f(sock, target_ip, strip_nils(target_port, sock_opts))
    end
```

**Comment by rucciva** [comment]
btw, the test result are not the same again

screen shot 2018-07-19 at 17 41 24

File: kong/globalpatches.lua (hunk 1 above)
Comment (rucciva) [reply kong/globalpatches.lua]: oh i got what you means, sorry

File: kong/globalpatches.lua (hunk 3 above)
Comment (Tieske) [reply kong/globalpatches.lua]: This is fine, no need for the blank line between the two `end` statements. In general, check the rest of the code.

File: kong/globalpatches.lua (hunk 1 above)
Comment (rucciva) [reply kong/globalpatches.lua]: since the third argument can be port or opts (and will be confusing), can i do it like this?

```lua
    local function strip_nils(first, second)
      if second then
        return first, second
      elseif first then
        return first
      end
    end

    local function resolve_connect(f, sock, host, port_or_opts, opts)
      if sub(host, 1, 5) == "unix:" then
        opts = port_or_opts -- in unix domain socket, third argument are socket options
        return f(sock, host, strip_nils(opts))
      end

      local port = port_or_opts
      local target_ip, target_port = toip(host, port)
      if not target_ip then
        return nil, "[toip() name lookup failed]: " .. tostring(target_port)
      end
      return f(sock, target_ip, strip_nils(target_port, opts))
    end

    local function tcp_resolve_connect(sock, host, port_or_opts, opts)
      return resolve_connect(old_tcp_connect, sock, host, port_or_opts, opts)
    end

    local function udp_resolve_setpeername(sock, host, port)
      return resolve_connect(old_udp_setpeername, sock, host, port)
    end
```

Comment (Tieske) [reply kong/globalpatches.lua]: yes, seems appropriate

File: kong/globalpatches.lua [hunk 4]
```diff
@@ -288,37 +288,37 @@ return function(options)
...
+        return nil, "[toip() name lookup failed]: " .. tostring(target_port)
       end
-
-      -- need to do the extra check here: https://github.com/openresty/lua-nginx-module/issues/860
-      if not sock_opts then
-        return old_tcp_connect(sock, target_ip, target_port)
-      end
-
-      return old_tcp_connect(sock, target_ip, target_port, sock_opts)
+      return f(sock, target_ip, strip_nils(target_port, opts))
```
Comment (Tieske) [inline kong/globalpatches.lua]: the code is correct, but I think you're overdoing the variable naming to explain some intricate details of how the socket functions work, which complicates the code and reduces code readability. Can't we just drop the local variables and stick to:
```lua
    local function resolve_connect(f, sock, host, port, opts)
      if sub(host, 1, 5) ~= "unix:" then
        host, port = toip(host, port)
        if not host then
          return nil, "[toip() name lookup failed]: " .. tostring(port)
        end
      end

      return f(sock, host, strip_nils(port, opts))
    end
```

File: kong/globalpatches.lua [hunk 5]
```diff
@@ -288,37 +288,37 @@ return function(options)
...
-    local function tcp_resolve_connect(sock, host, port, sock_opts)
+    local function strip_nils(first, second)
+      if second then
+        return first, second
+      elseif first then
+        return first
+      end
+    end
+  
+    -- need to do the extra check here: https://github.com/openresty/lua-nginx-module/issues/860
```
Comment (Tieske) [inline kong/globalpatches.lua]: this comment belongs to the function above: `strip_nils`

File: kong/globalpatches.lua (hunk 4 above)
Comment (rucciva) [reply kong/globalpatches.lua]: seems ok for me too. in the end, this is a patch and users might not expect that the original ngx.socket.* are modified by kong, thus they will probably lookup the original ngx lua to find the definition.
