### PR TITLE
fix(db) fix target cleanup and cascade-delete for Targets

### LINKED ISSUE #4317: Cannot delete upstreams on Kong 1.0.2
### Summary

Cannot delete upstreams on Kong 1.0.2

### Steps To Reproduce

1. Create one upstream
2. Create some targets belongs to the  upstream
3. Delete all the targets
4. Delete the upstream will raise error "an existing 'targets' entity references this 'upstreams' entity"

### Additional Details & Logs

- Kong version 1.0.2
- Operating system Debian 4.9.130-2 (2018-10-27) x86_64
- Database cassandra

### PR DESCRIPTION
**Pull request by hishamhm**
This fixes two problems:

1) Target cleanup was happening in the wrong order. This was not a problem for
the target being inserted (because cleanup happened before insertion), but it
would cause the other targets of the list to be corrupted in case they had a
target history themselves.

   Since cleanup happened before insertion (meaning before a weight=0 entry was
inserted upon deletion), this meant that deleting targets never truly emptied
the table -- this meant that Cassandra could not delete upstreams, because the
cascade-delete annotation was missing from the entity schema. Merely adding
`on_delete = "cascade"` to `targets.upstream` would fix the problem in #4317
illustrated by the regression test added to
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua but would not
fix the other problem, illustrated by the test added to
spec/02-integration/04-admin_api/08-targets_routes_spec.lua.

2) We also add `on_cascade = "delete"` to the schema, which fixes the inconsistency in behavior between Postgres and Cassandra, as the former included cascade-delete in its migration already.

Fixes #4317.

### CODE REVIEW

File: kong/db/dao/targets.lua [hunk 1]
```diff
@@ -111,7 +115,7 @@ function _TARGETS:delete(pk)
     return nil, err, err_t
   end
 
-  return self:insert({
+  self:insert({
```
Comment (bungle) [inline kong/db/dao/targets.lua]: Should we handle possible errors in this case?

**Comment by hishamhm** [comment]
totally! that was an editing mistake. good catch, thanks!

File: kong/db/dao/targets.lua (hunk 1 above)
Comment (hishamhm) [reply kong/db/dao/targets.lua]: fixed!
