### PR TITLE
fix(cli) no stack trace when running migration up while having pending migrations

### LINKED ISSUE #6105: Kong migrations when executed twice gives minor stacktrace by design
### Summary

Running ```kong migrations up``` multiple times (accidentally we did last night, obviously not a big deal but wasn't sure if yall intended a stack trace or just a print statement).

The error makes sense, but was a stack-trace output intended as opposed to just a [error] log statement? Was thinking expected behavior like:

```
2020/07/10 04:07:20 [error] Database has pending migrations; run 'kong migrations finish'
```

But the error output is like this:

```
2020/07/10 04:07:20 [debug] resolved Cassandra contact point 'serverxyz' to: 10.207.150.109
Error: 
...ong/luarocks/share/lua/5.1/kong/cmd/utils/migrations.lua:108: [Cassandra error] cluster_mutex callback threw an error: ...ong/luarocks/share/lua/5.1/kong/cmd/utils/migrations.lua:67: Database has pending migrations; run 'kong migrations finish'
stack traceback:
	[C]: in function 'error'
	...ong/luarocks/share/lua/5.1/kong/cmd/utils/migrations.lua:67: in function <...ong/luarocks/share/lua/5.1/kong/cmd/utils/migrations.lua:63>
	[C]: in function 'xpcall'
	/usr/local/kong/luarocks/share/lua/5.1/kong/db/init.lua:358: in function </usr/local/kong/luarocks/share/lua/5.1/kong/db/init.lua:308>
	[C]: in function 'pcall'
	/usr/local/kong/luarocks/share/lua/5.1/kong/concurrency.lua:45: in function 'cluster_mutex'
	...ong/luarocks/share/lua/5.1/kong/cmd/utils/migrations.lua:63: in function 'up'
	...ocal/kong/luarocks/share/lua/5.1/kong/cmd/migrations.lua:172: in function 'cmd_exec'
	/usr/local/kong/luarocks/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/kong/luarocks/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/kong/luarocks/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/kong/luarocks/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:48: in function <init_worker_by_lua:46>
	[C]: in function 'xpcall'
	init_worker_by_lua:55: in function <init_worker_by_lua:53>
stack traceback:
	[C]: in function 'error'
	...ong/luarocks/share/lua/5.1/kong/cmd/utils/migrations.lua:108: in function 'up'
	...ocal/kong/luarocks/share/lua/5.1/kong/cmd/migrations.lua:172: in function 'cmd_exec'
	/usr/local/kong/luarocks/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/kong/luarocks/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/kong/luarocks/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/kong/luarocks/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:48: in function <init_worker_by_lua:46>
	[C]: in function 'xpcall'
	init_worker_by_lua:55: in function <init_worker_by_lua:53>
2020/07/10 04:07:20 [debug] loading subsystems migrations...
2020/07/10 04:07:20 [verbose] retrieving keyspace schema state...
2020/07/10 04:07:20 [verbose] schema state retrieved
2020/07/10 04:07:20 [debug] loading subsystems migrations...
2020/07/10 04:07:20 [verbose] retrieving keyspace schema state...
2020/07/10 04:07:21 [verbose] schema state retrieved
```

If this is intentional we can close this, I wasn't sure.

### Additional Details & Logs

- Kong version 2.0.5

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Fixes issue reported in #6105 by @jeremyjpj0916.

Before this commit:
```
$ kong migrations up
Error: [PostgreSQL error] cluster_mutex callback threw an error: kong/cmd/utils/migrations.lua:67: Database has pending migrations; run 'kong migrations finish'
stack traceback:
	[C]: in function 'error'
	kong/cmd/utils/migrations.lua:67: in function <kong/cmd/utils/migrations.lua:63>
	[C]: in function 'xpcall'
	kong/db/init.lua:364: in function <kong/db/init.lua:314>
	[C]: in function 'pcall'
	kong/concurrency.lua:45: in function 'cluster_mutex'
	kong/cmd/utils/migrations.lua:63: in function 'up'
	kong/cmd/migrations.lua:177: in function 'cmd_exec'
	kong/cmd/init.lua:88: in function <kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	kong/cmd/init.lua:88: in function <kong/cmd/init.lua:45>
	bin/kong:9: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

  Run with --v (verbose) or --vv (debug) for more details
```

After this commit:
```
$ kong migrations up
Error: Database has pending migrations; run 'kong migrations finish'

  Run with --v (verbose) or --vv (debug) for more details
```

### Issues Resolved

Fix #6105

### CODE REVIEW

File: kong/cmd/utils/migrations.lua [hunk 1]
```diff
@@ -60,6 +60,10 @@ local function up(schema_state, db, opts)
     error("Cannot run migrations: " .. NEEDS_BOOTSTRAP_MSG)
   end
 
+  if not opts.force and schema_state.pending_migrations then
+    error("Database has pending migrations; run 'kong migrations finish'")
+  end
```
Comment (thibaultcha) [inline kong/cmd/utils/migrations.lua:65]: Why changing the below `error` call to `log`, like all other logs written from the cluster mutex?

Comment (bungle) [reply kong/cmd/utils/migrations.lua:65]: @thibaultcha, it will change the status code then too that cli returns. I think that would be breaking.

Comment (thibaultcha) [reply kong/cmd/utils/migrations.lua:65]: Ok - should it be removed then? They just seem redundant so the diff looked incomplete to me, that's all!

Comment (bungle) [reply kong/cmd/utils/migrations.lua:65]: The repetitive test is there because the test I added here is ran without a lock. So there is tiny change that the first check passes while the second will fail after waiting for the mutex. The one inside the mutex will still result stack trace. We can also gather that to `err_without_stack` and then throw the `err_without_stack` after returning from the code running inside mutex. But that looked so strange, so I just copied the check. This will be ok for 99,999% of the time (people should never hit the one inside a mutex, but there is a small change). The errors raised inside the mutex contain stack trace. That is deeper and I didn't want to make change there (e.g. a new option to not add stacktrace).

Comment (dndx) [reply kong/cmd/utils/migrations.lua:65]: What about:

`lapp.quit("Database has pending migrations; run 'kong migrations finish", true)`? That way it will not be breaking and we avoid duplicating the checks just for cosmetic reasons (also it is slightly more robust and easier to understand).

Comment (bungle) [reply kong/cmd/utils/migrations.lua:65]: @dndx, whenever we do `quit` we do not release mutex then.

Comment (dndx) [reply kong/cmd/utils/migrations.lua:65]: Okay, if that is the case I guess this is the most reasonable fix we can do given the current implementation, I will be okay to merge this for now, and if we have a better way of propagating the error we can always change it in the future.

Can we add some comment before this change just so that future maintainers won't scratch their head figuring out why a double check was needed?

**Review by dndx — APPROVED** [review]
