### PR TITLE
fix(acl) get acl by group fails when more consumers share the same group

### LINKED ISSUE #5280: Get ACL by group fails when more consumers share the same group
### Summary

Since this commit (5f0ab5d106a6b246bc0f7fc24296291c03e4596e) the retrieving of an ACL by the group name fails for all consumers but one when there is more than one consumer with the same group. This happens because the consumer_id is not used in the db query and only the first of the acl with that group name is returned (always the same acl for all consumers)

### Steps To Reproduce

1. `http POST /consumers username=alice` [200]
2. `http POST /consumers username=bob` [200]
3. `http POST /consumers/alice/acls group=foo` [200]
4. `http POST /consumers/bob/acls group=foo` [200]
5. `http GET /consumers/alice/acls/foo` [200]
5. `http GET /consumers/bob/acls/foo` **[404]**

### Additional Details & Logs

I have this issue with kong 1.0.3 but looking at the code I think it is present also in master.
If you want I can submit a pull request with the updated spec test file showing the issue but I don't know how to fix it, I think `kong.api.endpoints` should be extended. I can try if someone can indicate me the right direction.

### PR DESCRIPTION
**Pull request by bungle**
### Summary

@albertored reported issue here #5280.

This PR removes `endpoint_key` from `acls` dao, as it is not `unique`,
and using non-unique endpoint keys leads to strange results.

And of course it fixes the issue reported:

```
http POST :8001/consumers username=alice
http POST :8001/consumers username=bob
http POST :8001/consumers/alice/acls group=foo
http POST :8001/consumers/bob/acls group=foo
http GET :8001/consumers/alice/acls/foo
http GET :8001/consumers/bob/acls/foo
```

All returning `200`/`201` as expected.

### Issues Resolved

Fix #5280

### CODE REVIEW

File: spec/03-plugins/18-acl/01-api_spec.lua [hunk 1]
```diff
@@ -152,10 +153,114 @@ for _, strategy in helpers.each_strategy() do
...
+          local res  = assert(admin_client:post("/consumers", {
+            body = {
+              username = "anna",
+            },
+            headers = {
+              ["Content-Type"] = "application/json",
+            },
+          }))
+          local body = assert.res_status(201, res)
+          local _    = cjson.decode(body)
```
Comment (kikito) [inline spec/03-plugins/18-acl/01-api_spec.lua]: I think using the following assertion is more explicit, and produces a slightly better error message if something goes wrong:

```suggestion
          assert.response(res).has.jsonbody()
```

The assertion also returns the decoded json table, so it could be used to replace the calls to `cjson.decode` where they are assigned to a named variable too, if you so desired. This is an aesthetic choice and I don't particularly care about that.

File: spec/03-plugins/18-acl/01-api_spec.lua [hunk 2]
```diff
@@ -152,10 +153,114 @@ for _, strategy in helpers.each_strategy() do
...
+          local res  = assert(admin_client:post("/consumers", {
+            body = {
+              username = "jack",
+            },
+            headers = {
+              ["Content-Type"] = "application/json",
+            },
+          }))
+          local body = assert.res_status(201, res)
+          local _    = cjson.decode(body)
```
Comment (kikito) [inline spec/03-plugins/18-acl/01-api_spec.lua]:
```suggestion
          assert.response(res).has.jsonbody()
```

File: spec/03-plugins/18-acl/01-api_spec.lua [hunk 3]
```diff
@@ -152,10 +153,114 @@ for _, strategy in helpers.each_strategy() do
...
+          local res  = assert(admin_client:delete("/consumers/anna"))
+          local _    = assert.res_status(204, res)
+
+          local res  = assert(admin_client:delete("/consumers/jack"))
+          local _    = assert.res_status(204, res)
+        end)
+        it("retrieves right ACL by group when multiple consumers share the same group name created with PUT", function()
+          local res  = assert(admin_client:put("/consumers/anna"))
+          local body = assert.res_status(200, res)
+          local _    = cjson.decode(body)
```
Comment (kikito) [inline spec/03-plugins/18-acl/01-api_spec.lua]:
```suggestion
          assert.response(res).has.jsonbody()
```

File: spec/03-plugins/18-acl/01-api_spec.lua [hunk 4]
```diff
@@ -152,10 +153,114 @@ for _, strategy in helpers.each_strategy() do
...
+
+          local res  = assert(admin_client:put("/consumers/jack"))
+          local body = assert.res_status(200, res)
+          local _    = cjson.decode(body)
```
Comment (kikito) [inline spec/03-plugins/18-acl/01-api_spec.lua]:
```suggestion
          assert.response(res).has.jsonbody()
```

File: spec/03-plugins/18-acl/01-api_spec.lua [hunk 5]
```diff
@@ -152,10 +153,114 @@ for _, strategy in helpers.each_strategy() do
...
+
+          assert.same(ag, ag2)
+          assert.same(jg, jg2)
+          assert.not_same(jg, ag)
+          assert.not_same(jg2, ag2)
+          assert.not_same(jg, ag2)
+          assert.not_same(jg2, ag)
+
+          local res  = assert(admin_client:delete("/consumers/anna"))
+          local _    = assert.res_status(204, res)
```
Comment (kikito) [inline spec/03-plugins/18-acl/01-api_spec.lua]: I think assigning this to the unnamed variable serves no purpose.

```suggestion
          assert.res_status(204, res)
```

File: spec/03-plugins/18-acl/01-api_spec.lua [hunk 6]
```diff
@@ -152,10 +153,114 @@ for _, strategy in helpers.each_strategy() do
...
+
+          local res  = assert(admin_client:delete("/consumers/jack"))
+          local _    = assert.res_status(204, res)
```
Comment (kikito) [inline spec/03-plugins/18-acl/01-api_spec.lua]:
```suggestion
          assert.res_status(204, res)
```

File: spec/03-plugins/18-acl/01-api_spec.lua [hunk 7]
```diff
@@ -152,10 +153,114 @@ for _, strategy in helpers.each_strategy() do
           res = assert(admin_client:get("/consumers/alice/acls/" .. acl.group))
           assert.res_status(404, res)
         end)
+        it("retrieves right ACL by group when multiple consumers share the same group name created with POST", function()
+          local res  = assert(admin_client:post("/consumers", {
```
Comment (kikito) [inline spec/03-plugins/18-acl/01-api_spec.lua]: All the "shortcut request methods" (`admin_client:post`, `admin_client:delete`, `admin_client:get`, etc) already do an `assert`, so wrapping them with an `assert` is not really needed.
