### PR TITLE
fix(balancer) use local target cache

### LINKED ISSUE #8517: One or some workers in one of 14 kong nodes still use the old cache after the kong api is updated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 0.12.3

### Current Behavior

There are 14 kong nodes in our apigateway cluster which uses PostgreSQL as db. Each kong node runs 4 nginx workers. All TTL configs remain default.

#db_update_frequency = 5 
#db_update_propagation = 0 
#db_cache_ttl = 3600

We added a new custom plugin to an existed kong api. After testing with some http requests, we found that some requests routed by one kong node didn't execute the new plugin. Then we login that kong node and curl 127.0.0.1 with host to force the requests going through that kong api and node. Finally, some requests executed the plugin and some didn't. We suspect one or several nginx workers still use the old cache.
After 8 hours, the issue still existed. But after reloading nginx process, everything works well.

### Expected Behavior

The newly added plugin should be propagated to all kong nodes and all workers.

### Steps To Reproduce

```markdown
The issue happens rarely.
```

### Anything else?

We found following logs after the plugin was added to an existed kong api.
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 314, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 315, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 316, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 317, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 318, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 319, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 320, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 321, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 322, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 323, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 324, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 325, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 326, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 327, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 328, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 329, context: ngx.timer
2022/03/07 03:02:40 [error] 30#30: *7171374869 [lua] events.lua:103: errlog(): worker-events: dropping event; waiting for event data timed out, id: 330, context: ngx.timer

### LINKED ISSUE #10020: One worker not update address list of balancer after target removed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.2.2

### Current Behavior

I use kong for k8s ingress, with db deployment method, But controller deployment standalone. And a k8s service admin_url is used. 
image
> I don't know if this issue is related to to my deployment method, so I also ask a question at kic: https://github.com/Kong/kubernetes-ingress-controller/issues/3308

I found one time when I update my app's deployment, a old app pod which was deleted by k8s was still in the `address list` of balancer on one kong pod worker, while another worker of this kong pod(one kong pod two nginx worker) and other kong pod's worker was ok. I affirmed that app pod was removed from kong's PG.

### Expected Behavior

That app pod  was deleted should remove from `address list` of the balancer.

### Steps To Reproduce

```markdown
I can't reproduce it.
```

### Anything else?

No any error log about target event handle found.

### PR DESCRIPTION
**Pull request by locao**
### Summary

The target's global cache was caching more data than it should: it kept data retrieved from the database and DNS name resolution, which has its own cache.

As a result, when config reloads were done, some processes were skipped (such as setting the upstream as healthy) because the load-balancer never identified the data as new if it was the same as cached (highly probable with DNS name resolution).

This change makes the target cache local to the worker. 

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* Make the target cache local to the worker.
* This PR has no tests. This is a race condition, almost impossible to automate. 

### Issue reference

FTI-3172
Fix #8517
Fix #10020

### CODE REVIEW

File: kong/runloop/balancer/targets.lua [hunk 1]
```diff
@@ -157,7 +167,14 @@ function targets_M.on_target_event(operation, target)
...
 
-  kong.core_cache:invalidate_local("balancer:targets:" .. upstream_id)
+  targets_by_upstream_id["balancer:targets:" .. upstream_id] = nil
+
+  local upstream = upstreams.get_upstream_by_id(upstream_id)
+  if not upstream then
+    log(ERR, "target ", operation, ": upstream not found for ", upstream_id,
+      upstream_name and " (" .. upstream_name ..")" or "")
+    return
+  end
```
Comment (samugi) [inline kong/runloop/balancer/targets.lua:177]: This code appears to be a duplicate of [this block below](https://github.com/Kong/kong/blob/0b0fb6a0615adb9d5a04cd388b64b559c4ff3e5b/kong/runloop/balancer/targets.lua#L190-L195). Can the latter be removed?

Comment (locao) [reply kong/runloop/balancer/targets.lua:177]: 🤦 
I missed that when resolving the cherry-pick conflict. Thank you!

**Review by samugi — APPROVED** [review]
