### PR TITLE
fix(cors) properly validate flat strings

### LINKED ISSUE #3832: Cors plugin doesn't validate "flat strings" appropriately
### Summary

The Cors plugin states you can provide "flat strings or PCRE regexes" for the `config.origins` value.  However, flat string origins are not validated safely.

From what I can tell flat strings are evaluated with `re_find()` (see [here](https://github.com/Kong/kong/blob/acdd89d1ebb2d804913bd204ba6efc4fda351bbd/kong/plugins/cors/handler.lua#L54)). Since there are no line start/end (`^`, `$`) symbols surrounding the flat string, as long as an origin starts with the same characters it will be validated.

### Steps To Reproduce

1. Setup an clean Kong environment. I'm using Docker with `kong:0.13.0-alpine` and `postgres:10.1-alpine`, but I believe this bug exists in all versions of the plugin (see `re_find()` link above).
2. Setup the Cors plugin like this:
```
curl -X POST \
  http://localhost:8001/plugins \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "cors",
    "config": {
      "origins": [
        "http://my-site.com",
        "http://my-other-site.com"
      ]
    }
  }'
```
3. Ping the Proxy with **your legitimate** origin and confirm **you do** get the `Access-Control-Allow-Origin` response header ✅ 
```
curl -X OPTIONS \
  http://localhost:8000 \
  -H 'Origin: http://my-site.com' 
```
4. Ping the Proxy with a **clearly illegitimate** origin and confirm **you do not** get the `Access-Control-Allow-Origin` response header ✅ 
```
curl -X OPTIONS \
  http://localhost:8000 \
  -H 'Origin: http://bad-guys.com' 
```
5. Ping the Proxy with a **tricky illegitimate** origin and confirm **you do not** get the `Access-Control-Allow-Origin` response header 😞 
```
curl -X OPTIONS \
  http://localhost:8000 \
  -H 'Origin: http://my-site.com.bad-guys.com' 
```

### PR DESCRIPTION
**Pull request by subnetmarco**
Closes #3832.

This pull request changes the behavior of the CORS plugin as follows:

* Forces a full string validation to avoid the issue in #3832 
* When a both valid and matched domain is processed, returns an `Access-Control-Allow-Origin` header value that equals the string sent by the client in the original `Origin` value
* Validates that the scheme, host and port also match the `Origin` value as per [RFC6454 Section 5](https://tools.ietf.org/html/rfc6454#section-5)

These changes seem reasonable to me, but happy to hear feedback.

### CODE REVIEW

File: kong/plugins/cors/handler.lua [hunk 1]
```diff
@@ -50,8 +50,11 @@ local function configure_origin(ngx, conf)
 
   local req_origin = ngx.var.http_origin
   if req_origin then
+
+    local parsed_req_origin = url.parse(req_origin).host or req_origin
+
     for _, domain in ipairs(conf.origins) do
-      local from, _, err = re_find(req_origin, domain, "jo")
+      local from, _, err = re_find(parsed_req_origin, "^"..(url.parse(domain).host or domain).."$", "jo")
```
Comment (p0pr0ck5) [inline kong/plugins/cors/handler.lua]: Can we cache the value of url.parse here?

File: kong/plugins/cors/handler.lua [hunk 2]
```diff
@@ -16,6 +16,9 @@ CorsHandler.PRIORITY = 2000
 CorsHandler.VERSION = "0.1.0"
 
 
+local parsed_domains = { }
```
Comment (subnetmarco) [inline kong/plugins/cors/handler.lua]: Not sure if putting this variable here is the intended style.

File: kong/plugins/cors/handler.lua [hunk 3]
```diff
@@ -16,6 +17,11 @@ CorsHandler.PRIORITY = 2000
 CorsHandler.VERSION = "0.1.0"
 
 
+-- per-worker cache of parsed origins
+local CACHE_SIZE = 10 ^ 4
```
Comment (subnetmarco) [inline kong/plugins/cors/handler.lua]: Will store at `10000` origins values at a time, seems reasonable.

File: kong/plugins/cors/handler.lua [hunk 4]
```diff
@@ -50,8 +56,25 @@ local function configure_origin(ngx, conf)
 
   local req_origin = ngx.var.http_origin
   if req_origin then
+
+    local parsed_req_origin_obj = url.parse(req_origin)
+    local parsed_req_origin = parsed_req_origin_obj and parsed_req_origin_obj.host
```
Comment (thibaultcha) [inline kong/plugins/cors/handler.lua]: [RFC 6454](https://tools.ietf.org/html/rfc6454#page-11) says on "Comparing Origins" that:

>  Two origins are "the same" if, and only if, they are identical.  In
   particular: 
> If the two origins are scheme/host/port triples, the two origins
      are the same if, and only if, they have identical schemes, hosts,
      and ports.

Also see:

>  Q: Why not just use the host?
>   A: Including the scheme in the origin tuple is essential for
   security.  If user agents did not include the scheme, there would be
   no isolation between http://example.com and https://example.com
   because the two have the same host.  However, without this isolation,
   an active network attacker could corrupt content retrieved from
   http://example.com and have that content instruct the user agent to
   compromise the confidentiality and integrity of content retrieved
   from https://example.com, bypassing the protections afforded by TLS
   [RFC5246].

The comparisons we are doing now do not take scheme and port into consideration (nor do we have tests asserting them). See section 3.2.1 of RFC 6454 for examples of resources with similar and different origins, we could use this list to write our tests.

**Comment by thibaultcha** [comment]
I have added a commit to this PR. Should be good to go now, but waiting for any additional review just in case. Will be merged for 1.0rc4.
