### PR TITLE
Save context tables for the Go log phase timer.

### LINKED ISSUE #6426: [plugin]: go-plugin can't get kong.ctx.shared set by lua
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce
lua plugin at `body_filter` phase:
```lua
local function status()
        local s = kong.response.get_status()
        kong.ctx.shared.status = s
end
```
go plugin at `log` phase:
```go
func (conf Config) Log(kong *pdk.PDK) {

        status, err := kong.Ctx.GetSharedInt("status")
        if err!= nil {
                kong.Log.Err(err.Error())
        }
       ....
}
```
got error : `null response`

### Additional Details & Logs

- Kong version (`2.1.3`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

### PR DESCRIPTION
**Pull request by javierguerragiraldez**
Once again, having Go log phase run in a timer means less access to
request-relative information.

This patch stores `ngx.ctx` and `kong.ctx.shared` tables, prolonging
their lifetimes until timer execution time.  Note: these _must_ be
removed before finishing the timer, or it would create a memory leak.

### Issues resolved

Fix #6426 
Replace #6430

### CODE REVIEW

File: spec/fixtures/go/go-hello.go [hunk 1]
```diff
@@ -27,4 +27,27 @@ func (conf Config) Access(kong *pdk.PDK) {
 		message = "hello"
 	}
 	kong.Response.SetHeader("x-hello-from-go", fmt.Sprintf("Go says %s to %s", message, host))
+	kong.Ctx.SetShared("shared_msg", message)
+}
+
+func (conf Config) Log(kong *pdk.PDK) {
+    access_start, err := kong.Nginx.GetCtxFloat("KONG_ACCESS_START")
```
Comment (kikito) [inline spec/fixtures/go/go-hello.go:34]: Indentation on this function seem incorrect (four spaces instead of tabs)

**Review by kikito — CHANGES_REQUESTED** [review]

File: spec/fixtures/go/go-hello.go (hunk 1 above)
Comment (javierguerragiraldez) [reply spec/fixtures/go/go-hello.go]: :facepalm:

**Review by dndx — APPROVED** [review]
LGTM. @kikito mind taking another look and ✅ as well?
