### PR TITLE
tests(dns): add a test case to cover dns resolution in stream subsystem

### LINKED ISSUE #11896: DNS resolution failed in stream subsystem
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

When the host of the tcp service is a domain (like 'smtp.exmail.qq.com'), kong has error log :

`2023/10/31 22:51:18 [error] 65#0: *42425 stream [lua] balancer.lua:1038: execute(): DNS resolution failed: dns client error: 101 empty record received. Tried: ["(short)smtp.exmail.qq.com:(na) - cache-miss","smtp.exmail.qq.com:5 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.gateway-2b2d55ba.svc.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.svc.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.gateway-2b2d55ba.svc.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.svc.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com:1 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.gateway-2b2d55ba.svc.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.svc.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received"] while prereading client data, client: 119.147.10.194, server: 0.0.0.0:8000
2023/10/31 22:51:18 [error] 65#0: *42425 [kong] response.lua:869 unable to proxy stream connection, status: 503, err: {"message":"name resolution failed"} while prereading client data, client: 119.147.10.194, server: 0.0.0.0:8000`

I confirm Kong pod can resolve `smtp.exmail.qq.com`:

```
[root@group-07627f42-kong-0 logs]# ping smtp.exmail.qq.com
PING smtp-v6.exmail.qq.com (157.255.202.11) 56(84) bytes of data.
64 bytes from 157.255.202.11 (157.255.202.11): icmp_seq=1 ttl=50 time=42.7 ms
64 bytes from 157.255.202.11 (157.255.202.11): icmp_seq=2 ttl=50 time=42.8 ms
64 bytes from 157.255.202.11 (157.255.202.11): icmp_seq=3 ttl=50 time=42.8 ms
```

Is this as expected? Does the tcp service not support domain names?

### Expected Behavior

The tcp service of the domain name can be accessed normally

### Steps To Reproduce

1. create a route :
`{
            "strip_path":true,
            "id":"eabb6363-073f-4376-8113-e0e6cf9b31f7",
            "snis":null,
            "service":{
                "id":"5d0e9e44-7102-4470-9cca-bc5d18789d7d"
            },
            "tags":null,
            "hosts":null,
            "request_buffering":true,
            "response_buffering":true,
            "path_handling":"v1",
            "https_redirect_status_code":426,
            "created_at":1698760609,
            "updated_at":1698760900,
            "headers":null,
            "preserve_host":false,
            "protocols":[
                "tcp"
            ],
            "paths":null,
            "methods":null,
            "sources":null,
            "destinations":[
                {
                    "port":8000,
                    "ip":"0.0.0.0/0"
                }
            ],
            "regex_priority":0,
            "name":"qq"
        }`

2. create a service
        `{
            "host":"smtp.exmail.qq.com",
            "id":"5d0e9e44-7102-4470-9cca-bc5d18789d7d",
            "name":"qq",
            "retries":5,
            "tags":[
            ],
            "ca_certificates":null,
            "port":465,
            "client_certificate":null,
            "created_at":1698760539,
            "updated_at":1698760539,
            "connect_timeout":60000,
            "tls_verify":null,
            "read_timeout":60000,
            "path":null,
            "tls_verify_depth":null,
            "protocol":"tcp",
            "write_timeout":60000
        }
`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tzssangglass**
### Summary

just make sure dns resolve can run normally in the stream subsystem
 

### Checklist

- [x] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #11896

### CODE REVIEW

File: spec/02-integration/05-proxy/05-dns_spec.lua [hunk 1]
```diff
@@ -206,5 +206,64 @@ for _, strategy in helpers.each_strategy() do
...
+      end)
+
+      it("resolve domain name", function()
+        local tcp = ngx.socket.tcp()
+        assert(tcp:connect(helpers.get_proxy_ip(false), 19000))
+        local MESSAGE = "echo, ping, pong. echo, ping, pong. echo, ping, pong.\n"
+        assert(tcp:send(MESSAGE))
+        local body = assert(tcp:receive("*a"))
+        assert.equal(MESSAGE, body)
+        tcp:close()
```
Comment (nowNick) [inline spec/02-integration/05-proxy/05-dns_spec.lua:265]: I wonder what will happen if an assertion fails and the code does not reach this line. The [documentation](https://github.com/openresty/lua-nginx-module#tcpsockclose) suggests that:
> Socket objects that have not invoked this method (and associated connections) will be closed when the socket object is released by the Lua GC (Garbage Collector) or the current client HTTP request finishes processing.

So I think theoretically we should be fine. There's still potential for improper resource handling which might introduce flakiness but a lot of things have to go wrong for it to occur (i.e. the test would need to fail, GC would need to run late enough for the sockets to get exhausted... and then some other tests might fail).

**Review by nowNick — APPROVED** [review]
Looks good! Awesome that we're improving our code coverage 🚀

File: spec/02-integration/05-proxy/05-dns_spec.lua (hunk 1 above)
Comment (hanshuebner) [reply spec/02-integration/05-proxy/05-dns_spec.lua:265]: We must rely on the GC to work properly.  There is no need to complicate the test code to cover for the unlikely case that the assertion (and thus the test) fails.

**Review by hanshuebner — APPROVED** [review]

**Comment by tzssangglass** [comment]
need to backport ee, leave a reminder for myself.
