### PR TITLE
fix(core): definition of cookie name validate

### LINKED ISSUE #11860: Cookie Name validation too strict
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4.1.1-enterprise-edition

### Current Behavior

I'm trying to configure an upstream with:

```yaml
hash_on: cookie
hash_on_cookie: ASP.NET_SessionId
```

But that fails because the [Cookie Name validation](https://github.com/Kong/kong/blob/f59e36b554b6071a9213deea6947eb804dd7a6f6/kong/tools/utils.lua#L808-L824) only allows `A-Z, a-z, 0-9, '_', and '-'` characters in the Cookie Name.

But per [RFC-6265](https://httpwg.org/specs/rfc6265.html#sane-set-cookie-syntax) a `.` is a valid character to be used in a Cookie Name.

### Expected Behavior

Kong will allow configuring valid Cookie Names as defined in [RFC-6265](https://httpwg.org/specs/rfc6265.html#sane-set-cookie-syntax).

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by StarlightIbuki**
### Summary

We have a too strong limitation on the character used in cookie names. For example "." should be allowed.

We choose not to do the same to the header because we rely on Nginx's API to handle headers, which has more strict restrictions on the characters.

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)

### Full changelog

* [Implement ...]

### Issue reference

Fix #11860

### CODE REVIEW

**Comment by bungle** [comment]
This regex looks simpler:
https://github.com/guzzle/guzzle/blob/7.9/src/Cookie/SetCookie.php#L464

@StarlightIbuki what do you think?

**Comment by StarlightIbuki** [comment]
> This regex looks simpler (and whitelist feels safer than blacklist): [guzzle/guzzle@`7.9`/src/Cookie/SetCookie.php#L464](https://github.com/guzzle/guzzle/blob/7.9/src/Cookie/SetCookie.php?rgh-link-date=2023-10-30T08%3A28%3A05Z#L464)
> 
> @StarlightIbuki what do you think?

Applied the change.

File: kong/tools/utils.lua [hunk 1]
```diff
@@ -783,6 +783,29 @@ _M.format_host = function(p1, p2)
...
+    end
+
+    if re_match(token, HTTP_TOKEN_SCHEMA, 'jo') then
+      return token
+    end
+
+    return nil, "bad " .. (purpose or "token") .. " '" .. token ..
+              "'. Must not contain invalid characters: ASCII " ..
+              "control characters (0-31;127), space, tab and the " ..
+              "following characters: ()<>@,;:\"/?={}[]. Please refer to RFC 2616"
```
Comment (fffonion) [inline kong/tools/utils.lua:804]: this doesn't seem to match the regex

File: kong/tools/utils.lua [hunk 2]
```diff
@@ -801,23 +826,13 @@ _M.validate_header_name = function(name)
               "', allowed characters are A-Z, a-z, 0-9, '_', and '-'"
 end
 
+-- should we also use validate_http_token for this?
 --- Validates a cookie name.
 -- Checks characters used in a cookie name to be valid
 -- a-z, A-Z, 0-9, '_' and '-' are allowed.
 -- @param name (string) the cookie name to verify
 -- @return the valid cookie name, or `nil+error`
```
Comment (fffonion) [inline kong/tools/utils.lua:834]:
```suggestion
--- Validates a cookie name.
-- @param name (string) the cookie name to verify
-- @return the valid cookie name, or `nil+error`
```

File: kong/tools/utils.lua [hunk 3]
```diff
@@ -783,6 +783,31 @@ _M.format_host = function(p1, p2)
...
+-- @return the valid token, or `nil+error`
+function _M.validate_http_token(purpose)
+  return function(token)
+    if token == nil or token == "" then
+      return nil, "no token provided"
+    end
+
+    if not re_match(token, HTTP_TOKEN_FROBID_PATTERN, "jo") then
+      return token
+    end
```
Comment (fffonion) [inline kong/tools/utils.lua:802]:
```suggestion

    end
```

File: kong/db/schema/typedefs.lua [hunk 4]
```diff
@@ -331,6 +331,21 @@ typedefs.url = Schema.define {
   description = "A string representing a URL, such as https://example.com/path/to/resource?q=search."
 }
 
+
+typedefs.http_token = Schema.define {
+  type = "string",
+  custom_validator = utils.validate_http_token(),
+  description = "A string representing an HTTP token defined by RFC 2616."
+}
```
Comment (fffonion) [inline kong/db/schema/typedefs.lua:339]: this seems not used

File: kong/tools/utils.lua (hunk 3 above)
Comment (StarlightIbuki) [inline kong/tools/utils.lua:802]:
```suggestion
    end

```

File: kong/db/schema/typedefs.lua [hunk 5]
```diff
@@ -331,6 +331,21 @@ typedefs.url = Schema.define {
...
+
```
Comment (StarlightIbuki) [inline kong/db/schema/typedefs.lua:340]:
```suggestion
```

File: kong/tools/utils.lua [hunk 6]
```diff
@@ -783,6 +783,29 @@ _M.format_host = function(p1, p2)
   end
 end
 
+local CONTROLS = [[\x00-\x1F\x7F]]
+local HIGHBIT = [[\x80-\xFF]]
+local SEPARATORS = [==[ \t()<>@,;:\\\"\/?={}\[\]]==]
+local HTTP_TOKEN_FROBID_PATTERN = "[".. CONTROLS .. HIGHBIT .. SEPARATORS .. "]"
```
Comment (hanshuebner) [inline kong/tools/utils.lua:789]:
```suggestion
local HTTP_TOKEN_FORBID_PATTERN = "[".. CONTROLS .. HIGHBIT .. SEPARATORS .. "]"
```
Also references need to be fixed.

File: kong/tools/utils.lua [hunk 7]
```diff
@@ -783,6 +783,29 @@ _M.format_host = function(p1, p2)
...
+    return nil, "no token provided"
+  end
+
+  if not re_match(token, HTTP_TOKEN_FROBID_PATTERN, "jo") then
+    return token
+  end
+
+  return nil, "must not contain invalid characters: ASCII " ..
+              "control characters (0-31;127), space, tab and the " ..
+              "following characters: ()<>@,;:\\\"/?={}[]"
```
Comment (hanshuebner) [inline kong/tools/utils.lua:805]:
```suggestion
  return nil, "contains one or more invalid characters. ASCII " ..
              "control characters (0-31;127), space, tab and the " ..
              "characters ()<>@,;:\\\"/?={}[] are not allowed."
```

**Review by hanshuebner — CHANGES_REQUESTED** [review]
Typo, otherwise looks good to me.

**Comment by bungle** [comment]
> Applied the change. And notice the code you refer to also uses a blacklist.

Ah, damn, you are right. I read it wrong.

File: kong/tools/utils.lua [hunk 8]
```diff
@@ -783,6 +783,29 @@ _M.format_host = function(p1, p2)
...
+
+--- Validates a token defined by RFC 2616.
+-- @param token (string) the string to verify
+-- @return the valid token, or `nil+error`
+function _M.validate_http_token(token)
+  if token == nil or token == "" then
+    return nil, "no token provided"
+  end
+
+  if not re_match(token, HTTP_TOKEN_FROBID_PATTERN, "jo") then
```
Comment (StarlightIbuki) [inline kong/tools/utils.lua:799]:
```suggestion
  if not re_match(token, HTTP_TOKEN_FORBID_PATTERN, "jo") then
```

File: kong/db/schema/typedefs.lua [hunk 9]
```diff
@@ -331,6 +331,14 @@ typedefs.url = Schema.define {
   description = "A string representing a URL, such as https://example.com/path/to/resource?q=search."
 }
 
+
+typedefs.cookie_name = Schema.define {
+  type = "string",
+  custom_validator = utils.validate_cookie_name,
```
Comment (kikito) [inline kong/db/schema/typedefs.lua:337]: If the function is only used here, please remove it from utils and into typedefs.lua

Comment (StarlightIbuki) [reply kong/db/schema/typedefs.lua:337]: It's unit-tested so it needs to be exported. Also before the patch, this function was already exported and in the util module.

**Comment by StarlightIbuki** [comment]
@hanshuebner Could you review this again?

**Review by bungle — APPROVED** [review]
