### PR TITLE
fix(declarative) misleading errors and validation errors

### LINKED ISSUE #5750: Bug: configuration parsing throws wrong errors on missing foreign key relations
### Summary

When a foreign relation is missing, the configuration parser throws misleading errors.

### Steps To Reproduce

Run Kong 2.0.2 with DB-less mode

```bash
$ cat kong.json
{
  "_format_version": "1.1",
  "consumers": [
    {
      "username": "consumer-test",
      "basicauth_credentials": [
        {
          "username": "some_user",
          "password": "some_password"
        }
      ]
    }
  ],
  "plugins": [
    {
      "name": "request-transformer",
      "config": {
        "add": {
          "body": [],
          "headers": [],
          "querystring": []
        },
        "append": {
          "body": [],
          "headers": [
            "X-Another-Header:foo"
          ],
          "querystring": []
        },
        "remove": {
          "body": [],
          "headers": [
            "X-Another-Header"
          ],
          "querystring": []
        },
        "rename": {
          "body": [],
          "headers": [],
          "querystring": []
        },
        "replace": {
          "body": [],
          "headers": [],
          "querystring": [],
          "uri": null
        }
      },
      "route": "does-not-exist",
      "enabled": true,
      "protocols": [
        "http",
        "https"
      ]
    }
  ]
}
$ http :8001/config < kong.json
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 362
Content-Type: application/json; charset=utf-8
Date: Fri, 03 Apr 2020 00:03:11 GMT
Server: kong/2.0.1
X-Kong-Admin-Latency: 275

{
    "code": 14,
    "fields": {
        "consumers": [
            {
                "basicauth_credentials": [
                    {
                        "@entity": [
                            "all or none of these fields must be set: 'password', 'consumer.id'"
                        ]
                    }
                ]
            }
        ]
    },
    "message": "declarative config is invalid: {consumers={{basicauth_credentials={{[\"@entity\"]={\"all or none of these fields must be set: 'password', 'consumer.id'\"}}}}}}",
    "name": "invalid declarative configuration"
}
```

If you remove the broken route relation on the above plugin, then the configuration is correctly parsed.

### Additional Details & Logs

- Kong version (`$ kong version`) 2.0.2

### LINKED ISSUE #5920: Declarative config basic auth credentials on a consumer errors when key auth is defined on a route without a name or id
### Summary and steps to reproduce

This declarative config errors:

```
_format_version: "1.1"

services:
- name: test-service
  routes:
  - paths:
    - /test/path
    plugins:
    - name: key-auth
  url: https://example.com

consumers:
- username: test-user
  basicauth_credentials:
  - username: test-username
    password: test-password
```

```
$ kong config parse test-kong.yaml
Error: Failed parsing:
in 'consumers':
  - in entry 1 of 'consumers':
    in 'basicauth_credentials':
      - in entry 1 of 'basicauth_credentials':
        in '@entity':
          - in entry 1 of '@entity': all or none of these fields must be set: 'password', 'consumer.id'

  Run with --v (verbose) or --vv (debug) for more details
```

Doing one of the following make the error not occur:
* Remove the key-auth plugin on the route
* Remove the basicauth_credentials from the consumer
* Add a name to the route
* Add an ID to the route

For example this config works fine:

```
_format_version: "1.1"

services:
- name: test-service
  routes:
  - name: test-route
    paths:
    - /test/path
    plugins:
    - name: key-auth
  url: https://example.com

consumers:
- username: test-user
  basicauth_credentials:
  - username: test-username
    password: test-password
```

### Additional Details & Logs

- Kong version: 2.0.4 (installed via RPM)
- Operating system: RHEL 7 x64

Logs and config as per above.

The error message seems buggy and related to #5750, but there seems to be an unrelated issue in that I believe this config should be valid in the first place.

### PR DESCRIPTION
**Pull request by bungle**
#### fix(declarative) misleading error may be returned in certain cases

The declarative config validation may return misleading error messages in some cases, see #5750.

#### fix(declarative) validation errors because non-filled primary keys

The validation of declarative configuration could fail when presenting configuration that did not have ids or names or didn't have a cache key.

Here is such configuration:

```yaml
_format_version: "1.1"

services:
- name: test-service
  routes:
  - paths:
    - /test/path
    plugins:
    - name: key-auth
  url: https://example.com

consumers:
- username: test-user
  basicauth_credentials:
  - username: test-username
    password: test-password
```

See #5920

### Issues resolved

Fix #5750
Fix #5920

### CODE REVIEW

File: kong/db/schema/others/declarative_config.lua [hunk 1]
```diff
@@ -554,6 +560,29 @@ local function populate_ids(input, known_entities, parent_entity, by_id, by_key)
 end
 
 
+local function remove_errors(err)
```
Comment (kikito) [inline kong/db/schema/others/declarative_config.lua:563]: suggest rename: `extract_null_errors`
