### PR TITLE
fix(plugins) foreign fields were not always required as they should

### LINKED ISSUE #4875: Credentials can be created in Kong without an association with a consumer
### Summary

In previous versions of Kong, it was not possible to create credentials in Kong without it being associated with a consumer. This seems to be possible in Kong 1.3rc1.
I've verified and this doesn't seem to be possible in Kong 1.2

This might be due to https://github.com/Kong/kong/pull/4713 or a similar change.

### Steps To Reproduce

1. Start Kong 1.3rc1 in DB mode
2.  The following all succeed where they should all fail with a foreign key missing violation:

```bash
$ http :8001/key-auths key=fo
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 96
Content-Type: application/json; charset=utf-8
Date: Wed, 07 Aug 2019 16:34:43 GMT
Server: kong/1.3.0rc1

{
    "consumer": null,
    "created_at": 1565195683,
    "id": "1c16dc9f-cf21-4fdc-92fd-54cd3bf2fea5",
    "key": "fo"
}

$ http post :8001/jwts secret=foo
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 183
Content-Type: application/json; charset=utf-8
Date: Wed, 07 Aug 2019 16:35:06 GMT
Server: kong/1.3.0rc1

{
    "algorithm": "HS256",
    "consumer": null,
    "created_at": 1565195706,
    "id": "6528cd4a-a7e1-409a-8c20-874bcc8f956f",
    "key": "lZ4ZyChYh071nxngeKz6wEX83MGuGGjT",
    "rsa_public_key": null,
    "secret": "foo"
}

$ http post :8001/hmac-auths secret=foo username=not-a-consumer
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 128
Content-Type: application/json; charset=utf-8
Date: Wed, 07 Aug 2019 16:36:50 GMT
Server: kong/1.3.0rc1

{
    "consumer": null,
    "created_at": 1565195810,
    "id": "0ee68d38-8998-44b5-b0d6-14a6b1e4709e",
    "secret": "foo",
    "username": "not-a-consumer"
}

$ http :8001/basic-auths password=foo
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 42
Content-Type: application/json; charset=utf-8
Date: Wed, 07 Aug 2019 16:38:29 GMT
Server: kong/1.3.0rc1

{
    "message": "An unexpected error occurred"
}
```

### Additional Details & Logs

- Kong version (`$ kong version`) 1.3rc1
- Operating system: Docker env

Logs for the basic-auth 500 error:
```
2019/08/07 16:38:29 [error] 31#0: *618893 lua coroutine: runtime error: ...ua/5.1/kong/plugins/basic-auth/basicauth_credentials.lua:30: attempt to index field 'consumer' (a nil value)
stack traceback:
coroutine 0:
        ...ua/5.1/kong/plugins/basic-auth/basicauth_credentials.lua: in function 'hash_password'
        ...ua/5.1/kong/plugins/basic-auth/basicauth_credentials.lua:40: in function 'insert_entity'
        /usr/local/share/lua/5.1/kong/api/endpoints.lua:369: in function 'fn'
        /usr/local/share/lua/5.1/kong/api/init.lua:45: in function </usr/local/share/lua/5.1/kong/api/init.lua:28>
coroutine 1:
        [C]: in function 'resume'
        /usr/local/share/lua/5.1/lapis/application.lua:397: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/lapis/application.lua:167: in function </usr/local/share/lua/5.1/lapis/application.lua:165>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:230: in function 'serve_admin_api'
        content_by_lua(nginx-kong.conf:180):2: in main chunk, client: 172.17.0.1, server: kong_admin, request: "POST /basic-auths HTTP/1.1", host: "localhost:8001"
2019/08/07 16:38:29 [error] 31#0: *618893 [lua] init.lua:162: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:401: ...ua/5.1/kong/plugins/basic-auth/basicauth_credentials.lua:30: attempt to index field 'consumer' (a nil value)
stack traceback:
        ...ua/5.1/kong/plugins/basic-auth/basicauth_credentials.lua: in function 'hash_password'
        ...ua/5.1/kong/plugins/basic-auth/basicauth_credentials.lua:40: in function 'insert_entity'
        /usr/local/share/lua/5.1/kong/api/endpoints.lua:369: in function 'fn'
        /usr/local/share/lua/5.1/kong/api/init.lua:45: in function </usr/local/share/lua/5.1/kong/api/init.lua:28>

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/lapis/application.lua:401: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/lapis/application.lua:167: in function </usr/local/share/lua/5.1/lapis/application.lua:165>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:230: in function 'serve_admin_api'
172.17.0.1 - - [07/Aug/2019:16:38:29 +0000] "POST /basic-auths HTTP/1.1" 500 42 "-" "HTTPie/1.0.2"
        content_by_lua(nginx-kong.conf:180):2: in main chunk, client: 172.17.0.1, server: kong_admin, request: "POST /basic-auths HTTP/1.1", host: "localhost:8001"
2019/08/07 16:38:29 [warn] 31#0: *618893 using uninitialized "kong_proxy_mode" variable, client: 172.17.0.1, server: kong_admin, request: "POST /basic-auths HTTP/1.1", host: "localhost:8001"
```

### PR DESCRIPTION
**Pull request by bungle**
### Summary

The issue originates from converting the old schema to new one where some fields where marked as `default=ngx.null` instead of `required=true`. This PR changes those back to required.

### Issues resolved

Fix #4875

### CODE REVIEW

File: kong/plugins/basic-auth/basicauth_credentials.lua [hunk 1]
```diff
@@ -27,7 +27,11 @@ local hash_password = function(self, cred_id_or_username, cred)
     end
   end
 
-  cred.password = crypto.hash(cred.consumer.id, cred.password)
+  if cred.consumer then
+    cred.password = crypto.hash(cred.consumer.id, cred.password)
+  else
+    cred.password = crypto.hash(utils.uuid(), cred.password)
```
Comment (hishamhm) [inline kong/plugins/basic-auth/basicauth_credentials.lua]: If `cred.consumer` is required, is this case ever going to get hit? (It seems odd to hash something based on a random value, how would this hash ever get verified?)

Comment (bungle) [reply kong/plugins/basic-auth/basicauth_credentials.lua]: @hishamhm, that is a good question, I didn't like to add that, but the hashing seems to happen prior validation (which sucks). And that's why I added that. The validation will still fail, it will just not cry about password being required.
