### PR TITLE
fix(jwt):correct  header delimiter to use comma

### LINKED ISSUE #14429: Incorrect parameter delimiter in JWT plugin `WWW-Authenticate` header
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

3.9

### Description

I noticed that the `WWW-Authenticate` header in JWT plugin uses spaces to separate parameters.
https://github.com/Kong/kong/blob/ed117a6fe801a80ddaa07b5af30ed4c5daabf241/kong/plugins/jwt/handler.lua#L161

According to RFC 7235 (HTTP Authentication) ([Section 4.1](https://datatracker.ietf.org/doc/html/rfc7235#section-4.1)), the parameters in authentication headers should be comma-delimited. 

> ... and each challenge can contain a comma-separated list of authentication parameters.

The correct format should be:
`WWW-Authenticate: Bearer realm="auth-server", error="invalid_token"  `
(Note the comma , between realm and error parameters.)

If I misunderstood the RFC’s requirements for header formatting, kindly clarify or correct me.

### PR DESCRIPTION
**Pull request by dingjiayi**
### Summary

Fix issue https://github.com/Kong/kong/issues/14429 where authentication plugins were using spaces instead of commas to separate parameters in the WWW-Authenticate header. According to RFC 7235 (HTTP Authentication) ([Section 4.1](https://datatracker.ietf.org/doc/html/rfc7235#section-4.1)), the parameters should be comma-delimited.

### Related PR

-  #14436 

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #14429

### CODE REVIEW

File: kong/plugins/jwt/handler.lua [hunk 1]
```diff
@@ -157,8 +157,12 @@ local function do_authentication(conf)
     return error(err)
   end
 
-  local www_authenticate_base = conf.realm and fmt('Bearer realm="%s"', conf.realm) or 'Bearer'
-  local www_authenticate_with_error = www_authenticate_base .. ' error="invalid_token"'
+  local realm = conf.realm and fmt(' realm="%s"', conf.realm) or ""
+  local www_authenticate_base = "Bearer" .. realm
+  local www_authenticate_with_error = www_authenticate_base
+    .. (realm ~= "" and "," or "")
+    .. ' error="invalid_token"'
```
Comment (nowNick) [inline kong/plugins/jwt/handler.lua:164]: I think this looks mostly ok. I'd suggest one change - let's split this logic a little bit. 
```suggestion
  local www_authenticate_base
  local www_authenticate_with_error
  if conf.realm then
    www_authenticate_base = fmt('Bearer realm="%s"', conf.realm)
    www_authenticate_with_error = www_authenticate_base .. ', error="invalid_token"'
  else
    www_authenticate_base = 'Bearer'
    www_authenticate_with_error = www_authenticate_base .. ' error="invalid_token"'    
  end
```

This way we don't have to double check if `conf.realm` exist in order to set `realm` to `""` and then check again if `realm` was set to `""` to determine whether or not use comma.

Comment (samugi) [reply kong/plugins/jwt/handler.lua:164]: other options:

```
local www_authenticate_base
if conf.realm then
  www_authenticate_base = fmt('Bearer realm="%s",', conf.realm)
else
  www_authenticate_base = 'Bearer'
end
local www_authenticate_with_error = www_authenticate_base .. ' error="invalid_token"'
```
or
```
local www_authenticate_base =
    'Bearer' .. (conf.realm and fmt(' realm="%s",', conf.realm) or '')
local www_authenticate_with_error = www_authenticate_base .. ' error="invalid_token"'
```
all are fine by me.

**Review by samugi — COMMENTED** [review]
this just need an entry in `changelog/unreleased`

File: kong/plugins/jwt/handler.lua (hunk 1 above)
Comment (dingjiayi) [reply kong/plugins/jwt/handler.lua]: Thank you both @nowNick and @samugi for your suggestions! I appreciate the feedback.
I think @nowNick's suggestion is very clear and addresses the issue directly by separating the logic more cleanly.
Regarding @samugi's options, they look good but there's a small issue: both options would add a comma at the end of `www_authenticate_base` when `conf.realm` is set (e.g., `Bearer realm=\"test\",`). This would be correct when we're adding more parameters after it, but might not be ideal when `www_authenticate_base` is used alone (like in the \"Unauthorized\" response where we don't add the error parameter).
Thanks again for the review!

Comment (dingjiayi) [reply kong/plugins/jwt/handler.lua]: I've updated the code to use the cleaner approach as suggested.

**Comment by dingjiayi** [comment]
> this just need an entry in `changelog/unreleased`

Added.

**Review by nowNick — APPROVED** [review]
Looks great! Thank you 🚀

File: kong/plugins/jwt/handler.lua (hunk 1 above)
Comment (samugi) [reply kong/plugins/jwt/handler.lua]: oh yeah I didn't realize we were reusing `www_authenticate_base` below - my bad!
