### PR TITLE
fix(router/atc): uri replace didn't works well if contains the optional group

### LINKED ISSUE #13014: Optional capture groups are broken with the request-transformer plugin and traditional_compatible router
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.6

### Current Behavior

When I
- use the `traditional_compatible` router
- create a regex path `~/(gw/)?api/(?<subpath>htest)$`
- match it against `/api/htest`
- add the following request-transformer plugin config:
  ```
  replace:
    uri: /api/v2/$(uri_captures.subpath)
  ```
The route sent upstream is `/api/v2/` instead of `/api/v2/htest`.
When I request `/gw/api/htest` (the `gw/` optional group matches) the route sent upstream is correct: `/api/v2/htest`.

### Expected Behavior

The route sent upstream is `/api/v2/htest`, respecting the `subpath` capture group even if the optional group doesn't match.
The `traditional` router behaves like this, the bug is only observed with `traditional_compatible`.

### Steps To Reproduce

Use this deck config:
```
services:
  - name: htest-deck
    url: http://htest.infra
    routes:
      - name: htest-routes
        paths:
          - ~/(gw/)?api/(?<subpath>htest)$
        strip_path: false
        plugins:
          - name: request-transformer
            config:
              replace:
                uri: /api/v2/$(uri_captures["subpath"])
```
with the `traditional_compatible` router on Kong 3.6.

### Anything else?

debug logs from request-transformer with route `/api/htest`:
```
2024/05/10 10:10:05 [debug] 1284#0: *12328 [kong] access.lua:486 [request-transformer] 8[request-transformer] template `/api/v2/$(uri_captures["subpath"])` rendered to `/api/v2/`
172.21.9.0 - - [10/May/2024:10:10:05 +0000] "GET /api/htest HTTP/1.1" 200 409 "-" "curl/8.4.0" kong_request_id: "882af5474b6f451100612f6d94bca01f"
```

### PR DESCRIPTION
**Pull request by git-hulk**
### Summary

URI captures are not usable if the first capture is an empty string.

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Ticket reference

Fix #13014, KAG-4474

### CODE REVIEW

**Comment by git-hulk** [comment]
Working in fixing test cases

File: kong/router/atc.lua [hunk 1]
```diff
@@ -382,12 +383,16 @@ function _M:matching(params)
 
   local request_prefix = matched_route.strip_path and matched_path or nil
 
+    local uri_captures = nil
+    if matched_path and captures and pl_tablex.size(captures) > 1 then
+      uri_captures = captures
+    end
```
Comment (StarlightIbuki) [inline kong/router/atc.lua:389]:
```suggestion
  local uri_captures = nil
  if matched_path and captures and pl_tablex.size(captures) > 1 then
    uri_captures = captures
  end

```

We use 2 spaces identation.

File: spec/01-unit/08-router_spec.lua [hunk 2]
```diff
@@ -3484,6 +3484,26 @@ for _, flavor in ipairs({ "traditional", "traditional_compatible", "expressions"
...
+
+        local router = assert(new_router(use_case))
+        local _ngx = mock_ngx("GET", "/users/1984/profile",
+          { host = "domain.org" })
+        router._set_ngx(_ngx)
+        local match_t = router:exec()
+        assert.equal("users/", match_t.matches.uri_captures[1])
+        assert.equal("profile", match_t.matches.uri_captures.subpath)
+        assert.same(nil, match_t.matches.uri_captures.scope)
+      end)
```
Comment (StarlightIbuki) [inline spec/01-unit/08-router_spec.lua:3506]:
```suggestion
      end)

```

File: spec/03-plugins/36-request-transformer/02-access_spec.lua [hunk 3]
```diff
@@ -1113,6 +1129,30 @@ describe("Plugin: request-transformer(access) [#" .. strategy .. "]", function()
       local json = assert.request(r).has.jsonbody()
       assert.is_truthy(string.find(json.data, "\"emptyarray\":[]", 1, true))
     end)
+    it("replace request uri with optional capature prefix", function()
```
Comment (StarlightIbuki) [inline spec/03-plugins/36-request-transformer/02-access_spec.lua:1132]:
```suggestion

    it("replace request uri with optional capature prefix", function()
```

File: spec/03-plugins/36-request-transformer/02-access_spec.lua [hunk 4]
```diff
@@ -1113,6 +1129,30 @@ describe("Plugin: request-transformer(access) [#" .. strategy .. "]", function()
...
+        path = "/api/htest",
+        headers = {
+          host = "test29.test"
+        }
+      })
+      assert.response(r).has.status(404)
+      local body = assert(assert.response(r).has.jsonbody())
+      assert.equals("/api/v2/htest", body.vars.request_uri)
+    end)
+    it("replace reqest uri with the capature prefix", function()
```
Comment (StarlightIbuki) [inline spec/03-plugins/36-request-transformer/02-access_spec.lua:1144]:
```suggestion

    it("replace reqest uri with the capature prefix", function()
```

**Review by StarlightIbuki — CHANGES_REQUESTED** [review]
Thanks for your contribution! The PR is correctly done, except for some minor style issues.

File: changelog/unreleased/kong/fix-request-transformer-uri-replace.yml [hunk 5]
```diff
@@ -0,0 +1,4 @@
+message: |
+  **reqeust-transformer**: Fixed the uri replace didn't works well if contains the optional group.
```
Comment (StarlightIbuki) [inline changelog/unreleased/kong/fix-request-transformer-uri-replace.yml:2]:
```suggestion
  **reqeust-transformer**: Fixed an issue where the URI captures are unavailable when an optional group is absent.
```

File: changelog/unreleased/kong/fix-request-transformer-uri-replace.yml [hunk 6]
```diff
@@ -0,0 +1,4 @@
...
+type: bugfix
+scope: Plugin
```
Comment (StarlightIbuki) [inline changelog/unreleased/kong/fix-request-transformer-uri-replace.yml:4]:
```suggestion
scope: Core
```

**Comment by git-hulk** [comment]
@StarlightIbuki Thank you, I did enable the .editorconfig plugin in my IDE, but it seems didn't work correctly. Will take care of this next time.

File: changelog/unreleased/kong/fix-request-transformer-uri-replace.yml [hunk 7]
```diff
@@ -0,0 +1,4 @@
+message: |
+  **reqeust-transformer**: Fixed an issue where the URI captures are unavailable when an optional group is absent.
```
Comment (chronolaw) [inline changelog/unreleased/kong/fix-request-transformer-uri-replace.yml:2]:
```suggestion
  Fixed an issue where the URI captures are unavailable when an optional group is absent.
```
We did not change the code of plugin, so need not to add plugin info in changelog.

File: kong/router/atc.lua [hunk 8]
```diff
@@ -382,12 +383,17 @@ function _M:matching(params)
 
   local request_prefix = matched_route.strip_path and matched_path or nil
 
+  local uri_captures = nil
+  if matched_path and captures and pl_tablex.size(captures) > 1 then
```
Comment (chronolaw) [inline kong/router/atc.lua:387]: should we use `not table.isempty()` to replace `pl_tablex.size`?

File: kong/router/atc.lua [hunk 9]
```diff
@@ -382,12 +383,17 @@ function _M:matching(params)
...
+    uri_captures = captures
+  end
+
   return {
     route           = matched_route,
     service         = service,
     prefix          = request_prefix,
     matches = {
-      uri_captures = (captures and captures[1]) and captures or nil,
+      uri_captures = uri_captures
```
Comment (chronolaw) [inline kong/router/atc.lua:396]:
```suggestion
      uri_captures = uri_captures,
```

File: spec/03-plugins/36-request-transformer/02-access_spec.lua [hunk 10]
```diff
@@ -1114,6 +1130,32 @@ describe("Plugin: request-transformer(access) [#" .. strategy .. "]", function()
       assert.is_truthy(string.find(json.data, "\"emptyarray\":[]", 1, true))
     end)
 
+    it("replace request uri with optional capture prefix", function()
```
Comment (chronolaw) [inline spec/03-plugins/36-request-transformer/02-access_spec.lua:1133]:
```suggestion
    it("replaces request uri with optional capture prefix", function()
```

File: spec/03-plugins/36-request-transformer/02-access_spec.lua [hunk 11]
```diff
@@ -1114,6 +1130,32 @@ describe("Plugin: request-transformer(access) [#" .. strategy .. "]", function()
...
+        headers = {
+          host = "test29.test"
+        }
+      })
+      assert.response(r).has.status(404)
+      local body = assert(assert.response(r).has.jsonbody())
+      assert.equals("/api/v2/htest", body.vars.request_uri)
+    end)
+
+    it("replace request uri with the capature prefix", function()
```
Comment (chronolaw) [inline spec/03-plugins/36-request-transformer/02-access_spec.lua:1146]:
```suggestion
    it("replaces request uri with the capature prefix", function()
```

**Review by nowNick — APPROVED** [review]
Looks good to me! Thank you for your contribution 🚀

File: kong/router/atc.lua (hunk 8 above)
Comment (StarlightIbuki) [reply kong/router/atc.lua:387]: > This place requires the size of `captures` to be > 1, which means capturing at least one element from the URI. So guess we cannot use table.isempty here, is that right? @StarlightIbuki

I'm unsure if `captures[0]` is used to return the whole match here, but I suppose it's not. The original condition was to check if there's at least 1 match, thus if I'm right, we need to use `is_emtpy` instead.

@chronolaw any idea?

File: changelog/unreleased/kong/fix-request-transformer-uri-replace.yml [hunk 12]
```diff
@@ -0,0 +1,4 @@
+message: |
+  Fixed an issue where the URI captures are unavailable when an optional group is absent.
```
Comment (StarlightIbuki) [inline changelog/unreleased/kong/fix-request-transformer-uri-replace.yml:2]:
```suggestion
  Fixed an issue where the URI captures are unavailable when the first capture group is absent.
```

Sorry, my mistake.

File: kong/router/atc.lua (hunk 8 above)
Comment (chronolaw) [reply kong/router/atc.lua:387]: I think that we should use `table.isempty`, see: https://github.com/Kong/atc-router/blob/main/lib/resty/router/context.lua#L76

File: kong/router/atc.lua [hunk 13]
```diff
@@ -2,6 +2,7 @@ local _M = {}
 local _MT = { __index = _M, }
 
 
+local pl_tablex = require("pl.tablex")
```
Comment (StarlightIbuki) [inline kong/router/atc.lua:5]:
```suggestion
local isempty= require("table.isempty")
```

File: kong/router/atc.lua (hunk 8 above)
Comment (StarlightIbuki) [inline kong/router/atc.lua:387]:
```suggestion
  if matched_path and captures and not isempty(captures) then
```

**Review by StarlightIbuki — CHANGES_REQUESTED** [review]
Please use `isempty` instead.

File: kong/router/atc.lua (hunk 8 above)
Comment (chronolaw) [reply kong/router/atc.lua:387]: Could we remove the condition `matched_path`? If no matching the captures must be `nil`

Comment (chronolaw) [reply kong/router/atc.lua:387]: This line could be :
```
local uri_captures = (captures and not tb_isempty(captures)) and captures or nil
```

**Review by StarlightIbuki — APPROVED** [review]

File: kong/router/atc.lua [hunk 14]
```diff
@@ -2,6 +2,7 @@ local _M = {}
 local _MT = { __index = _M, }
 
 
+local isempty= require("table.isempty")
```
Comment (chronolaw) [inline kong/router/atc.lua:5]: Could we move this line below `local tb_new` and rename it to `tb_isempty`?

File: kong/router/atc.lua (hunk 8 above)
Comment (git-hulk) [reply kong/router/atc.lua]: > I'm unsure if captures[0] is used to return the whole match here, but I suppose it's not.

Yes, captures[0] will return the whole match. And change to is_empty might break the old behavior, like this test case: https://github.com/Kong/kong/blob/master/spec/01-unit/08-router_spec.lua#L1084

The current code will return a nil `uri_capatured`, but changed to `table.isempty` will become not nil(uri_capature[0]). Not sure if it's expected, if yes, then I can change the corresponding test cases as well:

```
Failure → spec/01-unit/08-router_spec.lua @ 1055
Router (flavor = expressions) select() [uri regex] matches a [uri regex] even if a [prefix uri] got a match
spec/01-unit/08-router_spec.lua:1084: Expected objects to be the same.
Passed in:
(table: 0x01367e2758) {
  [0] = '/route/persons/123/profile' }
Expected:
(nil)

stack traceback:
        spec/01-unit/08-router_spec.lua:1084: in function <spec/01-unit/08-router_spec.lua:1055>
```

Comment (git-hulk) [reply kong/router/atc.lua]: cc @StarlightIbuki @chronolaw

File: spec/01-unit/08-router_spec.lua [hunk 15]
```diff
@@ -3484,6 +3484,27 @@ for _, flavor in ipairs({ "traditional", "traditional_compatible", "expressions"
         assert.is_nil(match_t.matches.headers)
       end)
 
+      it("uri_captures works well with the optional capture group. Fix #13014", function()
```
Comment (chronolaw) [inline spec/01-unit/08-router_spec.lua:3487]: I think that it is not a proper test case, It did not re-produce the situation in #13014.
The test uri should be `1984/profile`, and `match_t.matches.uri_captures[1]` should be `nil`

Perhaps we should add another test case for it.

File: kong/router/atc.lua (hunk 14 above)
Comment (git-hulk) [reply kong/router/atc.lua:5]: I have tested this on my side, it will break the old test cases: https://github.com/Kong/kong/pull/13024#discussion_r1599677152

File: kong/router/atc.lua (hunk 8 above)
Comment (StarlightIbuki) [reply kong/router/atc.lua]: @git-hulk Please revert my commit

Comment (git-hulk) [reply kong/router/atc.lua]: OK, I didn't apply those commits yet.

Comment (chronolaw) [reply kong/router/atc.lua]: I got. `captures[0]` should not be treated as a capture, right?

File: spec/01-unit/08-router_spec.lua (hunk 15 above)
Comment (git-hulk) [reply spec/01-unit/08-router_spec.lua:3487]: @chronolaw OK, I will add another test case after the previous question is confirmed.

File: kong/router/atc.lua (hunk 8 above)
Comment (git-hulk) [reply kong/router/atc.lua]: Yes, that's why I check if the table size > 1 instead of >= 1

Comment (chronolaw) [reply kong/router/atc.lua]: Then we should use `table.nkeys`, it is better than pl.tablex

File: kong/router/atc.lua (hunk 14 above)
Comment (chronolaw) [reply kong/router/atc.lua:5]: should use `table.nkeys` as `tb_nkeys`.

File: kong/router/atc.lua (hunk 8 above)
Comment (git-hulk) [reply kong/router/atc.lua]: @chronolaw Thanks, will change to `table.nkeys`

Comment (chronolaw) [reply kong/router/atc.lua]: I think that `>= 2` is more clear for reviewer, it will reminder the people there are two capture results.

Comment (chronolaw) [reply kong/router/atc.lua]: We should also add a comment for this condition, it is very easy to confuse the reviewer.

**Comment by git-hulk** [comment]
@StarlightIbuki @chronolaw Please take a look at the last commit again.

File: kong/router/atc.lua [hunk 16]
```diff
@@ -2,6 +2,7 @@ local _M = {}
 local _MT = { __index = _M, }
 
 
+local tb_nkeys = require("table.nkeys")
```
Comment (chronolaw) [inline kong/router/atc.lua:5]: Moving this line below `tb_new` is better.

File: kong/router/atc.lua [hunk 17]
```diff
@@ -382,12 +383,17 @@ function _M:matching(params)
 
   local request_prefix = matched_route.strip_path and matched_path or nil
 
+  local uri_captures = nil
+  if matched_path and captures and tb_nkeys(captures) > 1 then
```
Comment (chronolaw) [inline kong/router/atc.lua:387]: As we talked before, I suggest to use `>= 2` and add some comments to explain it.

File: spec/01-unit/08-router_spec.lua [hunk 18]
```diff
@@ -3484,6 +3484,29 @@ for _, flavor in ipairs({ "traditional", "traditional_compatible", "expressions"
...
+            },
+          },
+        }
+
+        local router = assert(new_router(use_case))
+        local _ngx = mock_ngx("GET", "/1984/profile",
+                                                 { host = "domain.org" })
+        router._set_ngx(_ngx)
+        local match_t = router:exec()
+        if flavor ~= "traditional" then
```
Comment (chronolaw) [inline spec/01-unit/08-router_spec.lua:3503]: Do we need this? Should it also work for traditional flavor?

Comment (git-hulk) [reply spec/01-unit/08-router_spec.lua:3503]: For the traditional flavor, it will return `false` instead of `nil`.

File: kong/router/atc.lua (hunk 17 above)
Comment (git-hulk) [reply kong/router/atc.lua]: Done.

File: kong/router/atc.lua (hunk 16 above)
Comment (git-hulk) [reply kong/router/atc.lua]: Done

File: spec/01-unit/08-router_spec.lua (hunk 18 above)
Comment (chronolaw) [reply spec/01-unit/08-router_spec.lua:3503]: Got, thanks.

File: kong/router/atc.lua [hunk 19]
```diff
@@ -382,12 +383,19 @@ function _M:matching(params)
 
   local request_prefix = matched_route.strip_path and matched_path or nil
 
+  local uri_captures = nil
+  -- The whole matched uri will be put in captures[0], so we need to check
+  -- the number of table keys >= 2 to determine if there has any uri captured.
```
Comment (chronolaw) [inline kong/router/atc.lua:388]:
```suggestion
  -- the number of table keys >= 2 to determine if there is any uri captured.
```

File: kong/router/atc.lua [hunk 20]
```diff
@@ -382,12 +383,19 @@ function _M:matching(params)
...
+  if matched_path and captures and tb_nkeys(captures) >= 2 then
```
Comment (chronolaw) [inline kong/router/atc.lua:389]: Do we really need this `matched_path` condition?

File: spec/01-unit/08-router_spec.lua [hunk 21]
```diff
@@ -3484,6 +3484,29 @@ for _, flavor in ipairs({ "traditional", "traditional_compatible", "expressions"
...
+            route   = {
+              id = "e8fb37f1-102d-461e-9c51-6608a6bb8101",
+              paths = { [[~/(users/)?1984/(?<subpath>profile)$]] },
+            },
+          },
+        }
+
+        local router = assert(new_router(use_case))
+        local _ngx = mock_ngx("GET", "/1984/profile",
+                                                 { host = "domain.org" })
```
Comment (chronolaw) [inline spec/01-unit/08-router_spec.lua:3500]: Style: align to `"GET"` above line

File: spec/01-unit/08-router_spec.lua [hunk 22]
```diff
@@ -3484,6 +3484,29 @@ for _, flavor in ipairs({ "traditional", "traditional_compatible", "expressions"
...
+        router._set_ngx(_ngx)
+        local match_t = router:exec()
+        if flavor ~= "traditional" then
+          assert.is_nil(match_t.matches.uri_captures[1])
```
Comment (chronolaw) [inline spec/01-unit/08-router_spec.lua:3504]: Should we use `assert.falsy()` to remove `if flavor ~= "traditional" then ... end`

**Review by chronolaw — APPROVED** [review]
LGTM, thank you @git-hulk.
@StarlightIbuki , could you take a look again?

File: kong/router/atc.lua [hunk 23]
```diff
@@ -382,12 +383,19 @@ function _M:matching(params)
 
   local request_prefix = matched_route.strip_path and matched_path or nil
 
+  local uri_captures = nil
+  -- The whole matched uri will be put in captures[0], so we need to check
+  -- the number of table keys >= 2 to determine if there is any uri captured.
+  if captures and tb_nkeys(captures) >= 2 then
```
Comment (ADD-SP) [inline kong/router/atc.lua:389]: The function `tb_nkeys` is an `O(n)` operation, and it is in the hot proxy path. I‘m concerned about the performance impact.

The [atc-router knows the length of this table](https://github.com/Kong/atc-router/blob/ffd11db657115769bf94f0c4f915f98300bc26b6/lib/resty/router/context.lua#L116), getting it from that could get performance some benefits.

**Review by ADD-SP — CHANGES_REQUESTED** [review]
@git-hulk Thanks for your contribution, this PR looks good to me, except for the potential performance concern.

I've blocked this PR, we may need to do performance testing against this PR, or other works.

I think we should fix this bug and it would be better not to introduce performance regressions.

File: kong/router/atc.lua (hunk 23 above)
Comment (ADD-SP) [reply kong/router/atc.lua:389]: @chronolaw @StarlightIbuki What do you think?

Comment (git-hulk) [reply kong/router/atc.lua:389]: @ADD-SP Sure, it might be fine since the captures should be generally a small table.

Comment (StarlightIbuki) [reply kong/router/atc.lua:389]: @ADD-SP I have a simpler solution: set the `captures[0]` to zero and then check with `next(captures)`.

Comment (ADD-SP) [reply kong/router/atc.lua:389]: > @ADD-SP I have a simpler solution: set the captures[0] to nil and then check with next(captures).

This is hard to understand.

Comment (chronolaw) [reply kong/router/atc.lua:389]: > @ADD-SP I have a simpler solution: set the `captures[0]` to nil and then check with `next(captures)`.

It is a little hacky.

Comment (dndx) [reply kong/router/atc.lua:389]: Performance is more important than straightforwardness, especially on hot proxy path. For future maintainers, comments are what provides context.

Comment (git-hulk) [reply kong/router/atc.lua:389]: I saw @chronolaw has submitted a PR to return the capture count. Will change the code after it's merged.

Comment (dndx) [reply kong/router/atc.lua:389]: Will this work, I think the intention is reasonably clear?

`uri_captures = (captures and captures[1] or next(captures, 1)) and captures or nil`

Comment (nowNick) [reply kong/router/atc.lua:389]: I think there are 2 options here:
1. Do nothing and go with what we have here
2. Extend ATC Router

Regarding option 1:
Even if `tb_nkeys` is an `O(n)` operation it does not increase the overall time complexity of this function as it's generally `O(n)`. The next question is how many other `O(n)` operations come here into play so that we could estimate the impact of adding this one. From what I see there are at least 2 other `O(n)` calls: 
- here: https://github.com/Kong/atc-router/blob/main/lib/resty/router/context.lua#L118
- and here: https://github.com/Kong/atc-router/blob/main/src/ffi.rs#L246

So adding a third one will decrease the performance here by ~33% with regard to captures length. Now I reckon - realistically the captures length _shouldn't_ be that long. The URLs are usually at most around 2k characters - maybe up to 8k so in the worst case scenario we have 8k captures.
Now having said all that - I think it might not be an issue but on the other hand it's a hot path and every bit matters so I think we'd need to perf test it.

Regarding option 2:
The captures length is _right there_. If it's helpful we can just return with captures table: https://github.com/Kong/atc-router/blob/main/lib/resty/router/context.lua#L115

Comment (dndx) [reply kong/router/atc.lua:389]: We can probably just remove this check, as `captures` will naturally be `nil` if no regex match has taken place.

Comment (git-hulk) [reply kong/router/atc.lua:389]: > I agree with dndx. we could remove this logic ( if captures ... end) and let  uri_captures = captures.

I cannot get this point. It returns captures[0] = {whole match patch} even if no regex matched, so it won't be nil without changing the ATC router.

Comment (git-hulk) [reply kong/router/atc.lua]: @dndx @chronolaw @StarlightIbuki @ADD-SP @nowNick I have updated this patch with `next` and it should remove the O(N) operation for now, would you mind taking a look again?

Comment (git-hulk) [reply kong/router/atc.lua:389]: @chronolaw @dndx @ADD-SP @StarlightIbuki @nowNick  Is it good to change to 


```lua
-- The whole match path will be placed in captures if it's matched,
-- and we need to check if any other fields inside captures.
-- The `captures[1] or captures[0] and next(captures, 0)` is to check if any other fields except captures[0]. 
uri_captures = (captures and (captures[1] or captures[0] and next(captures, 0))) and captures or nil
```

Comment (chronolaw) [reply kong/router/atc.lua:389]: We are still in discussion, just give us more time, thanks.

Comment (ADD-SP) [reply kong/router/atc.lua:389]: > @ADD-SP I have a simpler solution: set the captures[0] to nil and then check with next(captures).

@StarlightIbuki I think we can call `next` twice, it should be enough, and don't forget to add a comment to explain it in detail.

File: kong/router/atc.lua [hunk 24]
```diff
@@ -344,6 +344,16 @@ local function set_upstream_uri(req_uri, match_t)
 end
 
 
+-- captures has the form { [0] = full_path, [1] = capture1, [2] = capture2, ... }
```
Comment (ADD-SP) [inline kong/router/atc.lua:347]: @StarlightIbuki I think the `captures` might have string keys. Am I right @chronolaw ?

Comment (chronolaw) [reply kong/router/atc.lua:347]: Of course, that is named capture.

File: kong/router/atc.lua [hunk 25]
```diff
@@ -344,6 +344,16 @@ local function set_upstream_uri(req_uri, match_t)
...
+-- and captures[0] will be the full matched path
+-- this function tests if there are captures other than the full path
+-- by checking if there are 2 or more than 2 keys
+local function has_capture(captures)
```
Comment (chronolaw) [inline kong/router/atc.lua:351]: I think that we could define function `get_captures(captures)`,
which will return captures table.

File: kong/router/atc.lua [hunk 26]
```diff
@@ -344,6 +344,16 @@ local function set_upstream_uri(req_uri, match_t)
...
+  local next_i = next(captures)
+  return next_i and next(captures, next_i) ~= nil
```
Comment (git-hulk) [inline kong/router/atc.lua:353]: Good workaround.

File: kong/router/atc.lua [hunk 27]
```diff
@@ -344,6 +344,16 @@ local function set_upstream_uri(req_uri, match_t)
 end
 
 
+-- captures has the form { [0] = full_path, [1] = capture1, [2] = capture2, ... }
+-- and captures[0] will be the full matched path
+-- this function tests if there are captures other than the full path
+-- by checking if there are 2 or more than 2 keys
+local function has_capture(captures)
+  local next_i = next(captures)
```
Comment (git-hulk) [inline kong/router/atc.lua:352]: `captures` should be possible to nil? so might need to check if it's nil before using the `next` function.

Comment (git-hulk) [inline kong/router/atc.lua:352]:
```suggestion
  if not captures then
    return nil
  end
  local next_i = next(captures)
```

File: kong/router/atc.lua [hunk 28]
```diff
@@ -344,6 +344,19 @@ local function set_upstream_uri(req_uri, match_t)
 end
 
 
+-- captures has the form { [0] = full_path, [1] = capture1, [2] = capture2, ... }
+-- and captures[0] will be the full matched path
+-- this function tests if there are captures other than the full path
+-- by checking if there are 2 or more than 2 keys
+local function has_capture(captures)
+  if not captures then
+    return nil
```
Comment (chronolaw) [inline kong/router/atc.lua:353]: should be `return false`?

File: kong/router/atc.lua [hunk 29]
```diff
@@ -344,6 +344,19 @@ local function set_upstream_uri(req_uri, match_t)
...
+  end
+  local next_i = next(captures)
```
Comment (chronolaw) [inline kong/router/atc.lua:355]: `next` should be localized at the module level like others (pairs/ipairs)

File: kong/router/atc.lua (hunk 28 above)
Comment (git-hulk) [reply kong/router/atc.lua:353]: Oh, yes. return false would be better since it's a has_xxx function.

Comment (git-hulk) [inline kong/router/atc.lua:353]:
```suggestion
    return false
```

File: kong/router/atc.lua [hunk 30]
```diff
@@ -344,6 +344,19 @@ local function set_upstream_uri(req_uri, match_t)
 end
 
 
+-- captures has the form { [0] = full_path, [1] = capture1, [2] = capture2, ... }
```
Comment (StarlightIbuki) [inline kong/router/atc.lua:347]:
```suggestion
-- captures has the form { [0] = full_path, [1] = capture1, [2] = capture2, ..., ["named1"] = named1, ... }
```

**Comment by git-hulk** [comment]
@dndx @nowNick @ADD-SP @samugi  Would you mind taking a look again?

File: kong/router/atc.lua (hunk 29 above)
Comment (ADD-SP) [reply kong/router/atc.lua:355]: @git-hulk Could you please apply this suggestion?

Comment (git-hulk) [reply kong/router/atc.lua:356]: @ADD-SP Sure, done in the last commit.

**Review by chronolaw — APPROVED** [review]

**Review by ADD-SP — APPROVED** [review]
@git-hulk Thank you for your contribution!

**Comment by git-hulk** [comment]
Thanks all for your help!
