### PR TITLE
fix(admin) empty url sugar attribute, see #3448

### LINKED ISSUE #3448: 500 error when adding a Service with an empty "url" value
Executing `http :8001/services name=test url=` triggers:

```
lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/api/api_helpers.lua:81: attempt to index local 'parsed_url' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/api/api_helpers.lua: in function 'resolve_url_params'
	/usr/local/share/lua/5.1/kong/api/routes/services.lua:17: in function </usr/local/share/lua/5.1/kong/api/routes/services.lua:16>
coroutine 1:
	[C]: in function 'resume'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
	content_by_lua(nginx-kong.conf:281):2: in function <content_by_lua(nginx-kong.conf:281):1>, client: 172.18.0.1, server: kong_admin, request: "POST /services HTTP/1.1", host: "localhost:8001"
2018/05/10 07:49:03 [error] 116#0: *38976 [lua] init.lua:135: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:397: /usr/local/share/lua/5.1/kong/api/api_helpers.lua:81: attempt to index local 'parsed_url' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/api/api_helpers.lua: in function 'resolve_url_params'
	/usr/local/share/lua/5.1/kong/api/routes/services.lua:17: in function </usr/local/share/lua/5.1/kong/api/routes/services.lua:16>

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/lapis/application.lua:397: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
	content_by_lua(nginx-kong.conf:281):2: in function <content_by_lua(nginx-kong.conf:281):1>, client: 172.18.0.1, server: kong_admin, request: "POST /services HTTP/1.1", host: "localhost:8001"
```

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Fixes unexpected error on admin api when using invalid `url´ sugar attribute on services endpoints reported by @thefosk.

### Issues resolved

Fix #3448

### CODE REVIEW

File: kong/api/api_helpers.lua [hunk 1]
```diff
@@ -3,6 +3,7 @@ local utils = require "kong.tools.utils"
 local url = require "socket.url"
 
 local type = type
+local null = ngx.null
```
Comment (thibaultcha) [inline kong/api/api_helpers.lua]: This will upset the linter

Comment (bungle) [reply kong/api/api_helpers.lua]: fixed.
