### PR TITLE
fix(declarative) send config updates to stream subsystem via Unix domain

### LINKED ISSUE #5656: stream routing does not work in DB-less and hybrid mode
### Summary

Stream routes are not propagated in DB-less mode and Kong always closes the TCP connections with an error log entry of no routes found. This works in DB-mode.

### Steps To Reproduce

Populate Kong with following configuration:
```
_format_version: "1.1"
services:
- connect_timeout: 60000
  host: httpbin.org
  name: httpbin.httpbin.80
  port: 80
  protocol: tcp
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: httpbin.example-app1.0
    protocols:
    - tcp
    destinations:
    - port: 9000
```

`telnet localhost 9000` will not work.

Run the same setup with postgres and that works.

### Additional Details & Logs

- Kong version (`$ kong version`) 2.0.2
- Operating system: Docker

### PR DESCRIPTION
**Pull request by dndx**
socket

Currently, the stream subsystem receives the declarative config from
the filesystem only. Once Kong is running, updating the declarative config
through `/config` admin API no longer propagates to the stream
subsystem. In the long term we will have shared shdict between `http`
and `stream` subsystem which solves the problem. However this PR
provides a temporary and clean solution for getting around the issue without
introducing new OpenResty patches, and can be reverted in the future
easily once situation changes.

Fixes #5656

### CODE REVIEW

File: kong/init.lua [hunk 1]
```diff
@@ -1155,4 +1159,38 @@ function Kong.serve_cluster_listener(options)
 end
 
 
+do
+  local declarative = require("kong.db.declarative")
+  local cjson = require("cjson.safe")
+
+  function Kong.stream_config_listener()
+    kong_global.set_phase(kong, PHASES.admin_api)
```
Comment (hbagdi) [inline kong/init.lua:1167]: This is a bit hacky but I do vaguely recall running into the same problem in any server block that uses PDK. Is it possible to avoid this in any way?

File: kong/init.lua [hunk 2]
```diff
@@ -1155,4 +1159,38 @@ function Kong.serve_cluster_listener(options)
...
+
+    local sock = ngx.req.socket()
+    if not sock then
+      ngx_log(ngx_CRIT, "unable to obtain request socket")
```
Comment (hbagdi) [inline kong/init.lua:1171]: `return` at this point.

File: kong/init.lua [hunk 3]
```diff
@@ -1155,4 +1159,38 @@ function Kong.serve_cluster_listener(options)
...
+    end
+
+    local data, err = sock:receive("*a")
+    if err then
+      ngx_log(ngx_CRIT, "unable to receive new config: ", err)
```
Comment (hbagdi) [inline kong/init.lua:1176]: `return` at this point.

File: kong/templates/nginx_kong_stream.lua [hunk 4]
```diff
@@ -119,5 +119,15 @@ server {
         Kong.log()
     }
 }
+
+server {
+    listen unix:${{PREFIX}}/stream_config.sock;
+
+    error_log  ${{PROXY_ERROR_LOG}} ${{LOG_LEVEL}};
```
Comment (hbagdi) [inline kong/templates/nginx_kong_stream.lua:126]: The `content_by_lua_block` will be executed in the context of Admin API only. Can we change the error output to `ADMIN_ERROR_LOG`?

File: kong/init.lua (hunk 1 above)
Comment (dndx) [reply kong/init.lua:1167]: This code path should't use PDK at all, but removing it shouldn't hurt either.

It was added only for styling reasons.

File: kong/init.lua [hunk 5]
```diff
@@ -1155,4 +1159,39 @@ function Kong.serve_cluster_listener(options)
...
+    end)
+
+    if err == "no memory" then
+      kong.log.err("not enough cache space for declarative config")
+      return
+    end
+
+    if not ok then
+      kong.log.err("failed loading declarative config into cache: ", err)
+    end
```
Comment (thibaultcha) [inline kong/init.lua:1192]: Easier to read and less prone to forgetting a `return` here in the future should we add code below:
```lua
if not ok then
  if err == "no memory"
    kong.log.err("not enough cache space for declarative config")
  
  else
    kong.log.err("failed loading declarative config into cache: ", err)
  end

  return
end
```

Also, we should make the "no memory" error actionable - instruct users how to increase the cache space, i.e. which config property to tweak.

File: kong/templates/nginx_kong_stream.lua [hunk 6]
```diff
@@ -119,5 +119,15 @@ server {
         Kong.log()
     }
 }
+
+server {
```
Comment (thibaultcha) [inline kong/templates/nginx_kong_stream.lua:123]: We should probably only inject this block when `strategy` is `off` (or whenever the `/config` endpoint is available anyway)? Especially given NGINX doesn't handle unix socket file very elegantly in some cases...

File: kong/init.lua [hunk 7]
```diff
@@ -1155,4 +1159,39 @@ function Kong.serve_cluster_listener(options)
...
 
 
+do
+  local declarative = require("kong.db.declarative")
+  local cjson = require("cjson.safe")
+
+  function Kong.stream_config_listener()
+    local sock = ngx.req.socket()
+    if not sock then
+      ngx_log(ngx_CRIT, "unable to obtain request socket")
```
[the remark this answers is not in the document]
Comment (thibaultcha) [reply kong/init.lua:1169]: Also, why not catching the second return value - `err`?

File: kong/init.lua [hunk 8]
```diff
@@ -1155,4 +1159,39 @@ function Kong.serve_cluster_listener(options)
...
+      return
+    end
+
+    local data, err = sock:receive("*a")
+    if err then
```
Comment (kikito) [inline kong/init.lua:1174]:
```suggestion
    if not data then
```
