### PR TITLE
fix(hmac): add missing www-authenticate headers

### LINKED ISSUE #7772: WWW-Authenticate header not present when Kong and plugins return HTTP status 401
### Summary
- Kong version (`$ kong version`) - 2.4.1
According to the HTTP specification for 401 error, https://httpwg.org/specs/rfc7235.html#status.401, WWW-Authenticate header field containing at least one challenge applicable to the target resource must be returned in the response.

At least the following plugins were observed to not returning the header when returning 401.
1) basic-auth
2) key-auth
3) ldap-auth
4) jwt

For Oauth2 related plugins **oauth2** and **jwt**, below are additional requirements from the related RFCs. They further define what needs to be included in the WWW-Authenticate header.

1) https://datatracker.ietf.org/doc/html/rfc6750#section-3
2) https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

### Steps To Reproduce
Exercise any unit tests of those plugins that would return 401 error and add an assertion in those test to detect the header, the assertion would fail.

For example in jwt pluging 03_acces_spec.lua, add the **LAST** assertion and execute the test, it will fail.

    describe("refusals", function()
      it("returns 401 Unauthorized if no JWT is found in the request", function()
        local res = assert(proxy_client:send {
          method  = "GET",
          path    = "/request",
          headers = {
            ["Host"] = "jwt1.com",
          }
        })
        assert.res_status(401, res)
        assert.not_nil(body.headers["WWW-Authenticate"])
      end)

### PR DESCRIPTION
**Pull request by nowNick**
### Summary

When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. HMAC auth was missing this header.

### Related PRs:
- https://github.com/Kong/kong/pull/11792
- https://github.com/Kong/kong/pull/11794
- https://github.com/Kong/kong/pull/11795
- https://github.com/Kong/kong/pull/11820
- https://github.com/Kong/kong/pull/11833

### RFCs & Materials

- https://httpwg.org/specs/rfc7235.html#status.401
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [x] N/A ~~There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~~

### Full changelog

- add `WWW-Authenticate` header to hmac 401 response

### Issue reference

- Fix #7772
- KAG-321

### CODE REVIEW

**Review by hanshuebner — APPROVED** [review]

File: kong/plugins/hmac-auth/schema.lua [hunk 1]
```diff
@@ -29,6 +29,7 @@ return {
               elements = { type = "string", one_of = ALGORITHMS },
               default = ALGORITHMS,
           }, },
+          { realm = { description = "When authentication fails the plugin sends `WWW-Authenticate` header with `realm` attribute value.", type = "string", required = false }, },
```
Comment (jschmid1) [inline kong/plugins/hmac-auth/schema.lua:32]: This requires backwards-compat changes, right?

**Review by jschmid1 — CHANGES_REQUESTED** [review]

File: kong/plugins/hmac-auth/schema.lua (hunk 1 above)
Comment (nowNick) [reply kong/plugins/hmac-auth/schema.lua:32]: You're right - without the backwards-compat changes the config is rejected by DP. I've created a that fixes it:
https://github.com/Kong/kong/pull/13042

@jschmid1 , @hanshuebner could you guys take a look at it?

Comment (nowNick) [reply kong/plugins/hmac-auth/schema.lua:32]: + I've also added proper backwards-compat changes.

**Review by hanshuebner — APPROVED** [review]

**Review by jschmid1 — APPROVED** [review]

**Comment by AndyZhang0707** [comment]
@nowNick please help and manually cherry-pick to ee, thanks.
